import { useEffect, useRef } from "react";

/**
 * The ten empty-state drawings, printed as a halftone screen.
 *
 * This is the engine from the Astrolabe landing hero (`src/DotField.jsx` in
 * astrolabe-landing), reduced to a single still frame. A fixed lattice of
 * cells; each cell draws exactly one round mark whose RADIUS and ALPHA are both
 * driven by one scalar value. There is no second layer and no blend mode — the
 * gradient you see is mark-area modulation, the way a printing screen makes a
 * tone.
 *
 * What the field carries is a shaded solid. Each object is modelled in one 2:1
 * isometric space and lit by one lamp, so its faces come out at different tones
 * and the screen renders them at different dot densities. That is the whole
 * reason this reads as an object rather than as a traced outline: an outline
 * has nothing for a screen to do.
 *
 * The ruling is finer than the hero's. The hero rules at 4px across a 2800px
 * canvas — 700 cells — and a 180px illustration at that pitch would be 45 cells
 * and could not hold a form. A small reproduction gets a finer screen, which is
 * the same relationship a book plate has to a poster.
 *
 * Fields are 4-bit, one nibble per cell, base64. 2.5KB each, against the 110KB
 * PNG apiece they replace, and they carry no colour of their own: the ink is
 * resolved from the element's own `currentColor` against the background it
 * actually sits on, and the tone travels the app's own ladder — mute, the
 * element's colour, the accent, bright — so the set follows the theme rather
 * than being a light-theme raster with `filter: invert()` over it. See `ramp`.
 */
export type EmptyStateArt =
  | "activity"
  | "archive"
  | "filtered"
  | "inbox"
  | "issues"
  | "people"
  | "projects"
  | "space"
  | "specs"
  | "unavailable";

/** The screen. Pitch and dot radius are in CSS px and are not scalable — a
 *  halftone that resizes is no longer a halftone, so the ruling is fixed and a
 *  plate is as big as the drawing on it. The lattice is the authoring grid; see
 *  `inkBox` for why nothing is drawn at its full extent. */
const COLS = 72;
const ROWS = 52;
const CELL = 2.5;
const MAX_R = 1.0;

const FIELDS: Record<EmptyStateArt, string> = {
  // a paper roll, part of it unspooled
  activity:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF7" +
    "uZlyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY7dy7mGUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbv/u3cu5" +
    "hlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa////7t3LuYZSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP/+7v/u7dy6mG" +
    "UwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAz//u7u7/7u3cuphmMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI//7d3u7u/+7t3LqYdj" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAd7u3d3d3u7v/u7dy6mHYwAAAAAAAAAAAAAAAAAAAAAAAAAAA83d3d3d3d7u7/7u3Muph2MA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAa3d3d3d3d3d3u7u7dy7l1ZRAAAAAAAAAAAAAAAAAAAAAAAABMzc3d3d3d3d3d3u7u2WREREAAAA" +
    "AAAAAAAAAAAAAAAAAAAAfMzM3M3d3d3d3d3d7sVERERDAAAAAAAAAAAAAAAAAAAAAAAYzMzMzNzN3d3d3d3d3YRERERRAAAAAAAA" +
    "AAAAAAAAAAAAAAOszMzMzMzMzd3d3d3d3WREREQwAAAAAAAAAAAAAAAAAAAAAGu7vMzMzMzMzM3N3d3d1kREREQAAAAAAAAAAAAA" +
    "AAAAAAAAKbu7u7zMzMzMzMzMzNzcZERERTAAAAAAAAAAAAAAAAAAAAAGu7u7u7u8vMzMzMzMzMzFREREUgAAAAAAAAAAAAAAAAAA" +
    "AAOaq6u7u7u7u7vMzMzMzMtURERDAAAAAAAAAAAAAAAAAAAAAoqqqquru7u7u7u7y8zMzMVERFMAAAAAAAAAAAAAAAAAAAAAOaqq" +
    "qqqqq7u7u7u7u8vMyAIzMgAAAAAAAAAAAAAAAAAAAAAAAWmqqqqqqqu7u7u7u7u7YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFpqqqq" +
    "qqqrq7u7u7uzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaamqqqqqqqq7u7kQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWmaqqqq" +
    "qqqqu2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZmqqqqqqqkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABWZmqqqqm" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVmZqacQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFZmDAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a tall lidded crate
  archive:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAA6tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADru7rQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS+7u" +
    "7u60AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL7u7u7u7utAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEvu7u7u7u7u" +
    "7rQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS+7u7u7u7u7u7t20AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL7u7u7u7u7u7u7d3d" +
    "tAAAAAAAAAAAAAAAAAAAAAAAAAAAAEvu7u7u7u7u7u7u7d3d3bQAAAAAAAAAAAAAAAAAAAAAAAAAS+7u7u7u7u7u7u7u7d3d3d20" +
    "AAAAAAAAAAAAAAAAAAAAAABL7u7u7u7u7u7u7u7u3d3d3d3dtAAAAAAAAAAAAAAAAAAAABvu7u7u7u7u7u7u7u7t3d3d3d3d3aEA" +
    "AAAAAAAAAAAAAAAAADrN7u7u7u7u7u7u7u7d3d3d3d3dyWMAAAAAAAAAAAAAAAAAABeqze7u7u7u7u7u7u3d3d3d3d3ZZkEAAAAA" +
    "AAAAAAAAAAAAAAAoqs3u7u7u7u7u7t3d3d3d3dlmUQAAAAAAAAAAAAAAAAAAAAAFqqrN7u7u7u7u3d3d3d3d2WZmQAAAAAAAAAAA" +
    "AAAAAAAAAAAFqqqqze7u7u7d3d3d3d3ZZmZVQAAAAAAAAAAAAAAAAAAAAAAFqqqqqs3u3d3d3d3d3dlmZlVVQAAAAAAAAAAAAAAA" +
    "AAAAAAAFmZmqqqrN3d3d3d3d2WZ2VVVVQAAAAAAAAAAAAAAAAAAAAAAFmZmZmaqqvd3d3d3ZZnZVVVVVQAAAAAAAAAAAAAAAAAAA" +
    "AAAFmZmZmZmqqr3d3dlmdlVVVVVVQAAAAAAAAAAAAAAAAAAAAAAFmZmZmZmZqqq92WZ2VVVVVVVVQAAAAAAAAAAAAAAAAAAAAAAF" +
    "mZmZmZmZmaqqdnZVVVVVVVVVQAAAAAAAAAAAAAAAAAAAAAAFmZmZmZmZmZmqdlVVVVVVVVVVQAAAAAAAAAAAAAAAAAAAAAAAOJmZ" +
    "mZmZmZmaZVVVVVVVVVVTAAAAAAAAAAAAAAAAAAAAAAAAADiZmZmZmZmaZVVVVVVVVVMAAAAAAAAAAAAAAAAAAAAAAAAAAAA4mZmZ" +
    "mZmZZVVVVVVVUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOJmZmZmZZVVVVVVTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADiZmZmZ" +
    "ZVVVVVMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4mZmZZVVVUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOJmZZVVS" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeZZVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4YgAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a funnel, lit inside, with nothing under it
  filtered:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiIhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIy" +
    "JCExEyJTIyEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIjAhExExExFBIxQyEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIjADADExEx" +
    "ExExQRQRQiAAAAAAAAAAAAAAAAAAAAAAAAAAASMBICADETExFBMhQRMTIUIQAAAAAAAAAAAAAAAAAAAAAAAANAEgIAIDETExFBQR" +
    "QTETEyFDAAAAAAAAAAAAAAAAAAAAAAAGASAwEgIBITExFBQSIUEyFBMhYAAAAAAAAAAAAAAAAAAAAABQQDEDAgIQMTExFBQUEjEx" +
    "QSMEBAAAAAAAAAAAAAAAAAAAAAIiEwQDESAwMTExFBQUFBMiMUAxIiAAAAAAAAAAAAAAAAAAAAUSESAwMCAgMTEiIxMUExMUFBMR" +
    "IUAAAAAAAAAAAAAAAAAAABMxISEiEhISEhIiIjIyMjIyIiISEjEAAAAAAAAAAAAAAAAAABoiExMTAwICAxMTMkFBQTFBQTExInEA" +
    "AAAAAAAAAAAAAAAAAAy0IjFAQDEiAxMTMUFBMyQUFBMiNoAAAAAAAAAAAAAAAAAAAAjLYiMUEiEgIhMTMUIzEyMxQTIkeGAAAAAA" +
    "AAAAAAAAAAAAAALctyIxMhMRIDMTMUMTIkIzEyJXiSAAAAAAAAAAAAAAAAAAAAB9zIIkIkEiETMTMUQiMyQiQiaJlgAAAAAAAAAA" +
    "AAAAAAAAAAAH3cozQiMxEjEjMyQyJEIkM3iaYAAAAAAAAAAAAAAAAAAAAAAAXdy0NDIjIiEzMyMzQzNDN5q0AAAAAAAAAAAAAAAA" +
    "AAAAAAAAAa3bU0QzIiMzM0MzNEQ0ibkQAAAAAAAAAAAAAAAAAAAAAAAAAAXdxkQzMiMzNEM0RERZq1AAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAZ3IVEQzMzNERERFargQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATN3bl2ZlV2aJvLq0AAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAY3e7u7u3u7u68gQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATN7t3d3d3ty0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAY3d3d3d3dgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPd3d3d3TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "DM3d3cqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7u7upegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7u7" +
    "qoeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7q6qoeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7q6qoeQ" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6q6qodgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFm6qnMAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a hopper, seen into
  inbox:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAABIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGN6CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY3u" +
    "7tggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABje2Cit7YIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGN7YEBdnre" +
    "2CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY3tgQABdmZ63tggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACje2BAAABdmZmet3Y" +
    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKe7YEAAAABdmZmZnvd2CAAAAAAAAAAAAAAAAAAAAAAAAAAAo7tgQAAAAABdmZmZmZ63dgg" +
    "AAAAAAAAAAAAAAAAAAAAAAACju2BAAAAAAACdmZmZmZmet3YIAAAAAAAAAAAAAAAAAAAAAKN7YEAAAAAAAIyJWZmZmZmZnrd2CAA" +
    "AAAAAAAAAAAAAAAAAZ7ukQAAAAAAAjIiIiVmZmZmZmZ73dgQAAAAAAAAAAAAAAAAA6zu2BAAAAACMiIiIiIlZmZmZmat3acwAAAA" +
    "AAAAAAAAAAAAA6qs7tgQAAIyIiIiIiIiJGZmZ63dt1UwAAAAAAAAAAAAAAAAA6qqrO7YEjIiIiIiIiIiIiVnrd2nZVUwAAAAAAAA" +
    "AAAAAAAAA5mqqqzu2TIiIiIiIiIiIiOd3aZFZVUwAAAAAAAAAAAAAAAAA5mZqqlq7tgyIiIiIiIiI43dpkRFZVUwAAAAAAAAAAAA" +
    "AAAAA5mZmWIiSd3YMiIiIiIjjd2mRERFZVUwAAAAAAAAAAAAAAAAA5mZgiIiIknd2DIiIiON3aZERERGVVUwAAAAAAAAAAAAAAAA" +
    "A5mZmEIiIiJJ3dgyI43dpkREREZlVVUgAAAAAAAAAAAAAAAAAWqZmZhCIiIiSd3Yjd2mRERERmVVVVQQAAAAAAAAAAAAAAAAAAJq" +
    "mZmYQiIiIknd3aZERERGZVVVVBAAAAAAAAAAAAAAAAAAAAACaZmZmEIiIiI5pkREREZlVVVUEAAAAAAAAAAAAAAAAAAAAAAAAmmZ" +
    "mZhCIiIjVERERWVVVVQQAAAAAAAAAAAAAAAAAAAAAAAAAAJpmZmYQiIiVERFZVVVVBAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaZmZ" +
    "mEIiVEVlVVVUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWmZmZhCVWVVVVQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFpmZmZ" +
    "dVVVVBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaZmZZVVUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWmZZVQQ" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFpZBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a block of cards, its layers cut into the cheeks
  issues:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAoUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACnu7FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKe" +
    "7u7uxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp7u7u7t7sUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACnu7u7uxS" +
    "bN3FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKe7u7u7tQREmzdxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp7u7u7u7u6kERFb" +
    "3cUAAAAAAAAAAAAAAAAAAAAAAAAAAAACnu7u7u7u7u7upRERW93FAAAAAAAAAAAAAAAAAAAAAAAAAAKe7u7u7u7u7u7u7bURFM3d" +
    "xQAAAAAAAAAAAAAAAAAAAAAAAp7u7u7u7u7u7u7u3d22rd3d3bQAAAAAAAAAAAAAAAAAAAACnu7u7u7u7u7u7u7t3d3d3d3d3IUA" +
    "AAAAAAAAAAAAAAAAAAKe7u7u7u7u7u7u7u7d3d3d3d3chmUAAAAAAAAAAAAAAAAAAG3u7u7u7u7u7u7u7u3d3d3d3dyGZmUAAAAA" +
    "AAAAAAAAAAAAAHrN7u7u7u7u7u7u7t3d3d3d3IZmZmUAAAAAAAAAAAAAAAAAAGeKze7u7u7u7u7u3d3d3d3chmZmZmUAAAAAAAAA" +
    "AAAAAAAAAGiXis3u7u7u7u7d3d3d3dyGZmZmZlUAAAAAAAAAAAAAAAAAAGmIl4rN7u7u3d3d3d3d3IZmZmZmVmUAAAAAAAAAAAAA" +
    "AAAAAHh5iJeKzd3d3d3d3d3chmZmZmZWZWUAAAAAAAAAAAAAAAAAAGeYeYiXis3d3d3d3dyGZmZmZmZmZlUAAAAAAAAAAAAAAAAA" +
    "AGmHmHmHl4rN3d3d3IZmZmZmZmZmZWQAAAAAAAAAAAAAAAAAAHh5h5h5d5eKvd3chmZmZmZmZmZlZCAAAAAAAAAAAAAAAAAAAGeI" +
    "eYeYeXeXiryGZmZmZmZmZmVlIAAAAAAAAAAAAAAAAAAAADmXiHmHmHl3l4hmZmZmZmZmZWUgAAAAAAAAAAAAAAAAAAAAAABJl4h5" +
    "h5h5d5dmZmZmZmZlZSAAAAAAAAAAAAAAAAAAAAAAAAAASZeIeYeXeXhmZmZmZmVlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmXiHiH" +
    "l3hmZmZmZWUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABJl4h4h5hmZmZlZSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASJeIeIhm" +
    "ZmVlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiXiHdmZWUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIl4llZSAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASJdkIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYgAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // two pieces on a board
  people:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEhAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABay5dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABvs27qXAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK7u3LqoUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA93u3LqYYgAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAB83d3LqncwAAAAAAAAAAAAAAIQAAAAAAAAAAAAAAAAAAAAAACbvMzLmXdAAAAAAAAAAAAAGM2o" +
    "QAAAAAAAAAAAAAAAAAAAAACau7u6qHhQAAAAAAAAAAAC3dy7pgAAAAAAAAAAAAAAAAAAAAq5qqqpmHapAAAAAAAAAAAL7ty6qCAA" +
    "AAAAAAAAAAAAAAAAAF7ImYmIiGXeMAAAAAAAAAAt3cy6l1AAAAAAAAAAAAAAAAAAAH7qiId3d2nuUAAAAAAAAABMzMu5iGAAAAAA" +
    "AAAAAAAAAAAAAH3tl2h2Zo7sUAAAAAAAAAB6u7qphnIAAAAAAAAAAAAAAAAAAHre6nVUau7GYAAAAAAAAAfaqpmZh5wQAAAAAAAA" +
    "AAAAAAAAKemr3e3d7ch16RAAAAAAAArbmIh4ds1AAAAAAAAAAAAAAAAE3emru7u6qZd17dMAAAAAAArdl3hmatxAAAAAAAAAAAAA" +
    "AAAt3emru7u6qZd17d0QAAAAAArN2nZnzbhQAAAAAAAAAAAAAACd3dmru7u6qZd17d1wAAAABcy6vMzMqGfZEAAAAAAAAAAAAAC9" +
    "3dmru7u6qZd17d2gAAAAfdyqu7qpmGfcsQAAAAAAAAAAAAC93dmru7u5qZd23d2gAAAC3dyqu7qpiGfcxwAAAAAAAAAAAACt3dyq" +
    "u7u5qZd73d1wAAAF3duqu7qpiGfcygAAAAAAAAAAAACK3d3Lu7u5qZjN3dhQAAAE3dyqu7qph2jMywAAAAAAAAAAAAB4rd3d3MzL" +
    "vN3d23RQAAAEzd3Kq7qZh4zMyAAAAAAAAAAAAAA5mrzd3d3d3d3bhmYgAAADm93dy7qqq8zLZQAAAAAAAAAAAAAFmqq7zMzMy6p4" +
    "ZnMAAAAAmazN3d3MzMuVVAAAAAAAAAAAAAAAOaq6urqqmYl4ZyAAAAAAOZqqu8y7qnd1UAAAAAAAAAAAAAAAAEi6urqqmYmGMAAA" +
    "AAAAAWqqqqmpiXdiAAAAAAAAAAAAAAAAAAATZ4iIdkMAAAAAAAAAAAFXqqmpl0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAASIhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // three cubes, set apart
  projects:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5owAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnu7qMA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOu7u7u6jAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA67u7u7u7uowAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADru7u7u7u7u7aMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc3u7u7u7u7u7dkQAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAqrN7u7u7u7u2WYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqqqze7u7u7ZZVYQAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAqqqqr3u7tllVVYQAAAAAAAAAAAAAAAAAAAAAAAAAAAABTAAAqqqqqq92WVVVVYQAAJQAAAAAAAA" +
    "AAAAAAAAAAAAAAAGzukgAqqqqqqqdVVVVVYQAp3cUAAAAAAAAAAAAAAAAAAAAAbO7u7pIZqqqqqqZVVVVVYSnd3d3FAAAAAAAAAA" +
    "AAAAAAAAFs3d3u7u6TSaqqqqZVVVVjOd3d3d3dxgAAAAAAAAAAAAAAAWzd3d3d3e7uk0iqqqZVVWM53d3d3d3d3cYAAAAAAAAAAA" +
    "AAPN3d3d3d3d3d3nA4qaZVYwjd3d3d3d3d3dyyAAAAAAAAAAAASr3d3d3d3d3dt2AAOKZjAAms3d3d3d3d3clTAAAAAAAAAAAASZ" +
    "q93d3d3d23VWAAADMAAAmZrN3d3d3dyVVTAAAAAAAAAAAASZmavd3d3bdVVWAAAAAAAAmZmazd3d3IVVVTAAAAAAAAAAAASZmZmb" +
    "3dt1VVVWAAAAAAAAmZmZms3chVVVVTAAAAAAAAAAAASZmZmZm3VVVVVWAAAAAAAAmZmZmZqVVVVVVTAAAAAAAAAAAASZmZmZmlVV" +
    "VVVWAAAAAAAAmZmZmZl1VVVVVTAAAAAAAAAAAABImZmZmlVVVVZBAAAAAAAAFpmZmZl1VVVVUwAAAAAAAAAAAAAASJmZmVVVVkEA" +
    "AAAAAAAAABaZmZl1VVVTAAAAAAAAAAAAAAAAAEiZmVVWQQAAAAAAAAAAAAAWmZl1VVMAAAAAAAAAAAAAAAAAAAA4mVZBAAAAAAAA" +
    "AAAAAAAAFpl1UwAAAAAAAAAAAAAAAAAAAAAAOEEAAAAAAAAAAAAAAAAAABZzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a house — somewhere the work lives
  space:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL5xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC//+cQAAEh" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv////nESABIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL//////6BAAASEA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC////////+cQAAEhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv//////////nEAABIQAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAL////////////6BAAASEAAAAAAAAAAAAAAAAAAAAAAAAAAAC//////////////+gQAAEhAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAv////////////////nEAABIQAAAAAAAAAAAAAAAAAAAAAAAL//////////////////5xAAASEAAAAA" +
    "AAAAAAAAAAAAAAAAAZ///////////////////+cQAAEhAAAAAAAAAAAAAAAAAAAAAAKf///////////////////nMzM0UzMQAAAA" +
    "AAAAAAAAAAAAAAAq3//////////////////pZmZmZmIAAAAAAAAAAAAAAAAAAAAqqt////////////////6WZmZmdAAAAAAAAAAA" +
    "AAAAAAAAAAAqqqrf/////////////+lmZmZ2UgAAAAAAAAAAAAAAAAAAAAApqqqq3///////////7pZmZnZVUgAAAAAAAAAAAAAA" +
    "AAAAAAApmZmqqt/////////+6WZniFVVUgAAAAAAAAAAAAAAAAAAAAApmZmaqZrf//////7ulmd3NFVVUgAAAAAAAAAAAAAAAAAA" +
    "AAApmZmVSKma3///7u7pZ3cyJFVVUgAAAAAAAAAAAAAAAAAAAAAqmZmVIkiZmt7u7u6XdzIiNVVVUgAAAAAAAAAAAAAAAAAAAAAC" +
    "epmVIiJImZrO7ul2VSI1ZVVVUgAAAAAAAAAAAAAAAAAAAAAAAnqVIiIkmZmazqZVVTVlVVVVUQAAAAAAAAAAAAAAAAAAAAAAAAJ1" +
    "IiIkmZmZmVVVVmVVVVVSAAAAAAAAAAAAAAAAAAAAAAAAAAACMiIkmZmZmVVVVVVVVVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjIk" +
    "mZmZmVVVVVVVUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI0mZmZmVVVVVVSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACeZmZ" +
    "mVVVVVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnmZmFVVUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ5mFVS" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACeVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // a ream with a pen across it
  specs:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS+kgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABL7u7q" +
    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEvu7u7u6SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS+7u7u7u7ukg" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77u7u7u7u7u7pIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvu7u7u7u7u7u7u2SAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAOu7u7u7u7u7u7u7u7dkgAAAAAAAAAAAAAAAAAAAAAAAAAAA67u7u7u7u7u7u7u7u7d3ZIAAA" +
    "AAAAAAAAAAAAAAAAAAAAADru7u7u7u7u7u7u7u7u3d3d2SAAAAAAAAAAAAAAAAAAAAAABd7u7u7u7u7u7u7u7u7t3d3d3dkgAAAA" +
    "AAAAAAAAAAAAAAAABJve7u7u7u7u7u7u7u7d3d3d3d3ZIAAAAAAAAAAAAAAAAAAABZib3u7u7u7u7u7u7u3d3d3d3d3d2SAAAAAA" +
    "AAAAAAAAAAAABYiYm97u7u7u7u7u7u3d3d3d3d3d3dggAAAAAAAAAAAAAAAABImImJve7u7u7u7u3e3d3d3d3d3d3chAAAAAAAAA" +
    "AAAAAAAABIiJiJib3u7u7u7e3d3d3d3d3d3dyGZAAAAAAAAAAAAAAAAABJeIeYiYm97u3d3e3d3d3d3d3d3IZmZAAAAAAAAAAAAA" +
    "AAAABXiXiHmImJvd3d3e3d3d3d3d3chmZmZAAAAAAAAAAAAAAAAAAXp4l4h5iJib3d3d3d3d3d3dyGZmZlVAAAAAAAAAAAAAAAAA" +
    "AAJ6d5eIeYiYms3d3d3d3d3IZmZmVWZAAAAAAAAAAAAAAAAAAAACeneXiHmImJrN3d3d3chmZmZWZmVAAAAAAAAAAAAAAAAAAAAA" +
    "Anp3l4h5iJiazd3dyGZmZlZmZmYwAAAAAAAAAAAAAAAAAAAAAAJ6d5eIeYeYms3IZmZmZWZmZlIAAAAAAAAAAAAAAAAAAAAAAAAC" +
    "eXeXiHl3mIpmZmZlZmZmUgAAAAAAAAAAAAAAAAAAAAAAAAAAAnl3l4h5d5lmZmVmZmZSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ5" +
    "d5eIeXhmZWZmZlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACeXeXiHllZmZmUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnl3" +
    "l4lmZmZSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ5d5hmZlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaXhm" +
    "UgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmlSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  // one link, parted
  unavailable:
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACNWd2VCEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIvu7u" +
    "7u7u7ZYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAo3u7u7u7u7u7u7qUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnu7u7u7u7u7u" +
    "7u7u7EAAAAAAAAAAAAAAAAAAAAAAAAAAAABd7u7u7u7u3d7u7u7u7toQAAAAAAAAAAAAAAAAAAAAAAAAAAXu7u7u7bmIiIir3u7u" +
    "7u2xAAAAAAAAAAAAAAAAAAAAAAAAAAAli+7ulneIeIiYid7u7u7ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANoV0IAAAATaJzu7u3d" +
    "IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAAAAAYru7u3dYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAju7u7tgAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAbu7t3dgAAAAAAAAAAAAAAAAAAAAAAAAAAAJYvrEAAAAAAAAG3u7t3dQAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAWt7u7u1yAAAAAAS+7u7d3XIAAAAAAAAAAAAAAAAAAAAAAAAAfe7u7u7uyXZnit7u7u3d12AAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAac3u7u7u7u7u7u7u7u7dt0AAAAAAAAAAAAAAAAAAAAAAAAAACKrN7u7u7u7u7u3t7e3d3dyDAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAFm6ze7u7u7u7t7e3d3d3d3dxhAAAAAAAAAAAAAAAAAAAAAAAAFZurvN7u7u7u3e3d3d3d3d3cUAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAN6vN7e7u3u7bu7vN3d3d3d2QAAAAAAAAAAAAAAAAAAAAAAAAAATd3d3t3Zd2eIiIm93d3d2kAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAzd3d3dtmdlREVoiIzchTAAAAAAAAAAAAAAAAAAAAAAAAAAAE3d3d3ZdTAAAAAAJYkQAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAH3d3d3ZQAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI3d3d3WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH" +
    "3d3d3ZAAAAAAAAAAJCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEzd3d3dogAAAAAAAFzdyWMQAAAAAAAAAAAAAAAAAAAAAAAAACnd3d" +
    "3d3ZQQAAACa93d3czHAAAAAAAAAAAAAAAAAAAAAAAAAAec3d3d3d3cuqvd3d3dzMyEAAAAAAAAAAAAAAAAAAAAAAAAAAGJvd3d3d" +
    "3d3d3d3d3czKZTAAAAAAAAAAAAAAAAAAAAAAAAAAAXqbzd3d3d3d3d3NzMqFYwAAAAAAAAAAAAAAAAAAAAAAAAAAAASKqszd3d3d" +
    "3dzcuYZ0EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiqqru7y7uqmXhoQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVeqqqqZmZiW" +
    "UwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI0VVQzEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
};

const decoded = new Map<EmptyStateArt, Uint8Array>();

/** One nibble per cell, so a field is half the bytes its cell count suggests. */
function field(art: EmptyStateArt): Uint8Array {
  const hit = decoded.get(art);
  if (hit) return hit;
  const bin = atob(FIELDS[art]);
  const out = new Uint8Array(COLS * ROWS);
  for (let i = 0; i < bin.length; i += 1) {
    const byte = bin.charCodeAt(i);
    out[i * 2] = byte >> 4;
    out[i * 2 + 1] = byte & 15;
  }
  decoded.set(art, out);
  return out;
}

const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
const smoothstep = (a: number, b: number, x: number) => {
  const t = clamp01((x - a) / (b - a));
  return t * t * (3 - 2 * t);
};
const mix = (a: number[], b: number[], k: number) => [
  a[0]! + (b[0]! - a[0]!) * k,
  a[1]! + (b[1]! - a[1]!) * k,
  a[2]! + (b[2]! - a[2]!) * k,
];

type Box = { x: number; y: number; w: number; h: number };

const boxes = new Map<EmptyStateArt, Box>();

/**
 * The drawing's own extent, in cells, with the lattice's blank left out.
 *
 * Each field is centred in the 72×52 lattice, so its padding is symmetric —
 * and different for every drawing, because the objects are different sizes. A
 * plate drawn at the full lattice therefore sets its own leading edge and its
 * own gap to the title: 22.5px of blank down the left of `projects` against
 * 37.5px for `unavailable`, and 32.5px under `projects` against 22.5px under
 * `filtered`. Ten states, ten spacings, none of them declared anywhere.
 *
 * Cropping to the ink hands that spacing back to the layout, where it is one
 * margin for the whole set. It is not a resize: the pitch, the cell and the
 * dot radius are untouched, and the same cells are drawn at the same size.
 */
function inkBox(art: EmptyStateArt): Box {
  const hit = boxes.get(art);
  if (hit) return hit;
  const cells = field(art);
  let x0 = COLS;
  let x1 = -1;
  let y0 = ROWS;
  let y1 = -1;
  for (let j = 0; j < ROWS; j += 1) {
    for (let i = 0; i < COLS; i += 1) {
      if (cells[j * COLS + i] === 0) continue;
      if (i < x0) x0 = i;
      if (i > x1) x1 = i;
      if (j < y0) y0 = j;
      if (j > y1) y1 = j;
    }
  }
  // A blank field cannot happen, but a zero box would size a canvas at nothing
  // and paint nothing forever, so it degrades to the whole lattice.
  const box =
    x1 < 0
      ? { x: 0, y: 0, w: COLS, h: ROWS }
      : { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
  boxes.set(art, box);
  return box;
}

/** One plate's drawn size in CSS px. The pitch is fixed, so this is the
 *  drawing's own measure rather than a scale it was given. */
export function artSize(art: EmptyStateArt): { width: number; height: number } {
  const box = inkBox(art);
  return { width: box.w * CELL, height: box.h * CELL };
}

/**
 * The browser's own colour parser, borrowed one pixel at a time.
 *
 * Our tokens are `light-dark()` over `oklch()`, and both survive into the
 * computed value: `getComputedStyle` picks the light or the dark arm but keeps
 * the colour space. So the `rgb(…)` this file used to match never arrived, the
 * ink fell back to a hardcoded pink and the ground to an assumed black — which
 * is most of why the plates looked like they came from another app.
 *
 * Rather than carry an OKLCH converter that would have to agree with the
 * browser's own gamut mapping, hand the string back to the browser: fill one
 * pixel, read it. That parses every notation the page can actually paint with,
 * which is exactly the set that matters.
 */
let scratch: CanvasRenderingContext2D | null | undefined;

/** A colour no palette holds. `fillStyle` keeps its previous value when handed
 *  something it cannot parse, so this is how "unparseable" is told from black. */
const UNPARSED = "#123456";

/** What a probe inherits when the token it asked for does not exist. */
const ABSENT = "rgb(1, 2, 3)";

function toRgb(value: string): number[] | null {
  const literal = /rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)/.exec(value);
  if (literal) return [Number(literal[1]), Number(literal[2]), Number(literal[3])];
  if (!value) return null;
  if (scratch === undefined) {
    const canvas = document.createElement("canvas");
    canvas.width = 1;
    canvas.height = 1;
    scratch = canvas.getContext("2d", { willReadFrequently: true });
  }
  const ctx = scratch;
  if (!ctx) return null; // jsdom, and any surface without a 2d context
  ctx.fillStyle = UNPARSED;
  ctx.fillStyle = value;
  if (ctx.fillStyle === UNPARSED) return null;
  ctx.clearRect(0, 0, 1, 1);
  ctx.fillRect(0, 0, 1, 1);
  try {
    const pixel = ctx.getImageData(0, 0, 1, 1).data;
    return pixel[3] === 0 ? null : [pixel[0]!, pixel[1]!, pixel[2]!];
  } catch {
    return null;
  }
}

/**
 * Palette tokens, resolved the way the page resolves them: on a real element,
 * inside the tree the plate sits in, so `light-dark()` picks the same arm the
 * surface around it did. Reading the custom property directly would hand back
 * the unresolved `light-dark(…, …)` text instead.
 *
 * The probe sits inside a wrapper holding a colour no palette holds, because a
 * token that does not exist is invalid at computed-value time and leaves the
 * probe at its inherited colour — which is how an absent token is told from a
 * resolved one rather than silently becoming the ink.
 */
function tokenColors(el: HTMLElement, names: string[]): (number[] | null)[] {
  const host = el.parentElement ?? document.body;
  const wrapper = document.createElement("span");
  wrapper.setAttribute("aria-hidden", "true");
  wrapper.style.cssText = `position:absolute;width:0;height:0;overflow:hidden;color:${ABSENT}`;
  const probe = document.createElement("span");
  wrapper.appendChild(probe);
  host.appendChild(wrapper);
  const out = names.map((name) => {
    probe.style.color = `var(${name})`;
    const value = getComputedStyle(probe).color;
    return value === ABSENT ? null : toRgb(value);
  });
  wrapper.remove();
  return out;
}

/** The nearest ancestor that actually paints. A canvas over a transparent
 *  parent has no idea which way its highlights should burn. */
function groundOf(el: HTMLElement): number[] {
  let node: HTMLElement | null = el;
  while (node) {
    const value = getComputedStyle(node).backgroundColor;
    if (value && !/rgba\(0,\s*0,\s*0,\s*0\)|transparent/.test(value)) {
      const parsed = toRgb(value);
      if (parsed) return parsed;
    }
    node = node.parentElement;
  }
  return [0, 0, 0];
}

const luma = (c: number[]) => 0.2126 * c[0]! + 0.7152 * c[1]! + 0.0722 * c[2]!;

type Stops = { quiet: number[]; ink: number[]; lit: number[]; core: number[] };

/*
 * The ink runs a spectrum rather than one hue lightened and darkened, because
 * a single-hue ramp reads as a flat wash at this dot size — the colour travel
 * is what gives a halftone its depth.
 *
 * Where it travels *to* is the app's own ladder, not the landing hero's. The
 * hero runs a lilac tail, ochre as the tone climbs and ivory at the cores,
 * which is the correct ramp for gold on black and a foreign palette anywhere
 * in a tracker whose one chromatic voice is `--color-accent`. The stops here
 * are `--color-mute` in the thin tail, the element's own colour through the
 * body, the accent as the tone climbs, and `--color-bright` at the cores.
 *
 * Which way the page goes is no longer computed. `--color-bright` is
 * `light-dark(near-black, white)` and `--color-mute` sits toward the ground in
 * both themes, so the plate inverts on paper because the tokens do.
 */
function ramp(stops: Stops) {
  const table: string[] = [];
  for (let i = 0; i < 16; i += 1) {
    const v = i / 15;
    // 0.58, and never the whole way. Started earlier the accent catches the
    // midrange and the plate turns blue — the same failure the hero's ochre
    // has at 0.42, which is a coloured wash rather than a lit solid.
    const climb = smoothstep(0.58, 1, v) * 0.75;
    const knee = 0.44;
    const base =
      climb < knee
        ? mix(stops.quiet, stops.ink, climb / knee)
        : mix(stops.ink, stops.lit, (climb - knee) / (1 - knee));
    const burn = smoothstep(0.74, 1, v) * (0.3 + 0.55 * climb);
    const c = mix(base, stops.core, burn);
    table.push(`rgb(${Math.round(c[0]!)},${Math.round(c[1]!)},${Math.round(c[2]!)})`);
  }
  return table;
}

function paint(canvas: HTMLCanvasElement, art: EmptyStateArt) {
  const ctx = canvas.getContext("2d");
  if (!ctx) return; // jsdom, and any surface without a 2d context
  const box = inkBox(art);
  const width = box.w * CELL;
  const height = box.h * CELL;
  const dpr = Math.min(2, window.devicePixelRatio || 1);
  canvas.width = Math.round(width * dpr);
  canvas.height = Math.round(height * dpr);
  const ink = toRgb(getComputedStyle(canvas).color) ?? [128, 128, 128];
  const ground = groundOf(canvas);
  const [mute, accent, bright] = tokenColors(canvas, [
    "--color-mute",
    "--color-accent",
    "--color-bright",
  ]);
  // The fallbacks are for a page that is not this app's — the plate still has
  // to hold shape, so it borrows the direction of travel from the ground.
  const up = luma(ink) > luma(ground);
  const table = ramp({
    quiet: mix(ink, mute ?? mix(ink, ground, 0.5), 0.6),
    ink,
    lit: accent ?? mix(ink, up ? [255, 255, 255] : [0, 0, 0], 0.25),
    core: bright ?? (up ? [255, 255, 255] : [20, 18, 24]),
  });
  const cells = field(art);
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, width, height);
  for (let j = 0; j < box.h; j += 1) {
    for (let i = 0; i < box.w; i += 1) {
      const q = cells[(box.y + j) * COLS + (box.x + i)]!;
      if (q === 0) continue;
      const v = q / 15;
      // 0.62, not the engine's 0.78. That curve suits a field meant to be
      // mostly faint against a dark ground; this plate is a small object in a
      // pane and has to hold at muted-text weight, so the midtones print harder.
      ctx.globalAlpha = Math.pow(v, 0.62);
      ctx.fillStyle = table[q]!;
      ctx.beginPath();
      ctx.arc((i + 0.5) * CELL, (j + 0.5) * CELL, MAX_R * v, 0, Math.PI * 2);
      ctx.fill();
    }
  }
  ctx.globalAlpha = 1;
}

/**
 * The drawing alone: no spacing and no colour of its own.
 *
 * Its box is the drawing's own extent, so the margin under it is the gap you
 * see under every plate and the leading edge is the same in all ten states.
 *
 * It repaints when the theme moves, because the ink is resolved from the page
 * rather than baked in. `data-theme` on `<html>` covers an explicit choice and
 * the media query covers "system", which are two different signals for the same
 * fact.
 */
export function EmptyArt({ art, className }: { art: EmptyStateArt; className?: string }) {
  const ref = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    let frame = 0;
    const repaint = () => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => paint(canvas, art));
    };
    repaint();
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    media.addEventListener("change", repaint);
    const observer = new MutationObserver(repaint);
    observer.observe(document.documentElement, { attributeFilter: ["data-theme"] });
    return () => {
      cancelAnimationFrame(frame);
      media.removeEventListener("change", repaint);
      observer.disconnect();
    };
  }, [art]);

  const { width, height } = artSize(art);
  return (
    <canvas
      aria-hidden
      className={className}
      data-empty-state-art={art}
      ref={ref}
      role="presentation"
      style={{ width: `${width}px`, height: `${height}px` }}
    />
  );
}
