/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminContentListRouteImport } from './routes/_admin/content-list'
import { Route as AdminSplatRouteImport } from './routes/_admin/$'
import { Route as AdminScreenListIndexRouteImport } from './routes/_admin/screen-list/index'
import { Route as AdminChannelListIndexRouteImport } from './routes/_admin/channel-list/index'
import { Route as AdminBroadcastListIndexRouteImport } from './routes/_admin/broadcast-list/index'
import { Route as AdminBroadcastHubIndexRouteImport } from './routes/_admin/broadcast-hub/index'
import { Route as AdminScreenListIdRouteImport } from './routes/_admin/screen-list/$id'
import { Route as AdminBroadcastListBroadcastIdRouteImport } from './routes/_admin/broadcast-list/broadcast.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentListRoute = AdminContentListRouteImport.update({
  id: '/content-list',
  path: '/content-list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScreenListIndexRoute = AdminScreenListIndexRouteImport.update({
  id: '/screen-list/',
  path: '/screen-list/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChannelListIndexRoute = AdminChannelListIndexRouteImport.update({
  id: '/channel-list/',
  path: '/channel-list/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastListIndexRoute = AdminBroadcastListIndexRouteImport.update({
  id: '/broadcast-list/',
  path: '/broadcast-list/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastHubIndexRoute = AdminBroadcastHubIndexRouteImport.update({
  id: '/broadcast-hub/',
  path: '/broadcast-hub/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScreenListIdRoute = AdminScreenListIdRouteImport.update({
  id: '/screen-list/$id',
  path: '/screen-list/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastListBroadcastIdRoute =
  AdminBroadcastListBroadcastIdRouteImport.update({
    id: '/broadcast-list/broadcast/$id',
    path: '/broadcast-list/broadcast/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/$': typeof AdminSplatRoute
  '/content-list': typeof AdminContentListRoute
  '/screen-list/$id': typeof AdminScreenListIdRoute
  '/broadcast-hub/': typeof AdminBroadcastHubIndexRoute
  '/broadcast-list/': typeof AdminBroadcastListIndexRoute
  '/channel-list/': typeof AdminChannelListIndexRoute
  '/screen-list/': typeof AdminScreenListIndexRoute
  '/broadcast-list/broadcast/$id': typeof AdminBroadcastListBroadcastIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof AdminSplatRoute
  '/content-list': typeof AdminContentListRoute
  '/': typeof AdminIndexRoute
  '/screen-list/$id': typeof AdminScreenListIdRoute
  '/broadcast-hub': typeof AdminBroadcastHubIndexRoute
  '/broadcast-list': typeof AdminBroadcastListIndexRoute
  '/channel-list': typeof AdminChannelListIndexRoute
  '/screen-list': typeof AdminScreenListIndexRoute
  '/broadcast-list/broadcast/$id': typeof AdminBroadcastListBroadcastIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/$': typeof AdminSplatRoute
  '/_admin/content-list': typeof AdminContentListRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/screen-list/$id': typeof AdminScreenListIdRoute
  '/_admin/broadcast-hub/': typeof AdminBroadcastHubIndexRoute
  '/_admin/broadcast-list/': typeof AdminBroadcastListIndexRoute
  '/_admin/channel-list/': typeof AdminChannelListIndexRoute
  '/_admin/screen-list/': typeof AdminScreenListIndexRoute
  '/_admin/broadcast-list/broadcast/$id': typeof AdminBroadcastListBroadcastIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/content-list'
    | '/screen-list/$id'
    | '/broadcast-hub/'
    | '/broadcast-list/'
    | '/channel-list/'
    | '/screen-list/'
    | '/broadcast-list/broadcast/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/content-list'
    | '/'
    | '/screen-list/$id'
    | '/broadcast-hub'
    | '/broadcast-list'
    | '/channel-list'
    | '/screen-list'
    | '/broadcast-list/broadcast/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/$'
    | '/_admin/content-list'
    | '/_admin/'
    | '/_admin/screen-list/$id'
    | '/_admin/broadcast-hub/'
    | '/_admin/broadcast-list/'
    | '/_admin/channel-list/'
    | '/_admin/screen-list/'
    | '/_admin/broadcast-list/broadcast/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/content-list': {
      id: '/_admin/content-list'
      path: '/content-list'
      fullPath: '/content-list'
      preLoaderRoute: typeof AdminContentListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/$': {
      id: '/_admin/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/screen-list/': {
      id: '/_admin/screen-list/'
      path: '/screen-list'
      fullPath: '/screen-list/'
      preLoaderRoute: typeof AdminScreenListIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/channel-list/': {
      id: '/_admin/channel-list/'
      path: '/channel-list'
      fullPath: '/channel-list/'
      preLoaderRoute: typeof AdminChannelListIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/broadcast-list/': {
      id: '/_admin/broadcast-list/'
      path: '/broadcast-list'
      fullPath: '/broadcast-list/'
      preLoaderRoute: typeof AdminBroadcastListIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/broadcast-hub/': {
      id: '/_admin/broadcast-hub/'
      path: '/broadcast-hub'
      fullPath: '/broadcast-hub/'
      preLoaderRoute: typeof AdminBroadcastHubIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/screen-list/$id': {
      id: '/_admin/screen-list/$id'
      path: '/screen-list/$id'
      fullPath: '/screen-list/$id'
      preLoaderRoute: typeof AdminScreenListIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/broadcast-list/broadcast/$id': {
      id: '/_admin/broadcast-list/broadcast/$id'
      path: '/broadcast-list/broadcast/$id'
      fullPath: '/broadcast-list/broadcast/$id'
      preLoaderRoute: typeof AdminBroadcastListBroadcastIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminContentListRoute: typeof AdminContentListRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminScreenListIdRoute: typeof AdminScreenListIdRoute
  AdminBroadcastHubIndexRoute: typeof AdminBroadcastHubIndexRoute
  AdminBroadcastListIndexRoute: typeof AdminBroadcastListIndexRoute
  AdminChannelListIndexRoute: typeof AdminChannelListIndexRoute
  AdminScreenListIndexRoute: typeof AdminScreenListIndexRoute
  AdminBroadcastListBroadcastIdRoute: typeof AdminBroadcastListBroadcastIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminContentListRoute: AdminContentListRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminScreenListIdRoute: AdminScreenListIdRoute,
  AdminBroadcastHubIndexRoute: AdminBroadcastHubIndexRoute,
  AdminBroadcastListIndexRoute: AdminBroadcastListIndexRoute,
  AdminChannelListIndexRoute: AdminChannelListIndexRoute,
  AdminScreenListIndexRoute: AdminScreenListIndexRoute,
  AdminBroadcastListBroadcastIdRoute: AdminBroadcastListBroadcastIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
