//! The bridge, and the only thing that crosses it.
//!
//! Revision 7 of the Plan puts a Dart interface over this Rust core, which
//! means there is a boundary again — the one revisions 5 and 6 removed on
//! purpose. Everything in this module exists to make that boundary safe by
//! construction rather than by care.
//!
//! ## What crosses, and in which direction
//!
//! Exactly two things. A [`ClientView`] goes out — a whole, immutable
//! projection of client state, built here and never assembled on the other
//! side. An [`ActionRequest`] comes back — a thing a person asked for. Nothing
//! else has a route across.
//!
//! ## Facts go out; words do not
//!
//! The view carries *what is true*, not what to say about it. A placement is
//! [`Placement::Vacant`], never "not running"; a row that cannot be opened
//! carries [`Unopenable::Undeclared`], never the sentence explaining it. That
//! split is what keeps the fifth lockdown rule honest: Dart owns wording and
//! layout, and cannot own a fact because it is never sent one it could have
//! derived differently.
//!
//! It is also why absence is modelled rather than encoded. `last_opened` is an
//! `Option<u64>` and not a `u64` where zero means never, because "never opened"
//! and "opened at the epoch" are different facts and a sentinel makes them the
//! same one. Unmeasured is absent, never zero — the rule survives the crossing
//! only if the wire format can say it.
//!
//! ## One model, still
//!
//! [`App`] stays the only model of client state. This module holds it, drains
//! the runtime into it, and projects it. Dart receives the projection whole and
//! keeps nothing of its own but drafts.

use std::path::{Path, PathBuf};
use std::sync::mpsc::{channel, Sender};
use std::sync::{Mutex, OnceLock};

use flutter_rust_bridge::frb;

// Generated by the bridge codegen and checked in beside this file. Named
// through the generated module rather than the crate root because that is
// where the codegen puts the concrete codec.
use crate::frb_generated::StreamSink;

use crate::client::library::{Opens, Placement as CorePlacement};
use crate::model::{App, StaleReason};
use crate::runtime::{Action, Runtime};
use crate::Config;

/// Everything a surface can draw, as of one moment.
///
/// Sent whole. There is no partial update and no patch protocol, because a
/// patch protocol is a second model in disguise: the receiver has to hold the
/// previous state and apply changes to it, and the moment it can do that it can
/// disagree with the sender.
#[derive(Debug, Clone, PartialEq)]
pub struct ClientView {
    /// Nothing has been read yet. Distinct from "read, and there is nothing".
    pub loading: bool,
    /// Why what is on screen may not be current. `None` is fresh.
    pub stale: Option<Staleness>,
    /// `None` until the library has been read once — which is not the same as
    /// a device that serves nothing.
    pub library: Option<Vec<LibraryRow>>,
    pub host: Option<HostFacts>,
    pub heads: Vec<HeadRow>,
    pub devices: Vec<DeviceRow>,
    pub storage: Vec<StorageRow>,
    /// This identity's Orbit registry, newest-opened first.
    pub orbits: Vec<OrbitRow>,
    /// The Space being administered, when one has been chosen. Choosing is an
    /// act — it costs a read — so this is absent until somebody chooses.
    pub space: Option<SpaceRow>,
    /// `None` until the book has been read once. Empty cards is a book
    /// that answered and holds nothing, not an unread book.
    pub book: Option<BookFacts>,
    pub notices: Vec<NoticeRow>,
    pub failures: Vec<FailureRow>,
    /// The keys of actions asked for and not yet answered. A control whose key
    /// is in here is disabled — on the frame the click happened, not on
    /// whichever later frame the answer arrives.
    pub in_flight: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Staleness {
    /// The first read has not landed.
    NeverLoaded,
    /// The stream said so, and said why.
    Signalled(String),
}

/// One row of the Library.
#[derive(Debug, Clone, PartialEq)]
pub struct LibraryRow {
    /// Stable across re-reads: the Orbit and the World in it. A selection
    /// keyed by index would silently follow whatever moved into that position.
    pub key: String,
    pub orbit: String,
    pub space: String,
    /// Empty when the row is the Space itself rather than a World in it.
    pub world_mount: String,
    /// `None` means nothing authoritative names it. Drawn as unnamed rather
    /// than as an id dressed up as a name.
    pub display_name: Option<String>,
    pub placement: PlacementView,
    /// Where `Open` lands. `None` with [`Self::unopenable`] set is a row that
    /// cannot be opened at all.
    pub opens_at: Option<String>,
    pub unopenable: Option<Unopenable>,
    /// Wall-clock seconds. `None` is *never opened*, which a zero would
    /// silently turn into 1 January 1970.
    pub last_opened: Option<u64>,
    /// Where the Orbit's store lives, when the registry could be read.
    pub store: Option<String>,
    /// Reviewed implementation version for the hosted World.
    pub version: Option<u32>,
    /// The running Orbit's sync gate, kept as transport facts for Dart wording.
    pub sync_state: Option<String>,
    pub sync_detail: Option<String>,
    /// What the World says about how it should be drawn. Empty for a Space row
    /// and for a World this build does not host — in both cases because nothing
    /// has said anything, which is a fact rather than a blank.
    pub tagline: Option<String>,
    /// Packed `0xRRGGBB`. A seed the interface derives a plate from locally;
    /// there is no asset here and nothing to fetch.
    pub accent: Option<u32>,
    /// Named places inside the World, already resolved for this Orbit.
    pub routes: Vec<RouteRow>,
}

/// One named place inside a World.
#[derive(Debug, Clone, PartialEq)]
pub struct RouteRow {
    pub label: String,
    /// Absolute, and resolved: `Open` takes it as it stands.
    pub path: String,
}

/// Whether an Orbit is currently up. Three states, because "not running" and
/// "could not be asked" are different facts and only one is worth acting on.
///
/// Named apart from [`crate::client::library::Placement`] on purpose: the
/// codegen flattens type names across the crate and picks between collisions at
/// random, so a DTO that shared a name with a core type would be a coin toss
/// nobody could see land.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlacementView {
    Placed,
    Vacant,
    Unknown,
}

/// Why a row cannot be opened. Two facts, not one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Unopenable {
    /// This build hosts no head for that World.
    Unhosted,
    /// The World is hosted here and has not declared where to open it.
    Undeclared,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HostFacts {
    pub version: String,
    pub identity_home: String,
    pub spaces_root: String,
    pub orbit_count: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HeadRow {
    pub id: String,
    /// Browser or MCP.
    pub kind: String,
    /// The Orbit it is bound to. `None` is a browser head serving every Orbit
    /// its identity has.
    pub orbit: Option<String>,
    /// The address, *without* the run credential its URL carries. A front page
    /// has no use for a credential — `Open` mints a single-use ticket of its
    /// own, which is what that ceremony is for.
    pub origin: Option<String>,
    pub owned: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct DeviceRow {
    pub id: String,
    pub label: String,
    pub state: String,
    pub owned: bool,
    /// Whether observation of this device is degraded, and what went wrong.
    /// A sampling failure preserves the last good reading and says so; it is
    /// never drawn as "nothing there".
    pub degraded: Option<String>,
    pub home: String,
    /// `None` for a daemon this client did not spawn. Ownership is a boundary:
    /// there is no pid-based path to stopping something we do not own, and the
    /// absence of a pid here is that boundary crossing the bridge.
    pub pid: Option<u32>,
    /// Whether this client may force-stop it. Answered by the core's
    /// capabilities rather than inferred from ownership on this side, because
    /// the two can differ and only one of them is authoritative.
    pub can_force_stop: bool,
    pub last_error: Option<String>,
}

/// What one Orbit is holding.
#[derive(Debug, Clone, PartialEq)]
pub struct StorageRow {
    pub orbit: String,
    /// What the registry calls it. Advisory — a display name is owned by a
    /// World today — and carried as what it is rather than as truth.
    pub name: Option<String>,
    /// Every figure is optional, and that is the contract. A footprint nobody
    /// could measure is *absent*, never zero: an Orbit reported as holding 0
    /// bytes is a claim, and one nobody asked is not.
    pub bytes_on_disk: Option<u64>,
    pub object_count: Option<u64>,
    pub last_verified_ms: Option<u64>,
    /// Why there are no figures, when there are none. Two reasons, because
    /// "not up" and "could not be asked" are different facts.
    pub missing: Option<Missing>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Missing {
    /// It is not up. Not an error, and not something a listing corrects —
    /// measuring must not place what nobody asked to place.
    NotPlaced,
    /// It could not be asked.
    Unreachable,
}

/// One Orbit in this identity's registry.
#[derive(Debug, Clone, PartialEq)]
pub struct OrbitRow {
    pub space: String,
    pub name: String,
    pub path: String,
    /// `None` is never opened, for the same reason it is on a library row.
    pub last_opened: Option<u64>,
}

/// What a gate answered, when a diagnosis was taken.
#[derive(Debug, Clone, PartialEq)]
pub struct GateRow {
    /// Stable machine id — `space`, `daemon`, `membership`, `peer`, `synced`.
    pub id: String,
    pub label: String,
    pub state: GateState,
    pub detail: String,
}

/// Five states, not two.
///
/// `Warn` is deliberately not blocking: a key-custody problem is urgent to fix
/// and irrelevant to whether somebody is onboarded, and a warning that hijacked
/// the blocker would tell a joiner they are stuck when they are not.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GateState {
    Pass,
    Wait,
    Fail,
    Warn,
    Skip,
}

/// A diagnosis, when one was taken.
///
/// Absent when the Space could not be asked — which is *not* the same as every
/// gate passing, and is the whole reason this is an `Option` rather than an
/// empty list of gates.
#[derive(Debug, Clone, PartialEq)]
pub struct DiagnosisRow {
    pub gates: Vec<GateRow>,
    /// The first non-passing gate: the one actionable blocker.
    pub blocked_on: Option<String>,
    pub summary: String,
}

/// The Space somebody is administering, as it last answered.
#[derive(Debug, Clone, PartialEq)]
pub struct SpaceRow {
    pub space: String,
    /// This actor's standing *here*. Per Orbit rather than per identity: one
    /// identity may hold very different standing in two Spaces, and a single
    /// answer would have to pick one and be wrong about the other.
    pub whoami: Option<String>,
    pub admin: bool,
    pub members: Vec<MemberRow>,
    pub devices: Vec<String>,
    pub diagnosis: Option<DiagnosisRow>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MemberRow {
    pub id: String,
    pub nick: Option<String>,
    /// Authored Card name that names this member, when one exists.
    /// Distinct from [`Self::nick`], which is Space-local and derived.
    pub authored_name: Option<String>,
    pub admin: bool,
}

/// The identity's address book, as last read.
#[derive(Debug, Clone, PartialEq)]
pub struct BookFacts {
    pub cards: Vec<CardRow>,
    pub migration_complete: bool,
    pub migration_pending: u32,
    pub migration_imported: u32,
    /// Staged card-exchange proposals awaiting review. Not in the book.
    pub suggestions: Vec<SuggestionRow>,
}

/// One staged suggestion from a card-exchange file. Review is the only way
/// into the book, so this carries exactly what the person must judge.
#[derive(Debug, Clone, PartialEq)]
pub struct SuggestionRow {
    pub suggestion: String,
    pub name: String,
    pub note: String,
    pub handles: Vec<String>,
}

/// One authored Card. Handles are wire spellings, never reachability.
#[derive(Debug, Clone, PartialEq)]
pub struct CardRow {
    pub card: String,
    pub name: String,
    pub note: String,
    pub handles: Vec<String>,
    pub groups: Vec<String>,
    pub self_claim: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct NoticeRow {
    pub said: String,
    /// Where a browser was sent, when that is what happened.
    pub launched: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FailureRow {
    pub what: String,
    pub error: String,
    /// Whether asking again could plausibly work. A refusal is not a retry.
    pub retryable: bool,
}

/// What a person asked for.
///
/// Every mutation crosses as one of these. There is no other route, and in
/// particular there is no "set this field" — a surface that could write a
/// field would be a second model of the thing it wrote.
#[derive(Debug, Clone, PartialEq)]
pub enum ActionRequest {
    /// Read this machine again.
    Refresh,
    /// Hand a World to the person's browser.
    Open {
        orbit: String,
        entry_path: String,
    },
    StartDevice {
        id: String,
    },
    StopDevice {
        id: String,
    },
    RestartDevice {
        id: String,
    },
    /// Force-stop. Only ever offered for a daemon this client owns: ownership
    /// is the safety boundary, and there is no pid-based path across it.
    ForceStopDevice {
        id: String,
    },
    StopAllOwned,
    /// Forget a device. `delete_data` additionally destroys what it holds, and
    /// is the one flag here that cannot be undone.
    RemoveDevice {
        id: String,
        delete_data: bool,
    },
    /// Read one Space. Choosing a Space to administer is an act, not a
    /// listing — it is the read that makes the Members surface answerable.
    ReadSpace {
        orbit: String,
    },
    /// Start a browser head for this identity.
    StartHead,
    StopHead {
        id: String,
    },
    /// Forget an Orbit. The store is left alone; this is registry-only.
    ForgetOrbit {
        space: String,
    },
    BookPut {
        card: Option<String>,
        name: String,
        note: Option<String>,
    },
    BookDelete {
        card: String,
    },
    BookMerge {
        from: String,
        into: String,
    },
    BookClaimSelf {
        card: String,
    },
    BookLink {
        card: String,
        handle: String,
    },
    BookUnlink {
        card: String,
        handle: String,
    },
    BookExport {
        path: String,
        cards: Option<Vec<String>>,
    },
    BookImport {
        path: String,
    },
    BookAccept {
        suggestion: String,
    },
    BookDismiss {
        suggestion: String,
    },
}

impl ActionRequest {
    fn into_action(self) -> Action {
        match self {
            Self::Refresh => Action::Refresh,
            Self::Open { orbit, entry_path } => Action::OpenWorld { orbit, entry_path },
            Self::StartDevice { id } => Action::StartDevice(id),
            Self::StopDevice { id } => Action::StopDevice(id),
            Self::RestartDevice { id } => Action::RestartDevice(id),
            Self::ForceStopDevice { id } => Action::ForceStopDevice(id),
            Self::StopAllOwned => Action::StopAllOwned,
            Self::RemoveDevice { id, delete_data } => Action::RemoveDevice { id, delete_data },
            Self::ReadSpace { orbit } => Action::ReadSpace(space_ref(orbit)),
            Self::StartHead => Action::StartHead,
            Self::StopHead { id } => Action::StopHead(id),
            Self::ForgetOrbit { space } => Action::OrbitForget { space },
            Self::BookPut { card, name, note } => Action::BookPut { card, name, note },
            Self::BookDelete { card } => Action::BookDelete { card },
            Self::BookMerge { from, into } => Action::BookMerge { from, into },
            Self::BookClaimSelf { card } => Action::BookClaimSelf { card },
            Self::BookLink { card, handle } => Action::BookLink { card, handle },
            Self::BookUnlink { card, handle } => Action::BookUnlink { card, handle },
            Self::BookExport { path, cards } => Action::BookExport { path, cards },
            Self::BookImport { path } => Action::BookPropose { path },
            Self::BookAccept { suggestion } => Action::BookAccept { suggestion },
            Self::BookDismiss { suggestion } => Action::BookDismiss { suggestion },
        }
    }
}

/// Resolve an Orbit id to the reference the Space plane needs.
///
/// The path comes from the registry the core already holds. An interface that
/// carried a store path would be holding a fact it could not have checked, and
/// would send a stale one the first time an Orbit moved.
fn space_ref(orbit: String) -> crate::client::space::SpaceRef {
    let path = CORE
        .get()
        .and_then(|core| core.lock().ok())
        .and_then(|core| {
            core.app.context().and_then(|context| {
                context
                    .orbits
                    .iter()
                    .find(|entry| entry.space == orbit)
                    .map(|entry| entry.path.clone())
            })
        })
        .unwrap_or_default();
    crate::client::space::SpaceRef { space: orbit, path }
}

/// The model, the background half, and the identity they were booted for.
struct Core {
    app: App,
    runtime: Runtime,
    state_root: PathBuf,
    sidecar: PathBuf,
}

static CORE: OnceLock<Mutex<Core>> = OnceLock::new();
/// Serialises the first boot so two isolates cannot each start a runtime
/// in the window between "not yet" and `CORE.set`.
static BOOT: Mutex<()> = Mutex::new(());
/// Told by the runtime's wake callback that something has arrived. A channel
/// rather than the mutex, because waking must not be able to block on the lock
/// the pump is holding while it drains.
static WOKEN: OnceLock<Sender<()>> = OnceLock::new();

/// Start the core, or attach to the one that is already running.
///
/// The first isolate boots the runtime. Later ones attach: same App, same
/// supervisor, a new view stream. A second *boot* — a start against a
/// different identity — is refused rather than spawning a second supervisor
/// of the same devices.
#[frb(sync)]
pub fn start(state_root: Option<String>, sidecar: Option<String>) -> Result<(), String> {
    // Resolved here when the caller has no opinion, which is every real launch.
    // The interface must not compute either of these: a path worked out on the
    // far side of the bridge is a second opinion about where this installation
    // keeps its things, and the two would differ on exactly the machine where
    // it mattered. The arguments exist so a test can point the core somewhere
    // disposable, and for nothing else.
    let state_root = match state_root {
        Some(given) => PathBuf::from(given),
        None => crate::sidecar::state_root().map_err(|error| format!("{error:#}"))?,
    };
    let sidecar = match sidecar {
        Some(given) => PathBuf::from(given),
        None => crate::sidecar::resolve().map_err(|error| format!("{error:#}"))?,
    };

    if let Some(core) = CORE.get() {
        return attach_to(core, &state_root, &sidecar);
    }

    let _boot = BOOT
        .lock()
        .map_err(|_| "the core boot lock is poisoned".to_string())?;
    if let Some(core) = CORE.get() {
        return attach_to(core, &state_root, &sidecar);
    }

    let (woken, wakeups) = channel();
    let wake = woken.clone();
    let runtime = Runtime::start(
        Config::new(state_root.clone(), sidecar.clone()),
        move || {
            // A failed send means the pump is gone, which happens only on the
            // way out. Nothing to report and nobody to report it to.
            let _ = wake.send(());
        },
    )
    .map_err(|error| error.to_string())?;

    let _ = CORE.set(Mutex::new(Core {
        app: App::new(),
        runtime,
        state_root,
        sidecar,
    }));
    let _ = WOKEN.set(woken);

    // The pump. It drains and projects; it never draws, and it never holds the
    // lock across the send.
    std::thread::Builder::new()
        .name("astrolabe-pump".into())
        .spawn(move || {
            while wakeups.recv().is_ok() {
                let view = {
                    let Some(core) = CORE.get() else { return };
                    let Ok(mut core) = core.lock() else { return };
                    let Core { app, runtime, .. } = &mut *core;
                    runtime.drain_into(app);
                    project(app)
                };
                emit(view);
            }
        })
        .map_err(|error| format!("start the projection pump: {error}"))?;
    Ok(())
}

fn attach_to(core: &Mutex<Core>, state_root: &Path, sidecar: &Path) -> Result<(), String> {
    let Ok(core) = core.lock() else {
        return Err("the core is poisoned".into());
    };
    attach_paths((&core.state_root, &core.sidecar), (state_root, sidecar))
}

/// Same identity attaches; a different one is a second boot, and is refused.
fn attach_paths(running: (&Path, &Path), asked: (&Path, &Path)) -> Result<(), String> {
    if running.0 == asked.0 && running.1 == asked.1 {
        Ok(())
    } else {
        Err(
            "the core is already running for a different identity — a second boot is refused"
                .into(),
        )
    }
}

/// Ask for something, and get back the view as it stands the instant it was
/// asked for.
///
/// Returning the view rather than nothing is what makes "a control is disabled
/// the moment it is clicked" true across a boundary. Waiting for the pump would
/// leave a live control for one round trip, which is long enough to press four
/// times and see three refusals.
#[frb(sync)]
pub fn dispatch(action: ActionRequest) -> ClientView {
    // Translated *before* the lock is taken: resolving an Orbit reads the
    // registry, which needs the same lock, and a translation done inside the
    // guard would deadlock on exactly the actions that touch a Space.
    let action = action.into_action();
    let Some(core) = CORE.get() else {
        return empty();
    };
    let Ok(mut core) = core.lock() else {
        return empty();
    };
    let Core { app, runtime, .. } = &mut *core;
    app.dispatched(&action);
    runtime.dispatch(action);
    let view = project(app);
    // Every watcher hears about the in-flight action now, not at completion:
    // with two windows on one model, the peer window's control must disable
    // on this dispatch, and the next pump only arrives when the action ends.
    emit(view.clone());
    view
}

/// The view as it stands, for a surface that has just been built.
#[frb(sync)]
pub fn current() -> ClientView {
    let Some(core) = CORE.get() else {
        return empty();
    };
    let Ok(core) = core.lock() else {
        return empty();
    };
    project(&core.app)
}

/// Every view from now on, on this isolate.
///
/// Each attached isolate opens its own stream. Every live sink receives the
/// same [`ClientView`] on every pump; a sink that goes away is dropped and
/// does not stall the rest.
pub fn watch(sink: StreamSink<ClientView>) {
    let sinks = SINKS.get_or_init(|| Mutex::new(Watchers::new()));
    let Ok(mut sinks) = sinks.lock() else {
        return;
    };
    sinks.attach(sink, current());
}

static SINKS: OnceLock<Mutex<Watchers<StreamSink<ClientView>>>> = OnceLock::new();

fn emit(view: ClientView) {
    let Some(sinks) = SINKS.get() else {
        return;
    };
    let Ok(mut sinks) = sinks.lock() else {
        return;
    };
    sinks.emit(&view);
}

/// A sink that can take a view, or say it is gone.
trait ViewPush {
    fn push(&self, view: &ClientView) -> bool;
}

impl ViewPush for StreamSink<ClientView> {
    fn push(&self, view: &ClientView) -> bool {
        self.add(view.clone()).is_ok()
    }
}

/// Every attached isolate's view stream.
struct Watchers<S> {
    sinks: Vec<S>,
}

impl<S: ViewPush> Watchers<S> {
    fn new() -> Self {
        Self { sinks: Vec::new() }
    }

    fn attach(&mut self, sink: S, current: ClientView) {
        if sink.push(&current) {
            self.sinks.push(sink);
        }
    }

    fn emit(&mut self, view: &ClientView) {
        self.sinks.retain(|sink| sink.push(view));
    }

    fn len(&self) -> usize {
        self.sinks.len()
    }
}

fn empty() -> ClientView {
    ClientView {
        loading: true,
        stale: Some(Staleness::NeverLoaded),
        library: None,
        host: None,
        heads: Vec::new(),
        devices: Vec::new(),
        storage: Vec::new(),
        orbits: Vec::new(),
        space: None,
        book: None,
        notices: Vec::new(),
        failures: Vec::new(),
        in_flight: Vec::new(),
    }
}

/// Build the projection. The whole of the boundary's outbound half is this
/// function, which is deliberate: one place to read when asking what Dart can
/// possibly know.
fn project(app: &App) -> ClientView {
    let orbits = app.context().map(|context| context.orbits.as_slice());
    // Asked of the snapshot rather than assumed. Whether this build can
    // force-stop what it owns is a capability the supervisor answers, and an
    // interface that inferred it from ownership would offer a control the core
    // refuses.
    let capabilities = app
        .snapshot()
        .map(|snapshot| snapshot.capabilities.clone())
        .unwrap_or_default();

    ClientView {
        loading: app.is_loading(),
        stale: app.stale().map(|reason| match reason {
            StaleReason::NeverLoaded => Staleness::NeverLoaded,
            StaleReason::Signalled(why) => Staleness::Signalled(why.clone()),
        }),
        library: app.library().map(|entries| {
            entries
                .iter()
                .map(|entry| {
                    let registered = orbits
                        .and_then(|orbits| orbits.iter().find(|orbit| orbit.space == entry.orbit));
                    LibraryRow {
                        key: format!("{}/{}", entry.orbit, entry.world_mount),
                        orbit: entry.orbit.clone(),
                        space: entry.space.clone(),
                        world_mount: entry.world_mount.clone(),
                        display_name: entry.display_name.clone(),
                        placement: match entry.placement {
                            CorePlacement::Placed => PlacementView::Placed,
                            CorePlacement::Vacant => PlacementView::Vacant,
                            CorePlacement::Unknown => PlacementView::Unknown,
                        },
                        opens_at: entry.opens.entry_path().map(str::to_owned),
                        unopenable: match entry.opens {
                            Opens::Unhosted => Some(Unopenable::Unhosted),
                            Opens::Undeclared => Some(Unopenable::Undeclared),
                            Opens::Declared(_) | Opens::Front => None,
                        },
                        // Zero is the registry saying it has never recorded an
                        // opening, which is an absence and travels as one.
                        last_opened: registered
                            .map(|orbit| orbit.last_opened)
                            .filter(|seconds| *seconds > 0),
                        store: registered.map(|orbit| orbit.path.clone()),
                        version: entry.template.version,
                        sync_state: entry.template.sync.as_ref().map(|sync| sync.state.clone()),
                        sync_detail: entry.template.sync.as_ref().map(|sync| sync.detail.clone()),
                        tagline: entry.template.tagline.clone(),
                        accent: entry.template.accent,
                        routes: entry
                            .template
                            .routes
                            .iter()
                            .map(|route| RouteRow {
                                label: route.label.clone(),
                                path: route.path.clone(),
                            })
                            .collect(),
                    }
                })
                .collect()
        }),
        host: app.context().map(|context| HostFacts {
            version: context.version.clone(),
            identity_home: context.identity_home.clone(),
            spaces_root: context.spaces_root.clone(),
            orbit_count: u32::try_from(context.orbits.len()).unwrap_or(u32::MAX),
        }),
        heads: app
            .heads()
            .iter()
            .map(|head| HeadRow {
                id: head.id.clone(),
                kind: format!("{:?}", head.kind).to_lowercase(),
                orbit: head.orbit.clone(),
                origin: head
                    .url
                    .as_deref()
                    .map(|url| url.split('?').next().unwrap_or(url).to_owned()),
                owned: matches!(head.ownership, lait_workbench::Ownership::Owned),
            })
            .collect(),
        devices: app
            .devices()
            .iter()
            .map(|device| DeviceRow {
                id: device.id.clone(),
                label: device.label.clone(),
                state: format!("{:?}", device.state).to_lowercase(),
                owned: device.owned,
                home: device.home.clone(),
                pid: device.pid,
                can_force_stop: device.owned && capabilities.force_stop_owned_process,
                last_error: device.last_error.clone(),
                degraded: match device.observation.state {
                    lait_workbench::ObservationState::Degraded => Some(
                        device
                            .observation
                            .error
                            .clone()
                            .unwrap_or_else(|| "no reason given".into()),
                    ),
                    lait_workbench::ObservationState::Healthy => None,
                },
            })
            .collect(),
        storage: app
            .storage()
            .iter()
            .map(|facts| StorageRow {
                orbit: facts.orbit.clone(),
                name: facts.name.clone(),
                bytes_on_disk: facts.bytes_on_disk,
                object_count: facts.object_count,
                last_verified_ms: facts.last_verified_ms,
                missing: facts.missing.map(|missing| match missing {
                    crate::client::storage::Missing::NotPlaced => Missing::NotPlaced,
                    crate::client::storage::Missing::Unreachable => Missing::Unreachable,
                }),
            })
            .collect(),
        orbits: orbits
            .unwrap_or_default()
            .iter()
            .map(|orbit| OrbitRow {
                space: orbit.space.clone(),
                name: orbit.name.clone(),
                path: orbit.path.clone(),
                last_opened: (orbit.last_opened > 0).then_some(orbit.last_opened),
            })
            .collect(),
        space: app.space().map(|view| SpaceRow {
            space: view.space.clone(),
            whoami: view.standing.actor.clone(),
            admin: view.standing.role == "admin",
            members: view
                .members
                .iter()
                .map(|member| MemberRow {
                    id: member.key.clone(),
                    nick: Some(member.alias.clone()).filter(|alias| !alias.is_empty()),
                    authored_name: authored_name_for(app.book(), &member.key),
                    admin: member.role == "admin",
                })
                .collect(),
            devices: view
                .devices
                .iter()
                .map(|device| device.line.clone())
                .collect(),
            // Absent when the Space could not be diagnosed, which is not the
            // same as every gate passing.
            diagnosis: view.diagnosis.as_ref().map(|taken| DiagnosisRow {
                gates: taken
                    .gates
                    .iter()
                    .map(|gate| GateRow {
                        id: gate.id.clone(),
                        label: gate.label.clone(),
                        state: match gate.state {
                            lait::diagnose::GateState::Pass => GateState::Pass,
                            lait::diagnose::GateState::Wait => GateState::Wait,
                            lait::diagnose::GateState::Fail => GateState::Fail,
                            lait::diagnose::GateState::Warn => GateState::Warn,
                            lait::diagnose::GateState::Skip => GateState::Skip,
                        },
                        detail: gate.detail.clone(),
                    })
                    .collect(),
                blocked_on: taken.blocked_on.clone(),
                summary: taken.summary.clone(),
            }),
        }),
        book: app.book().map(|book| BookFacts {
            cards: book
                .cards
                .iter()
                .map(|card| CardRow {
                    card: card.card.clone(),
                    name: card.name.clone(),
                    note: card.note.clone(),
                    handles: card.handles.clone(),
                    groups: card.groups.clone(),
                    self_claim: card.self_claim,
                })
                .collect(),
            migration_complete: book.migration_complete,
            migration_pending: u32::try_from(book.migration_pending).unwrap_or(u32::MAX),
            migration_imported: u32::try_from(book.migration_imported).unwrap_or(u32::MAX),
            suggestions: book
                .suggestions
                .iter()
                .map(|s| SuggestionRow {
                    suggestion: s.suggestion.clone(),
                    name: s.name.clone(),
                    note: s.note.clone(),
                    handles: s.handles.clone(),
                })
                .collect(),
        }),
        notices: app
            .notices()
            .map(|notice| NoticeRow {
                said: notice.said.clone(),
                launched: notice.launched.as_ref().map(|ticket| ticket.url.clone()),
            })
            .collect(),
        failures: app
            .failures()
            .map(|failure| FailureRow {
                what: failure.what.clone(),
                error: failure.error.to_string(),
                retryable: failure.error.retryable,
            })
            .collect(),
        in_flight: app.in_flight_keys(),
    }
}

fn authored_name_for(
    book: Option<&crate::client::book::BookSnapshot>,
    member_id: &str,
) -> Option<String> {
    let book = book?;
    book.cards
        .iter()
        .find(|card| {
            card.handles
                .iter()
                .any(|handle| handle == member_id || handle.ends_with(&format!(":{member_id}")))
        })
        .map(|card| card.name.clone())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::client::library::LibraryEntry;

    /// The rule that has to survive the crossing: an absence stays an absence.
    /// A registry that has never recorded an opening sends `None`, not a zero
    /// that the other side would render as 1 January 1970.
    #[test]
    fn never_opened_crosses_as_absent_rather_than_as_zero() {
        let mut app = App::new();
        app.absorb_library(vec![LibraryEntry {
            orbit: "orb_one".into(),
            space: "ws_one".into(),
            world_mount: "issues".into(),
            display_name: Some("Issues".into()),
            opens: Opens::Declared("/".into()),
            template: crate::client::library::Template::default(),
            placement: CorePlacement::Vacant,
        }]);
        app.absorb_context(crate::client::host::HostContext {
            version: "lait".into(),
            identity_home: "home".into(),
            spaces_root: "root".into(),
            worlds: Vec::new(),
            identities: Vec::new(),
            orbits: vec![crate::client::host::OrbitEntry {
                space: "orb_one".into(),
                name: "Issues".into(),
                path: "D:/store".into(),
                last_opened: 0,
            }],
        });

        let view = project(&app);
        let row = &view.library.expect("a library was read")[0];
        assert_eq!(
            row.last_opened, None,
            "a never-opened Orbit crossed the bridge as a timestamp"
        );
        assert_eq!(row.store.as_deref(), Some("D:/store"));
        assert_eq!(row.version, None);
        assert_eq!(row.sync_state, None);
        assert_eq!(row.sync_detail, None);
    }

    /// Facts cross; words do not. A row that cannot be opened says *which*
    /// kind of cannot, and the sentence explaining it is Dart's business.
    #[test]
    fn a_row_that_cannot_be_opened_crosses_as_a_reason_not_a_sentence() {
        let mut app = App::new();
        app.absorb_library(vec![
            LibraryEntry {
                orbit: "a".into(),
                space: "a".into(),
                world_mount: "issues".into(),
                display_name: None,
                opens: Opens::Undeclared,
                template: crate::client::library::Template::default(),
                placement: CorePlacement::Placed,
            },
            LibraryEntry {
                orbit: "b".into(),
                space: "b".into(),
                world_mount: "other".into(),
                display_name: None,
                opens: Opens::Unhosted,
                template: crate::client::library::Template::default(),
                placement: CorePlacement::Placed,
            },
            LibraryEntry {
                orbit: "c".into(),
                space: "c".into(),
                world_mount: String::new(),
                display_name: None,
                opens: Opens::Front,
                template: crate::client::library::Template::default(),
                placement: CorePlacement::Vacant,
            },
        ]);

        let rows = project(&app).library.expect("a library was read");
        assert_eq!(rows[0].unopenable, Some(Unopenable::Undeclared));
        assert_eq!(rows[0].opens_at, None);
        assert_eq!(rows[1].unopenable, Some(Unopenable::Unhosted));
        assert_eq!(
            rows[2].opens_at.as_deref(),
            Some("/"),
            "a Space that is not running crossed as unopenable"
        );
        assert_eq!(rows[2].unopenable, None);
    }

    /// Loading is not empty, and it survives the crossing as its own fact.
    #[test]
    fn the_book_crosses_as_authored_cards_not_as_reachability() {
        let mut app = App::new();
        app.absorb_book(crate::client::book::BookSnapshot {
            cards: vec![crate::client::book::CardFacts {
                card: "crd_one".into(),
                name: "Ada".into(),
                note: "colleague".into(),
                handles: vec!["actor:ws_one:act_ada".into()],
                groups: Vec::new(),
                self_claim: true,
            }],
            migration_complete: false,
            migration_pending: 1,
            migration_imported: 0,
            suggestions: vec![crate::client::book::SuggestionFacts {
                suggestion: "sug_abc".into(),
                name: "Grace".into(),
                note: String::new(),
                handles: Vec::new(),
            }],
        });
        let view = project(&app);
        let book = view.book.expect("the book was read");
        assert_eq!(book.cards.len(), 1);
        assert_eq!(book.cards[0].name, "Ada");
        assert_eq!(book.cards[0].handles[0], "actor:ws_one:act_ada");
        assert!(book.cards[0].self_claim);
        assert_eq!(book.migration_pending, 1);
        assert_eq!(book.suggestions.len(), 1, "staged suggestions cross whole");
        assert_eq!(book.suggestions[0].suggestion, "sug_abc");
        assert_eq!(
            authored_name_for(app.book(), "act_ada").as_deref(),
            Some("Ada")
        );
        assert_eq!(
            authored_name_for(app.book(), "Ada"),
            None,
            "a Card name is not a handle"
        );
    }

    #[test]
    fn loading_and_empty_are_told_apart_across_the_bridge() {
        let loading = project(&App::new());
        assert!(loading.loading);
        assert_eq!(loading.stale, Some(Staleness::NeverLoaded));
        assert!(loading.library.is_none());

        let mut read = App::new();
        read.absorb_library(Vec::new());
        let read = project(&read);
        assert_eq!(
            read.library,
            Some(Vec::new()),
            "a device that answered and serves nothing looks unread"
        );
    }

    /// A second isolate attaches; a second *boot* against a different
    /// identity is refused. The paths are the whole identity: two
    /// supervisors of one device set is the failure this exists to stop.
    #[test]
    fn a_second_boot_against_a_different_identity_is_refused() {
        let home = Path::new("C:/ident");
        let sidecar = Path::new("C:/lait.exe");
        assert!(attach_paths((home, sidecar), (home, sidecar)).is_ok());
        let err = attach_paths((home, sidecar), (Path::new("C:/other"), sidecar))
            .expect_err("a different identity is a second boot");
        assert!(
            err.contains("second boot"),
            "the refusal must name the second boot, got: {err}"
        );
    }

    struct FakeSink {
        views: std::sync::Arc<Mutex<Vec<ClientView>>>,
        live: bool,
    }

    impl ViewPush for FakeSink {
        fn push(&self, view: &ClientView) -> bool {
            if !self.live {
                return false;
            }
            self.views.lock().expect("views").push(view.clone());
            true
        }
    }

    fn fake(live: bool) -> (FakeSink, std::sync::Arc<Mutex<Vec<ClientView>>>) {
        let views = std::sync::Arc::new(Mutex::new(Vec::new()));
        (
            FakeSink {
                views: views.clone(),
                live,
            },
            views,
        )
    }

    /// Every attached isolate receives the same view on every pump.
    #[test]
    fn every_watcher_receives_the_same_view() {
        let (a, a_views) = fake(true);
        let (b, b_views) = fake(true);
        let mut watchers = Watchers::new();
        let first = empty();
        watchers.attach(a, first.clone());
        watchers.attach(b, first.clone());
        let next = {
            let mut view = empty();
            view.loading = false;
            view
        };
        watchers.emit(&next);
        let a_views = a_views.lock().expect("a");
        let b_views = b_views.lock().expect("b");
        assert_eq!(a_views.as_slice(), &[first.clone(), next.clone()]);
        assert_eq!(b_views.as_slice(), &[first, next]);
    }

    /// A sink that goes away is dropped and does not stall the rest.
    #[test]
    fn a_dead_watcher_is_dropped_and_the_rest_keep_pumping() {
        let (dead, dead_views) = fake(false);
        let (live, live_views) = fake(true);
        let mut watchers = Watchers::new();
        watchers.attach(dead, empty());
        watchers.attach(live, empty());
        assert_eq!(
            dead_views.lock().expect("dead").len(),
            0,
            "a dead sink must not be kept"
        );
        assert_eq!(live_views.lock().expect("live").len(), 1);

        let next = {
            let mut view = empty();
            view.loading = false;
            view
        };
        watchers.emit(&next);
        assert_eq!(watchers.len(), 1);
        assert_eq!(live_views.lock().expect("live").len(), 2);
    }
}
