//! The bridge, and the only thing that crosses it.
//!
//! Revision 7 of the Plan puts a Dart interface over this Rust core, which
//! means there is a boundary again — the one revisions 5 and 6 removed on
//! purpose. Everything in this module exists to make that boundary safe by
//! construction rather than by care.
//!
//! ## What crosses, and in which direction
//!
//! Exactly two things. A [`ClientView`] goes out — a whole, immutable
//! projection of client state, built here and never assembled on the other
//! side. An [`ActionRequest`] comes back — a thing a person asked for. Nothing
//! else has a route across.
//!
//! ## Facts go out; words do not
//!
//! The view carries *what is true*, not what to say about it. A placement is
//! [`Placement::Vacant`], never "not running"; a row that cannot be opened
//! carries [`Unopenable::Undeclared`], never the sentence explaining it. That
//! split is what keeps the fifth lockdown rule honest: Dart owns wording and
//! layout, and cannot own a fact because it is never sent one it could have
//! derived differently.
//!
//! It is also why absence is modelled rather than encoded. `last_opened` is an
//! `Option<u64>` and not a `u64` where zero means never, because "never opened"
//! and "opened at the epoch" are different facts and a sentinel makes them the
//! same one. Unmeasured is absent, never zero — the rule survives the crossing
//! only if the wire format can say it.
//!
//! ## One model, still
//!
//! [`App`] stays the only model of client state. This module holds it, drains
//! the runtime into it, and projects it. Dart receives the projection whole and
//! keeps nothing of its own but drafts.

use std::sync::mpsc::{channel, Sender};
use std::sync::{Mutex, OnceLock};

use flutter_rust_bridge::frb;

// Generated by the bridge codegen and checked in beside this file. Named
// through the generated module rather than the crate root because that is
// where the codegen puts the concrete codec.
use crate::frb_generated::StreamSink;

use crate::client::library::{Opens, Placement as CorePlacement};
use crate::model::{App, StaleReason};
use crate::runtime::{Action, Runtime};
use crate::Config;

/// Everything a surface can draw, as of one moment.
///
/// Sent whole. There is no partial update and no patch protocol, because a
/// patch protocol is a second model in disguise: the receiver has to hold the
/// previous state and apply changes to it, and the moment it can do that it can
/// disagree with the sender.
#[derive(Debug, Clone, PartialEq)]
pub struct ClientView {
    /// Nothing has been read yet. Distinct from "read, and there is nothing".
    pub loading: bool,
    /// Why what is on screen may not be current. `None` is fresh.
    pub stale: Option<Staleness>,
    /// `None` until the library has been read once — which is not the same as
    /// a device that serves nothing.
    pub library: Option<Vec<LibraryRow>>,
    pub host: Option<HostFacts>,
    pub heads: Vec<HeadRow>,
    pub devices: Vec<DeviceRow>,
    pub notices: Vec<NoticeRow>,
    pub failures: Vec<FailureRow>,
    /// The keys of actions asked for and not yet answered. A control whose key
    /// is in here is disabled — on the frame the click happened, not on
    /// whichever later frame the answer arrives.
    pub in_flight: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Staleness {
    /// The first read has not landed.
    NeverLoaded,
    /// The stream said so, and said why.
    Signalled(String),
}

/// One row of the Library.
#[derive(Debug, Clone, PartialEq)]
pub struct LibraryRow {
    /// Stable across re-reads: the Orbit and the World in it. A selection
    /// keyed by index would silently follow whatever moved into that position.
    pub key: String,
    pub orbit: String,
    pub space: String,
    /// Empty when the row is the Space itself rather than a World in it.
    pub world_mount: String,
    /// `None` means nothing authoritative names it. Drawn as unnamed rather
    /// than as an id dressed up as a name.
    pub display_name: Option<String>,
    pub placement: PlacementView,
    /// Where `Open` lands. `None` with [`Self::unopenable`] set is a row that
    /// cannot be opened at all.
    pub opens_at: Option<String>,
    pub unopenable: Option<Unopenable>,
    /// Wall-clock seconds. `None` is *never opened*, which a zero would
    /// silently turn into 1 January 1970.
    pub last_opened: Option<u64>,
    /// Where the Orbit's store lives, when the registry could be read.
    pub store: Option<String>,
}

/// Whether an Orbit is currently up. Three states, because "not running" and
/// "could not be asked" are different facts and only one is worth acting on.
///
/// Named apart from [`crate::client::library::Placement`] on purpose: the
/// codegen flattens type names across the crate and picks between collisions at
/// random, so a DTO that shared a name with a core type would be a coin toss
/// nobody could see land.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlacementView {
    Placed,
    Vacant,
    Unknown,
}

/// Why a row cannot be opened. Two facts, not one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Unopenable {
    /// This build hosts no head for that World.
    Unhosted,
    /// The World is hosted here and has not declared where to open it.
    Undeclared,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HostFacts {
    pub version: String,
    pub identity_home: String,
    pub spaces_root: String,
    pub orbit_count: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HeadRow {
    pub id: String,
    /// Browser or MCP.
    pub kind: String,
    /// The Orbit it is bound to. `None` is a browser head serving every Orbit
    /// its identity has.
    pub orbit: Option<String>,
    /// The address, *without* the run credential its URL carries. A front page
    /// has no use for a credential — `Open` mints a single-use ticket of its
    /// own, which is what that ceremony is for.
    pub origin: Option<String>,
    pub owned: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct DeviceRow {
    pub id: String,
    pub label: String,
    pub state: String,
    pub owned: bool,
    /// Whether observation of this device is degraded, and what went wrong.
    /// A sampling failure preserves the last good reading and says so; it is
    /// never drawn as "nothing there".
    pub degraded: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct NoticeRow {
    pub said: String,
    /// Where a browser was sent, when that is what happened.
    pub launched: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct FailureRow {
    pub what: String,
    pub error: String,
    /// Whether asking again could plausibly work. A refusal is not a retry.
    pub retryable: bool,
}

/// What a person asked for.
///
/// Every mutation crosses as one of these. There is no other route, and in
/// particular there is no "set this field" — a surface that could write a
/// field would be a second model of the thing it wrote.
#[derive(Debug, Clone, PartialEq)]
pub enum ActionRequest {
    /// Read this machine again.
    Refresh,
    /// Hand a World to the person's browser.
    Open {
        orbit: String,
        entry_path: String,
    },
    StartDevice {
        id: String,
    },
    StopDevice {
        id: String,
    },
    RestartDevice {
        id: String,
    },
}

impl ActionRequest {
    fn into_action(self) -> Action {
        match self {
            Self::Refresh => Action::Refresh,
            Self::Open { orbit, entry_path } => Action::OpenWorld { orbit, entry_path },
            Self::StartDevice { id } => Action::StartDevice(id),
            Self::StopDevice { id } => Action::StopDevice(id),
            Self::RestartDevice { id } => Action::RestartDevice(id),
        }
    }
}

/// The model, the background half, and nothing else.
struct Core {
    app: App,
    runtime: Runtime,
}

static CORE: OnceLock<Mutex<Core>> = OnceLock::new();
/// Told by the runtime's wake callback that something has arrived. A channel
/// rather than the mutex, because waking must not be able to block on the lock
/// the pump is holding while it drains.
static WOKEN: OnceLock<Sender<()>> = OnceLock::new();

/// Start the core. Idempotent: a second call is a no-op rather than a second
/// runtime, because two runtimes would be two supervisors of the same devices.
#[frb(sync)]
pub fn start(state_root: Option<String>, sidecar: Option<String>) -> Result<(), String> {
    if CORE.get().is_some() {
        return Ok(());
    }
    // Resolved here when the caller has no opinion, which is every real launch.
    // The interface must not compute either of these: a path worked out on the
    // far side of the bridge is a second opinion about where this installation
    // keeps its things, and the two would differ on exactly the machine where
    // it mattered. The arguments exist so a test can point the core somewhere
    // disposable, and for nothing else.
    let state_root = match state_root {
        Some(given) => std::path::PathBuf::from(given),
        None => crate::sidecar::state_root().map_err(|error| format!("{error:#}"))?,
    };
    let sidecar = match sidecar {
        Some(given) => std::path::PathBuf::from(given),
        None => crate::sidecar::resolve().map_err(|error| format!("{error:#}"))?,
    };

    let (woken, wakeups) = channel();
    let wake = woken.clone();
    let runtime = Runtime::start(Config::new(state_root, sidecar), move || {
        // A failed send means the pump is gone, which happens only on the
        // way out. Nothing to report and nobody to report it to.
        let _ = wake.send(());
    })
    .map_err(|error| error.to_string())?;

    let _ = CORE.set(Mutex::new(Core {
        app: App::new(),
        runtime,
    }));
    let _ = WOKEN.set(woken);

    // The pump. It drains and projects; it never draws, and it never holds the
    // lock across the send.
    std::thread::Builder::new()
        .name("astrolabe-pump".into())
        .spawn(move || {
            while wakeups.recv().is_ok() {
                let view = {
                    let Some(core) = CORE.get() else { return };
                    let Ok(mut core) = core.lock() else { return };
                    let Core { app, runtime } = &mut *core;
                    runtime.drain_into(app);
                    project(app)
                };
                emit(view);
            }
        })
        .map_err(|error| format!("start the projection pump: {error}"))?;
    Ok(())
}

/// Ask for something, and get back the view as it stands the instant it was
/// asked for.
///
/// Returning the view rather than nothing is what makes "a control is disabled
/// the moment it is clicked" true across a boundary. Waiting for the pump would
/// leave a live control for one round trip, which is long enough to press four
/// times and see three refusals.
#[frb(sync)]
pub fn dispatch(action: ActionRequest) -> ClientView {
    let action = action.into_action();
    let Some(core) = CORE.get() else {
        return empty();
    };
    let Ok(mut core) = core.lock() else {
        return empty();
    };
    let Core { app, runtime } = &mut *core;
    app.dispatched(&action);
    runtime.dispatch(action);
    project(app)
}

/// The view as it stands, for a surface that has just been built.
#[frb(sync)]
pub fn current() -> ClientView {
    let Some(core) = CORE.get() else {
        return empty();
    };
    let Ok(core) = core.lock() else {
        return empty();
    };
    project(&core.app)
}

/// Every view from now on.
pub fn watch(sink: StreamSink<ClientView>) {
    let _ = sink.add(current());
    let _ = SINK.set(Mutex::new(Some(sink)));
}

static SINK: OnceLock<Mutex<Option<StreamSink<ClientView>>>> = OnceLock::new();

fn emit(view: ClientView) {
    if let Some(sink) = SINK.get() {
        if let Ok(sink) = sink.lock() {
            if let Some(sink) = sink.as_ref() {
                let _ = sink.add(view);
            }
        }
    }
}

fn empty() -> ClientView {
    ClientView {
        loading: true,
        stale: Some(Staleness::NeverLoaded),
        library: None,
        host: None,
        heads: Vec::new(),
        devices: Vec::new(),
        notices: Vec::new(),
        failures: Vec::new(),
        in_flight: Vec::new(),
    }
}

/// Build the projection. The whole of the boundary's outbound half is this
/// function, which is deliberate: one place to read when asking what Dart can
/// possibly know.
fn project(app: &App) -> ClientView {
    let orbits = app.context().map(|context| context.orbits.as_slice());

    ClientView {
        loading: app.is_loading(),
        stale: app.stale().map(|reason| match reason {
            StaleReason::NeverLoaded => Staleness::NeverLoaded,
            StaleReason::Signalled(why) => Staleness::Signalled(why.clone()),
        }),
        library: app.library().map(|entries| {
            entries
                .iter()
                .map(|entry| {
                    let registered = orbits
                        .and_then(|orbits| orbits.iter().find(|orbit| orbit.space == entry.orbit));
                    LibraryRow {
                        key: format!("{}/{}", entry.orbit, entry.world_mount),
                        orbit: entry.orbit.clone(),
                        space: entry.space.clone(),
                        world_mount: entry.world_mount.clone(),
                        display_name: entry.display_name.clone(),
                        placement: match entry.placement {
                            CorePlacement::Placed => PlacementView::Placed,
                            CorePlacement::Vacant => PlacementView::Vacant,
                            CorePlacement::Unknown => PlacementView::Unknown,
                        },
                        opens_at: entry.opens.entry_path().map(str::to_owned),
                        unopenable: match entry.opens {
                            Opens::Unhosted => Some(Unopenable::Unhosted),
                            Opens::Undeclared => Some(Unopenable::Undeclared),
                            Opens::Declared(_) | Opens::Front => None,
                        },
                        // Zero is the registry saying it has never recorded an
                        // opening, which is an absence and travels as one.
                        last_opened: registered
                            .map(|orbit| orbit.last_opened)
                            .filter(|seconds| *seconds > 0),
                        store: registered.map(|orbit| orbit.path.clone()),
                    }
                })
                .collect()
        }),
        host: app.context().map(|context| HostFacts {
            version: context.version.clone(),
            identity_home: context.identity_home.clone(),
            spaces_root: context.spaces_root.clone(),
            orbit_count: u32::try_from(context.orbits.len()).unwrap_or(u32::MAX),
        }),
        heads: app
            .heads()
            .iter()
            .map(|head| HeadRow {
                id: head.id.clone(),
                kind: format!("{:?}", head.kind).to_lowercase(),
                orbit: head.orbit.clone(),
                origin: head
                    .url
                    .as_deref()
                    .map(|url| url.split('?').next().unwrap_or(url).to_owned()),
                owned: matches!(head.ownership, lait_workbench::Ownership::Owned),
            })
            .collect(),
        devices: app
            .devices()
            .iter()
            .map(|device| DeviceRow {
                id: device.id.clone(),
                label: device.label.clone(),
                state: format!("{:?}", device.state).to_lowercase(),
                owned: device.owned,
                degraded: match device.observation.state {
                    lait_workbench::ObservationState::Degraded => Some(
                        device
                            .observation
                            .error
                            .clone()
                            .unwrap_or_else(|| "no reason given".into()),
                    ),
                    lait_workbench::ObservationState::Healthy => None,
                },
            })
            .collect(),
        notices: app
            .notices()
            .map(|notice| NoticeRow {
                said: notice.said.clone(),
                launched: notice.launched.as_ref().map(|ticket| ticket.url.clone()),
            })
            .collect(),
        failures: app
            .failures()
            .map(|failure| FailureRow {
                what: failure.what.clone(),
                error: failure.error.to_string(),
                retryable: failure.error.retryable,
            })
            .collect(),
        in_flight: app.in_flight_keys(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::client::library::LibraryEntry;

    /// The rule that has to survive the crossing: an absence stays an absence.
    /// A registry that has never recorded an opening sends `None`, not a zero
    /// that the other side would render as 1 January 1970.
    #[test]
    fn never_opened_crosses_as_absent_rather_than_as_zero() {
        let mut app = App::new();
        app.absorb_library(vec![LibraryEntry {
            orbit: "orb_one".into(),
            space: "ws_one".into(),
            world_mount: "issues".into(),
            display_name: Some("Issues".into()),
            opens: Opens::Declared("/".into()),
            placement: CorePlacement::Vacant,
        }]);
        app.absorb_context(crate::client::host::HostContext {
            version: "lait".into(),
            identity_home: "home".into(),
            spaces_root: "root".into(),
            worlds: Vec::new(),
            identities: Vec::new(),
            orbits: vec![crate::client::host::OrbitEntry {
                space: "orb_one".into(),
                name: "Issues".into(),
                path: "D:/store".into(),
                last_opened: 0,
            }],
        });

        let view = project(&app);
        let row = &view.library.expect("a library was read")[0];
        assert_eq!(
            row.last_opened, None,
            "a never-opened Orbit crossed the bridge as a timestamp"
        );
        assert_eq!(row.store.as_deref(), Some("D:/store"));
    }

    /// Facts cross; words do not. A row that cannot be opened says *which*
    /// kind of cannot, and the sentence explaining it is Dart's business.
    #[test]
    fn a_row_that_cannot_be_opened_crosses_as_a_reason_not_a_sentence() {
        let mut app = App::new();
        app.absorb_library(vec![
            LibraryEntry {
                orbit: "a".into(),
                space: "a".into(),
                world_mount: "issues".into(),
                display_name: None,
                opens: Opens::Undeclared,
                placement: CorePlacement::Placed,
            },
            LibraryEntry {
                orbit: "b".into(),
                space: "b".into(),
                world_mount: "other".into(),
                display_name: None,
                opens: Opens::Unhosted,
                placement: CorePlacement::Placed,
            },
            LibraryEntry {
                orbit: "c".into(),
                space: "c".into(),
                world_mount: String::new(),
                display_name: None,
                opens: Opens::Front,
                placement: CorePlacement::Vacant,
            },
        ]);

        let rows = project(&app).library.expect("a library was read");
        assert_eq!(rows[0].unopenable, Some(Unopenable::Undeclared));
        assert_eq!(rows[0].opens_at, None);
        assert_eq!(rows[1].unopenable, Some(Unopenable::Unhosted));
        assert_eq!(
            rows[2].opens_at.as_deref(),
            Some("/"),
            "a Space that is not running crossed as unopenable"
        );
        assert_eq!(rows[2].unopenable, None);
    }

    /// Loading is not empty, and it survives the crossing as its own fact.
    #[test]
    fn loading_and_empty_are_told_apart_across_the_bridge() {
        let loading = project(&App::new());
        assert!(loading.loading);
        assert_eq!(loading.stale, Some(Staleness::NeverLoaded));
        assert!(loading.library.is_none());

        let mut read = App::new();
        read.absorb_library(Vec::new());
        let read = project(&read);
        assert_eq!(
            read.library,
            Some(Vec::new()),
            "a device that answered and serves nothing looks unread"
        );
    }
}
