/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/laitTheme.ts
 * Command: astryx theme build src/theme/laitTheme.ts --out src/theme/lait.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./lait.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const laitTheme: DefinedTheme;
