// GENERATED by tool/generate-astryx-theme.mjs — do not edit.
//
// The palette in `tool/palette.mjs`, projected onto Astryx's token vocabulary.
// Colour is derived, not authored: a seed gives a hue, and lightness and chroma
// come from shared curves. Edit the seeds or the curves and re-run
// `npm run tokens:astryx`.
//
// Values stay in `oklch()` rather than hex so the browser keeps gamut-mapping
// per display. `[light, dark]` tuples become `light-dark()` inside defineTheme.

import {defineTheme} from "@astryxdesign/core/theme";

export const laitTheme = defineTheme({
  name: "lait",

  typography: {
    body: {family: "Inter Variable", fallbacks: "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif"},
    heading: {family: "Inter Variable", fallbacks: "ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif"},
    code: {family: "Roboto Mono Variable", fallbacks: "ui-monospace, SFMono-Regular, \"SF Mono\", Menlo, Consolas, monospace"},
  },

  // Snappier than Astryx's 175/410/975 default. A tracker is a keyboard
  // surface: the animation has to be finished before the next keystroke lands,
  // not still easing through it.
  motion: {fast: 110, medium: 260, slow: 600, ratio: 0.75},

  tokens: {
    // Surfaces — our sunken < bg < raised ladder, mapped onto Astryx's roles
    "--color-background-muted": ["oklch(0.968 0.003 286)", "oklch(0.165 0.005 286)"],
    "--color-background-body": ["oklch(0.985 0.001 286)", "oklch(0.188 0.006 286)"],
    "--color-background-surface": ["oklch(1 0 0)", "oklch(0.228 0.008 286)"],
    "--color-background-card": ["oklch(1 0 0)", "oklch(0.228 0.008 286)"],
    "--color-background-popover": ["oklch(1 0 0)", "oklch(0.228 0.008 286)"],
    "--color-background-inverted": ["oklch(0.206 0.006 286)", "oklch(0.935 0.004 286)"],

    // Interaction — see note: the overlay-* alphas stay Astryx's on purpose
    "--color-tint-hover": ["oklch(0.962 0.003 286)", "oklch(0.256 0.01 286)"],
    "--color-skeleton": ["oklch(0.962 0.003 286)", "oklch(0.256 0.01 286)"],
    "--color-track": ["oklch(0.926 0.005 286)", "oklch(0.31 0.013 286)"],

    // Lines
    "--color-border": ["oklch(0.926 0.005 286)", "oklch(0.31 0.013 286)"],
    "--color-border-emphasized": ["oklch(0.866 0.01 286)", "oklch(0.365 0.016 286)"],

    // Text and icons — dim is the secondary voice, mute the tertiary
    "--color-text-primary": ["oklch(0.206 0.006 286)", "oklch(0.935 0.004 286)"],
    "--color-text-secondary": ["oklch(0.478 0.016 286)", "oklch(0.709 0.014 286)"],
    "--color-text-disabled": ["oklch(0.556 0.017 286)", "oklch(0.62 0.016 286)"],
    "--color-text-accent": ["oklch(0.581 0.2 264)", "oklch(0.571 0.17 264)"],
    "--color-icon-primary": ["oklch(0.206 0.006 286)", "oklch(0.935 0.004 286)"],
    "--color-icon-secondary": ["oklch(0.478 0.016 286)", "oklch(0.709 0.014 286)"],
    "--color-icon-disabled": ["oklch(0.556 0.017 286)", "oklch(0.62 0.016 286)"],
    "--color-icon-accent": ["oklch(0.581 0.2 264)", "oklch(0.571 0.17 264)"],

    // Accent and status
    "--color-accent": ["oklch(0.581 0.2 264)", "oklch(0.571 0.17 264)"],
    "--color-accent-muted": "color-mix(in oklch, var(--color-accent) 12%, var(--color-background-body))",
    "--color-on-accent": "#ffffff",
    "--color-success": ["oklch(0.581 0.2 147)", "oklch(0.571 0.17 147)"],
    "--color-success-muted": "color-mix(in oklch, var(--color-success) 12%, var(--color-background-body))",
    "--color-on-success": "#ffffff",
    "--color-error": ["oklch(0.581 0.2 22)", "oklch(0.571 0.17 22)"],
    "--color-error-muted": "color-mix(in oklch, var(--color-error) 12%, var(--color-background-body))",
    "--color-on-error": "#ffffff",
    "--color-warning": ["oklch(0.561 0.2 78)", "oklch(0.671 0.17 78)"],
    "--color-warning-muted": "color-mix(in oklch, var(--color-warning) 12%, var(--color-background-body))",
    "--color-on-warning": "oklch(0.206 0.006 286)",

    // Categorical — Astryx's nine hues, on our curve
    "--color-text-red": ["oklch(0.581 0.2 25)", "oklch(0.571 0.17 25)"],
    "--color-icon-red": ["oklch(0.581 0.2 25)", "oklch(0.571 0.17 25)"],
    "--color-border-red": "color-mix(in oklch, var(--color-text-red) 40%, var(--color-background-body))",
    "--color-background-red": "color-mix(in oklch, var(--color-text-red) 12%, var(--color-background-body))",
    "--color-text-orange": ["oklch(0.561 0.2 65)", "oklch(0.671 0.17 65)"],
    "--color-icon-orange": ["oklch(0.561 0.2 65)", "oklch(0.671 0.17 65)"],
    "--color-border-orange": "color-mix(in oklch, var(--color-text-orange) 40%, var(--color-background-body))",
    "--color-background-orange": "color-mix(in oklch, var(--color-text-orange) 12%, var(--color-background-body))",
    "--color-text-yellow": ["oklch(0.561 0.2 90)", "oklch(0.671 0.17 90)"],
    "--color-icon-yellow": ["oklch(0.561 0.2 90)", "oklch(0.671 0.17 90)"],
    "--color-border-yellow": "color-mix(in oklch, var(--color-text-yellow) 40%, var(--color-background-body))",
    "--color-background-yellow": "color-mix(in oklch, var(--color-text-yellow) 12%, var(--color-background-body))",
    "--color-text-green": ["oklch(0.581 0.2 145)", "oklch(0.571 0.17 145)"],
    "--color-icon-green": ["oklch(0.581 0.2 145)", "oklch(0.571 0.17 145)"],
    "--color-border-green": "color-mix(in oklch, var(--color-text-green) 40%, var(--color-background-body))",
    "--color-background-green": "color-mix(in oklch, var(--color-text-green) 12%, var(--color-background-body))",
    "--color-text-teal": ["oklch(0.581 0.2 180)", "oklch(0.571 0.17 180)"],
    "--color-icon-teal": ["oklch(0.581 0.2 180)", "oklch(0.571 0.17 180)"],
    "--color-border-teal": "color-mix(in oklch, var(--color-text-teal) 40%, var(--color-background-body))",
    "--color-background-teal": "color-mix(in oklch, var(--color-text-teal) 12%, var(--color-background-body))",
    "--color-text-cyan": ["oklch(0.581 0.2 215)", "oklch(0.571 0.17 215)"],
    "--color-icon-cyan": ["oklch(0.581 0.2 215)", "oklch(0.571 0.17 215)"],
    "--color-border-cyan": "color-mix(in oklch, var(--color-text-cyan) 40%, var(--color-background-body))",
    "--color-background-cyan": "color-mix(in oklch, var(--color-text-cyan) 12%, var(--color-background-body))",
    "--color-text-blue": ["oklch(0.581 0.2 250)", "oklch(0.571 0.17 250)"],
    "--color-icon-blue": ["oklch(0.581 0.2 250)", "oklch(0.571 0.17 250)"],
    "--color-border-blue": "color-mix(in oklch, var(--color-text-blue) 40%, var(--color-background-body))",
    "--color-background-blue": "color-mix(in oklch, var(--color-text-blue) 12%, var(--color-background-body))",
    "--color-text-purple": ["oklch(0.581 0.2 320)", "oklch(0.571 0.17 320)"],
    "--color-icon-purple": ["oklch(0.581 0.2 320)", "oklch(0.571 0.17 320)"],
    "--color-border-purple": "color-mix(in oklch, var(--color-text-purple) 40%, var(--color-background-body))",
    "--color-background-purple": "color-mix(in oklch, var(--color-text-purple) 12%, var(--color-background-body))",
    "--color-text-pink": ["oklch(0.581 0.2 355)", "oklch(0.571 0.17 355)"],
    "--color-icon-pink": ["oklch(0.581 0.2 355)", "oklch(0.571 0.17 355)"],
    "--color-border-pink": "color-mix(in oklch, var(--color-text-pink) 40%, var(--color-background-body))",
    "--color-background-pink": "color-mix(in oklch, var(--color-text-pink) 12%, var(--color-background-body))",
    "--color-text-gray": ["oklch(0.478 0.016 286)", "oklch(0.709 0.014 286)"],
    "--color-icon-gray": ["oklch(0.478 0.016 286)", "oklch(0.709 0.014 286)"],
    "--color-border-gray": ["oklch(0.926 0.005 286)", "oklch(0.31 0.013 286)"],
    "--color-background-gray": ["oklch(0.968 0.003 286)", "oklch(0.165 0.005 286)"],

    // Radius — mark/control/surface land on inner/element/container
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "16px",

    // Elevation — `low` is a chip's lift, not a card's
    "--shadow-low": "0px 1px 1px light-dark(rgba(0, 0, 0, 0.04), rgba(0, 0, 0, 0.18)), 0px 1px 2px light-dark(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.14))",

    // Type sizes — explicit, not a generated ratio: our ladder is bent
    "--font-size-2xs": "10px",
    "--font-size-xs": "11px",
    "--font-size-sm": "12px",
    "--font-size-base": "13px",
    "--font-size-lg": "15px",
  },

  // Priority is lait's vocabulary, not Astryx's. These four keys are not in
  // the base variant types; `astryx theme build` detects that and emits the
  // module augmentations that make them type-check.
  components: {
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)"
      },
      "variant:secondary": {
        "backgroundColor": "var(--color-background-surface)",
        "color": "var(--color-text-primary)",
        ":hover": {
          "backgroundColor": "var(--color-tint-hover)"
        }
      },
      "variant:active": {
        "backgroundColor": "light-dark(oklch(0.947 0.004 286), oklch(0.282 0.013 286))",
        "color": "var(--color-text-primary)",
        "boxShadow": "0 0 0 0.5px light-dark(rgb(0 0 0 / 0.09), rgb(255 255 255 / 0.1))"
      },
      "variant:primary": {
        "backgroundColor": "var(--color-background-inverted)",
        "color": "var(--color-background-body)",
        ":hover": {
          "backgroundColor": "color-mix(in oklch, var(--color-background-inverted) 85%, var(--color-background-body))"
        }
      },
      "variant:danger": {
        "backgroundColor": "transparent",
        "color": "var(--color-text-disabled)",
        ":hover": {
          "backgroundColor": "var(--color-error-muted)",
          "color": "var(--color-error)"
        }
      }
    },
    "iconbutton": {
      "base": {
        "borderRadius": "var(--radius-full)"
      },
      "variant:secondary": {
        "backgroundColor": "var(--color-background-surface)",
        "color": "var(--color-text-primary)",
        ":hover": {
          "backgroundColor": "var(--color-tint-hover)"
        }
      },
      "variant:active": {
        "backgroundColor": "light-dark(oklch(0.947 0.004 286), oklch(0.282 0.013 286))",
        "color": "var(--color-text-primary)",
        "boxShadow": "0 0 0 0.5px light-dark(rgb(0 0 0 / 0.09), rgb(255 255 255 / 0.1))"
      },
      "variant:primary": {
        "backgroundColor": "var(--color-background-inverted)",
        "color": "var(--color-background-body)",
        ":hover": {
          "backgroundColor": "color-mix(in oklch, var(--color-background-inverted) 85%, var(--color-background-body))"
        }
      },
      "variant:danger": {
        "backgroundColor": "transparent",
        "color": "var(--color-text-disabled)",
        ":hover": {
          "backgroundColor": "var(--color-error-muted)",
          "color": "var(--color-error)"
        }
      }
    },
    "popover": {
      "base": {
        "padding": "0"
      }
    },
    "dialog": {
      "base": {
        "padding": "0"
      }
    },
    "dropdown-menu": {
      "base": {
        "padding": "6px"
      }
    },
    "dropdown-menu-item": {
      "base": {
        ":hover": {
          "backgroundColor": "var(--color-tint-hover)"
        },
        ":focus-visible": {
          "backgroundColor": "var(--color-tint-hover)"
        }
      }
    },
    "statusdot": {
      "variant:urgent": {
        "backgroundColor": "light-dark(oklch(0.581 0.18 22), oklch(0.631 0.145 22))"
      },
      "variant:high": {
        "backgroundColor": "light-dark(oklch(0.581 0.18 40), oklch(0.631 0.145 40))"
      },
      "variant:medium": {
        "backgroundColor": "light-dark(oklch(0.561 0.18 78), oklch(0.731 0.145 78))"
      },
      "variant:low": {
        "backgroundColor": "light-dark(oklch(0.581 0.18 250), oklch(0.631 0.145 250))"
      }
    },
    "badge": {
      "variant:urgent": {
        "color": "light-dark(oklch(0.581 0.18 22), oklch(0.631 0.145 22))",
        "backgroundColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 22), oklch(0.631 0.145 22)) 12%, var(--color-background-body))",
        "borderColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 22), oklch(0.631 0.145 22)) 40%, var(--color-background-body))"
      },
      "variant:high": {
        "color": "light-dark(oklch(0.581 0.18 40), oklch(0.631 0.145 40))",
        "backgroundColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 40), oklch(0.631 0.145 40)) 12%, var(--color-background-body))",
        "borderColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 40), oklch(0.631 0.145 40)) 40%, var(--color-background-body))"
      },
      "variant:medium": {
        "color": "light-dark(oklch(0.561 0.18 78), oklch(0.731 0.145 78))",
        "backgroundColor": "color-mix(in oklch, light-dark(oklch(0.561 0.18 78), oklch(0.731 0.145 78)) 12%, var(--color-background-body))",
        "borderColor": "color-mix(in oklch, light-dark(oklch(0.561 0.18 78), oklch(0.731 0.145 78)) 40%, var(--color-background-body))"
      },
      "variant:low": {
        "color": "light-dark(oklch(0.581 0.18 250), oklch(0.631 0.145 250))",
        "backgroundColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 250), oklch(0.631 0.145 250)) 12%, var(--color-background-body))",
        "borderColor": "color-mix(in oklch, light-dark(oklch(0.581 0.18 250), oklch(0.631 0.145 250)) 40%, var(--color-background-body))"
      }
    }
  },
});
