/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/laitTheme.ts
 * Command: astryx theme build src/theme/laitTheme.ts --out src/theme/lait.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Button' {
  interface ButtonVariantMap {
    'active': true;
    'danger': true;
  }
}

declare module '@astryxdesign/core/StatusDot' {
  interface StatusDotVariantMap {
    'urgent': true;
    'high': true;
    'medium': true;
    'low': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'urgent': true;
    'high': true;
    'medium': true;
    'low': true;
  }
}
