import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

/**
 * The client builds straight into `products/issues-app/assets/web`, which is
 * **committed** as part of the independently shipped Issues release.
 *
 * The generic host never embeds these bytes. Bootstrap installers and the
 * World publication workflow copy them into the Issues release beside its
 * runner and signed declaration; later Issues updates replace that release on
 * their own cadence. Keeping generated bytes out of `src/` makes the package
 * ownership visible while preserving a Rust-only host build.
 *
 * The tradeoff is honest: build output in git, kept fresh by `npm run build` and
 * guarded by CI diffing a rebuild.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
  build: {
    outDir: "../products/issues-app/assets/web",
    emptyOutDir: true,
    // No hashed filenames: the bundle is committed, so stable names keep the diff
    // legible and stop every rebuild from churning the tree with new files. The
    // World release is versioned as a whole, so cache-busting names add nothing.
    rollupOptions: {
      output: {
        entryFileNames: "app.js",
        chunkFileNames: "[name].js",
        assetFileNames: "[name][extname]",
      },
    },
  },
});
