import { fileURLToPath } from "node:url";

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

/** Absolute path to a file in the built `porthole` wasm-pack package. */
const porthole = (file: string) =>
  fileURLToPath(new URL(`../crates/porthole/pkg/${file}`, import.meta.url));

/**
 * The client builds straight into `products/issues-app/assets/web`, which is
 * **committed** as part of the independently shipped Issues release.
 *
 * The generic host never embeds these bytes. Bootstrap installers and the
 * World publication workflow copy them into the Issues release beside its
 * runner and signed declaration; later Issues updates replace that release on
 * their own cadence. Keeping generated bytes out of `src/` makes the package
 * ownership visible while preserving a Rust-only host build.
 *
 * The tradeoff is honest: build output in git, kept fresh by `npm run build` and
 * guarded by CI diffing a rebuild.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
  // Resolve the shippable in-tab engine's small JS glue (`crates/porthole`,
  // built by wasm-pack --target web) for `import init, { boot } from "porthole"`.
  // Only the glue is bundled; the 14 MiB engine wasm and the 39 MiB runner are
  // BOTH fetched at runtime (same-origin in dev, the signed channel in a
  // release), so neither weighs down the committed bundle.
  resolve: {
    alias: [{ find: /^porthole$/, replacement: porthole("porthole.js") }],
  },
  // The engine Worker is spawned as an ES module (`new Worker(url, {type:
  // "module"})`); flat, unhashed chunk names keep it inside the release's
  // committed, CI-diffed naming scheme instead of a hashed assets/ path.
  worker: {
    format: "es",
    rollupOptions: {
      output: {
        entryFileNames: "[name].js",
        chunkFileNames: "[name].js",
        assetFileNames: "[name][extname]",
      },
    },
  },
  build: {
    outDir: "../products/issues-app/assets/web",
    emptyOutDir: true,
    // No hashed filenames: the bundle is committed, so stable names keep the diff
    // legible and stop every rebuild from churning the tree with new files. The
    // World release is versioned as a whole, so cache-busting names add nothing.
    rollupOptions: {
      output: {
        entryFileNames: "app.js",
        chunkFileNames: "[name].js",
        assetFileNames: "[name][extname]",
      },
    },
  },
});
