// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1979473582;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__current_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "current",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::current())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__dispatch_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "dispatch",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_action = <crate::api::ActionRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::dispatch(api_action))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__start_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_state_root = <Option<String>>::sse_decode(&mut deserializer);
            let api_sidecar = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::start(api_state_root, api_sidecar)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__watch_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "watch",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::ClientView,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::watch(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::ClientView, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::ActionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::ActionRequest::Refresh;
            }
            1 => {
                let mut var_orbit = <String>::sse_decode(deserializer);
                let mut var_entryPath = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::Open {
                    orbit: var_orbit,
                    entry_path: var_entryPath,
                };
            }
            2 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::StartDevice { id: var_id };
            }
            3 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::StopDevice { id: var_id };
            }
            4 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::RestartDevice { id: var_id };
            }
            5 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::ForceStopDevice { id: var_id };
            }
            6 => {
                return crate::api::ActionRequest::StopAllOwned;
            }
            7 => {
                let mut var_id = <String>::sse_decode(deserializer);
                let mut var_deleteData = <bool>::sse_decode(deserializer);
                return crate::api::ActionRequest::RemoveDevice {
                    id: var_id,
                    delete_data: var_deleteData,
                };
            }
            8 => {
                let mut var_orbit = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::ReadSpace { orbit: var_orbit };
            }
            9 => {
                return crate::api::ActionRequest::StartHead;
            }
            10 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::StopHead { id: var_id };
            }
            11 => {
                let mut var_space = <String>::sse_decode(deserializer);
                return crate::api::ActionRequest::ForgetOrbit { space: var_space };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::ClientView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_loading = <bool>::sse_decode(deserializer);
        let mut var_stale = <Option<crate::api::Staleness>>::sse_decode(deserializer);
        let mut var_library_ = <Option<Vec<crate::api::LibraryRow>>>::sse_decode(deserializer);
        let mut var_host = <Option<crate::api::HostFacts>>::sse_decode(deserializer);
        let mut var_heads = <Vec<crate::api::HeadRow>>::sse_decode(deserializer);
        let mut var_devices = <Vec<crate::api::DeviceRow>>::sse_decode(deserializer);
        let mut var_storage = <Vec<crate::api::StorageRow>>::sse_decode(deserializer);
        let mut var_orbits = <Vec<crate::api::OrbitRow>>::sse_decode(deserializer);
        let mut var_space = <Option<crate::api::SpaceRow>>::sse_decode(deserializer);
        let mut var_notices = <Vec<crate::api::NoticeRow>>::sse_decode(deserializer);
        let mut var_failures = <Vec<crate::api::FailureRow>>::sse_decode(deserializer);
        let mut var_inFlight = <Vec<String>>::sse_decode(deserializer);
        return crate::api::ClientView {
            loading: var_loading,
            stale: var_stale,
            library: var_library_,
            host: var_host,
            heads: var_heads,
            devices: var_devices,
            storage: var_storage,
            orbits: var_orbits,
            space: var_space,
            notices: var_notices,
            failures: var_failures,
            in_flight: var_inFlight,
        };
    }
}

impl SseDecode for crate::api::DeviceRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_state = <String>::sse_decode(deserializer);
        let mut var_owned = <bool>::sse_decode(deserializer);
        let mut var_degraded = <Option<String>>::sse_decode(deserializer);
        let mut var_home = <String>::sse_decode(deserializer);
        let mut var_pid = <Option<u32>>::sse_decode(deserializer);
        let mut var_canForceStop = <bool>::sse_decode(deserializer);
        let mut var_lastError = <Option<String>>::sse_decode(deserializer);
        return crate::api::DeviceRow {
            id: var_id,
            label: var_label,
            state: var_state,
            owned: var_owned,
            degraded: var_degraded,
            home: var_home,
            pid: var_pid,
            can_force_stop: var_canForceStop,
            last_error: var_lastError,
        };
    }
}

impl SseDecode for crate::api::DiagnosisRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_gates = <Vec<crate::api::GateRow>>::sse_decode(deserializer);
        let mut var_blockedOn = <Option<String>>::sse_decode(deserializer);
        let mut var_summary = <String>::sse_decode(deserializer);
        return crate::api::DiagnosisRow {
            gates: var_gates,
            blocked_on: var_blockedOn,
            summary: var_summary,
        };
    }
}

impl SseDecode for crate::api::FailureRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_what = <String>::sse_decode(deserializer);
        let mut var_error = <String>::sse_decode(deserializer);
        let mut var_retryable = <bool>::sse_decode(deserializer);
        return crate::api::FailureRow {
            what: var_what,
            error: var_error,
            retryable: var_retryable,
        };
    }
}

impl SseDecode for crate::api::GateRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_state = <crate::api::GateState>::sse_decode(deserializer);
        let mut var_detail = <String>::sse_decode(deserializer);
        return crate::api::GateRow {
            id: var_id,
            label: var_label,
            state: var_state,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::GateState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::GateState::Pass,
            1 => crate::api::GateState::Wait,
            2 => crate::api::GateState::Fail,
            3 => crate::api::GateState::Warn,
            4 => crate::api::GateState::Skip,
            _ => unreachable!("Invalid variant for GateState: {}", inner),
        };
    }
}

impl SseDecode for crate::api::HeadRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_orbit = <Option<String>>::sse_decode(deserializer);
        let mut var_origin = <Option<String>>::sse_decode(deserializer);
        let mut var_owned = <bool>::sse_decode(deserializer);
        return crate::api::HeadRow {
            id: var_id,
            kind: var_kind,
            orbit: var_orbit,
            origin: var_origin,
            owned: var_owned,
        };
    }
}

impl SseDecode for crate::api::HostFacts {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_version = <String>::sse_decode(deserializer);
        let mut var_identityHome = <String>::sse_decode(deserializer);
        let mut var_spacesRoot = <String>::sse_decode(deserializer);
        let mut var_orbitCount = <u32>::sse_decode(deserializer);
        return crate::api::HostFacts {
            version: var_version,
            identity_home: var_identityHome,
            spaces_root: var_spacesRoot,
            orbit_count: var_orbitCount,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::LibraryRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_key = <String>::sse_decode(deserializer);
        let mut var_orbit = <String>::sse_decode(deserializer);
        let mut var_space = <String>::sse_decode(deserializer);
        let mut var_worldMount = <String>::sse_decode(deserializer);
        let mut var_displayName = <Option<String>>::sse_decode(deserializer);
        let mut var_placement = <crate::api::PlacementView>::sse_decode(deserializer);
        let mut var_opensAt = <Option<String>>::sse_decode(deserializer);
        let mut var_unopenable = <Option<crate::api::Unopenable>>::sse_decode(deserializer);
        let mut var_lastOpened = <Option<u64>>::sse_decode(deserializer);
        let mut var_store = <Option<String>>::sse_decode(deserializer);
        let mut var_tagline = <Option<String>>::sse_decode(deserializer);
        let mut var_accent = <Option<u32>>::sse_decode(deserializer);
        let mut var_routes = <Vec<crate::api::RouteRow>>::sse_decode(deserializer);
        return crate::api::LibraryRow {
            key: var_key,
            orbit: var_orbit,
            space: var_space,
            world_mount: var_worldMount,
            display_name: var_displayName,
            placement: var_placement,
            opens_at: var_opensAt,
            unopenable: var_unopenable,
            last_opened: var_lastOpened,
            store: var_store,
            tagline: var_tagline,
            accent: var_accent,
            routes: var_routes,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::DeviceRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::DeviceRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FailureRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FailureRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::GateRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::GateRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::HeadRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::HeadRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::LibraryRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::LibraryRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::MemberRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::MemberRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::NoticeRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::NoticeRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::OrbitRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::OrbitRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::RouteRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::RouteRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::StorageRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::StorageRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::MemberRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_nick = <Option<String>>::sse_decode(deserializer);
        let mut var_admin = <bool>::sse_decode(deserializer);
        return crate::api::MemberRow {
            id: var_id,
            nick: var_nick,
            admin: var_admin,
        };
    }
}

impl SseDecode for crate::api::Missing {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::Missing::NotPlaced,
            1 => crate::api::Missing::Unreachable,
            _ => unreachable!("Invalid variant for Missing: {}", inner),
        };
    }
}

impl SseDecode for crate::api::NoticeRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_said = <String>::sse_decode(deserializer);
        let mut var_launched = <Option<String>>::sse_decode(deserializer);
        return crate::api::NoticeRow {
            said: var_said,
            launched: var_launched,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::DiagnosisRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::DiagnosisRow>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::HostFacts> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::HostFacts>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::Missing> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::Missing>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::SpaceRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::SpaceRow>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::Staleness> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::Staleness>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::Unopenable> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::Unopenable>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<crate::api::LibraryRow>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<crate::api::LibraryRow>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::OrbitRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_space = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_lastOpened = <Option<u64>>::sse_decode(deserializer);
        return crate::api::OrbitRow {
            space: var_space,
            name: var_name,
            path: var_path,
            last_opened: var_lastOpened,
        };
    }
}

impl SseDecode for crate::api::PlacementView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::PlacementView::Placed,
            1 => crate::api::PlacementView::Vacant,
            2 => crate::api::PlacementView::Unknown,
            _ => unreachable!("Invalid variant for PlacementView: {}", inner),
        };
    }
}

impl SseDecode for crate::api::RouteRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_path = <String>::sse_decode(deserializer);
        return crate::api::RouteRow {
            label: var_label,
            path: var_path,
        };
    }
}

impl SseDecode for crate::api::SpaceRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_space = <String>::sse_decode(deserializer);
        let mut var_whoami = <Option<String>>::sse_decode(deserializer);
        let mut var_admin = <bool>::sse_decode(deserializer);
        let mut var_members = <Vec<crate::api::MemberRow>>::sse_decode(deserializer);
        let mut var_devices = <Vec<String>>::sse_decode(deserializer);
        let mut var_diagnosis = <Option<crate::api::DiagnosisRow>>::sse_decode(deserializer);
        return crate::api::SpaceRow {
            space: var_space,
            whoami: var_whoami,
            admin: var_admin,
            members: var_members,
            devices: var_devices,
            diagnosis: var_diagnosis,
        };
    }
}

impl SseDecode for crate::api::Staleness {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::Staleness::NeverLoaded;
            }
            1 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::Staleness::Signalled(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::StorageRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_orbit = <String>::sse_decode(deserializer);
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_bytesOnDisk = <Option<u64>>::sse_decode(deserializer);
        let mut var_objectCount = <Option<u64>>::sse_decode(deserializer);
        let mut var_lastVerifiedMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_missing = <Option<crate::api::Missing>>::sse_decode(deserializer);
        return crate::api::StorageRow {
            orbit: var_orbit,
            name: var_name,
            bytes_on_disk: var_bytesOnDisk,
            object_count: var_objectCount,
            last_verified_ms: var_lastVerifiedMs,
            missing: var_missing,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::Unopenable {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::Unopenable::Unhosted,
            1 => crate::api::Unopenable::Undeclared,
            _ => unreachable!("Invalid variant for Unopenable: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        4 => wire__crate__api__watch_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__current_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__dispatch_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__start_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ActionRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::ActionRequest::Refresh => [0.into_dart()].into_dart(),
            crate::api::ActionRequest::Open { orbit, entry_path } => [
                1.into_dart(),
                orbit.into_into_dart().into_dart(),
                entry_path.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::ActionRequest::StartDevice { id } => {
                [2.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::StopDevice { id } => {
                [3.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::RestartDevice { id } => {
                [4.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::ForceStopDevice { id } => {
                [5.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::StopAllOwned => [6.into_dart()].into_dart(),
            crate::api::ActionRequest::RemoveDevice { id, delete_data } => [
                7.into_dart(),
                id.into_into_dart().into_dart(),
                delete_data.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::ActionRequest::ReadSpace { orbit } => {
                [8.into_dart(), orbit.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::StartHead => [9.into_dart()].into_dart(),
            crate::api::ActionRequest::StopHead { id } => {
                [10.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::ActionRequest::ForgetOrbit { space } => {
                [11.into_dart(), space.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ActionRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ActionRequest> for crate::api::ActionRequest {
    fn into_into_dart(self) -> crate::api::ActionRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ClientView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.loading.into_into_dart().into_dart(),
            self.stale.into_into_dart().into_dart(),
            self.library.into_into_dart().into_dart(),
            self.host.into_into_dart().into_dart(),
            self.heads.into_into_dart().into_dart(),
            self.devices.into_into_dart().into_dart(),
            self.storage.into_into_dart().into_dart(),
            self.orbits.into_into_dart().into_dart(),
            self.space.into_into_dart().into_dart(),
            self.notices.into_into_dart().into_dart(),
            self.failures.into_into_dart().into_dart(),
            self.in_flight.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ClientView {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ClientView> for crate::api::ClientView {
    fn into_into_dart(self) -> crate::api::ClientView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DeviceRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.owned.into_into_dart().into_dart(),
            self.degraded.into_into_dart().into_dart(),
            self.home.into_into_dart().into_dart(),
            self.pid.into_into_dart().into_dart(),
            self.can_force_stop.into_into_dart().into_dart(),
            self.last_error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DeviceRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DeviceRow> for crate::api::DeviceRow {
    fn into_into_dart(self) -> crate::api::DeviceRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DiagnosisRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.gates.into_into_dart().into_dart(),
            self.blocked_on.into_into_dart().into_dart(),
            self.summary.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DiagnosisRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DiagnosisRow> for crate::api::DiagnosisRow {
    fn into_into_dart(self) -> crate::api::DiagnosisRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FailureRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.what.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
            self.retryable.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FailureRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FailureRow> for crate::api::FailureRow {
    fn into_into_dart(self) -> crate::api::FailureRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GateRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GateRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GateRow> for crate::api::GateRow {
    fn into_into_dart(self) -> crate::api::GateRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::GateState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Pass => 0.into_dart(),
            Self::Wait => 1.into_dart(),
            Self::Fail => 2.into_dart(),
            Self::Warn => 3.into_dart(),
            Self::Skip => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::GateState {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::GateState> for crate::api::GateState {
    fn into_into_dart(self) -> crate::api::GateState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::HeadRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.orbit.into_into_dart().into_dart(),
            self.origin.into_into_dart().into_dart(),
            self.owned.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::HeadRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::HeadRow> for crate::api::HeadRow {
    fn into_into_dart(self) -> crate::api::HeadRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::HostFacts {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.version.into_into_dart().into_dart(),
            self.identity_home.into_into_dart().into_dart(),
            self.spaces_root.into_into_dart().into_dart(),
            self.orbit_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::HostFacts {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::HostFacts> for crate::api::HostFacts {
    fn into_into_dart(self) -> crate::api::HostFacts {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::LibraryRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.key.into_into_dart().into_dart(),
            self.orbit.into_into_dart().into_dart(),
            self.space.into_into_dart().into_dart(),
            self.world_mount.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.placement.into_into_dart().into_dart(),
            self.opens_at.into_into_dart().into_dart(),
            self.unopenable.into_into_dart().into_dart(),
            self.last_opened.into_into_dart().into_dart(),
            self.store.into_into_dart().into_dart(),
            self.tagline.into_into_dart().into_dart(),
            self.accent.into_into_dart().into_dart(),
            self.routes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::LibraryRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::LibraryRow> for crate::api::LibraryRow {
    fn into_into_dart(self) -> crate::api::LibraryRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MemberRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.nick.into_into_dart().into_dart(),
            self.admin.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::MemberRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MemberRow> for crate::api::MemberRow {
    fn into_into_dart(self) -> crate::api::MemberRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::Missing {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::NotPlaced => 0.into_dart(),
            Self::Unreachable => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::Missing {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::Missing> for crate::api::Missing {
    fn into_into_dart(self) -> crate::api::Missing {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::NoticeRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.said.into_into_dart().into_dart(),
            self.launched.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NoticeRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NoticeRow> for crate::api::NoticeRow {
    fn into_into_dart(self) -> crate::api::NoticeRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::OrbitRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.space.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.last_opened.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::OrbitRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::OrbitRow> for crate::api::OrbitRow {
    fn into_into_dart(self) -> crate::api::OrbitRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PlacementView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Placed => 0.into_dart(),
            Self::Vacant => 1.into_dart(),
            Self::Unknown => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::PlacementView {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PlacementView> for crate::api::PlacementView {
    fn into_into_dart(self) -> crate::api::PlacementView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::RouteRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.label.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::RouteRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::RouteRow> for crate::api::RouteRow {
    fn into_into_dart(self) -> crate::api::RouteRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SpaceRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.space.into_into_dart().into_dart(),
            self.whoami.into_into_dart().into_dart(),
            self.admin.into_into_dart().into_dart(),
            self.members.into_into_dart().into_dart(),
            self.devices.into_into_dart().into_dart(),
            self.diagnosis.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SpaceRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SpaceRow> for crate::api::SpaceRow {
    fn into_into_dart(self) -> crate::api::SpaceRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::Staleness {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::Staleness::NeverLoaded => [0.into_dart()].into_dart(),
            crate::api::Staleness::Signalled(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::Staleness {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::Staleness> for crate::api::Staleness {
    fn into_into_dart(self) -> crate::api::Staleness {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::StorageRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.orbit.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.bytes_on_disk.into_into_dart().into_dart(),
            self.object_count.into_into_dart().into_dart(),
            self.last_verified_ms.into_into_dart().into_dart(),
            self.missing.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::StorageRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::StorageRow> for crate::api::StorageRow {
    fn into_into_dart(self) -> crate::api::StorageRow {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::Unopenable {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Unhosted => 0.into_dart(),
            Self::Undeclared => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::Unopenable {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::Unopenable> for crate::api::Unopenable {
    fn into_into_dart(self) -> crate::api::Unopenable {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::ClientView, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::ActionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::ActionRequest::Refresh => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::ActionRequest::Open { orbit, entry_path } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(orbit, serializer);
                <String>::sse_encode(entry_path, serializer);
            }
            crate::api::ActionRequest::StartDevice { id } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::ActionRequest::StopDevice { id } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::ActionRequest::RestartDevice { id } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::ActionRequest::ForceStopDevice { id } => {
                <i32>::sse_encode(5, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::ActionRequest::StopAllOwned => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::ActionRequest::RemoveDevice { id, delete_data } => {
                <i32>::sse_encode(7, serializer);
                <String>::sse_encode(id, serializer);
                <bool>::sse_encode(delete_data, serializer);
            }
            crate::api::ActionRequest::ReadSpace { orbit } => {
                <i32>::sse_encode(8, serializer);
                <String>::sse_encode(orbit, serializer);
            }
            crate::api::ActionRequest::StartHead => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::ActionRequest::StopHead { id } => {
                <i32>::sse_encode(10, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::ActionRequest::ForgetOrbit { space } => {
                <i32>::sse_encode(11, serializer);
                <String>::sse_encode(space, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::ClientView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.loading, serializer);
        <Option<crate::api::Staleness>>::sse_encode(self.stale, serializer);
        <Option<Vec<crate::api::LibraryRow>>>::sse_encode(self.library, serializer);
        <Option<crate::api::HostFacts>>::sse_encode(self.host, serializer);
        <Vec<crate::api::HeadRow>>::sse_encode(self.heads, serializer);
        <Vec<crate::api::DeviceRow>>::sse_encode(self.devices, serializer);
        <Vec<crate::api::StorageRow>>::sse_encode(self.storage, serializer);
        <Vec<crate::api::OrbitRow>>::sse_encode(self.orbits, serializer);
        <Option<crate::api::SpaceRow>>::sse_encode(self.space, serializer);
        <Vec<crate::api::NoticeRow>>::sse_encode(self.notices, serializer);
        <Vec<crate::api::FailureRow>>::sse_encode(self.failures, serializer);
        <Vec<String>>::sse_encode(self.in_flight, serializer);
    }
}

impl SseEncode for crate::api::DeviceRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.state, serializer);
        <bool>::sse_encode(self.owned, serializer);
        <Option<String>>::sse_encode(self.degraded, serializer);
        <String>::sse_encode(self.home, serializer);
        <Option<u32>>::sse_encode(self.pid, serializer);
        <bool>::sse_encode(self.can_force_stop, serializer);
        <Option<String>>::sse_encode(self.last_error, serializer);
    }
}

impl SseEncode for crate::api::DiagnosisRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::GateRow>>::sse_encode(self.gates, serializer);
        <Option<String>>::sse_encode(self.blocked_on, serializer);
        <String>::sse_encode(self.summary, serializer);
    }
}

impl SseEncode for crate::api::FailureRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.what, serializer);
        <String>::sse_encode(self.error, serializer);
        <bool>::sse_encode(self.retryable, serializer);
    }
}

impl SseEncode for crate::api::GateRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.label, serializer);
        <crate::api::GateState>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::GateState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::GateState::Pass => 0,
                crate::api::GateState::Wait => 1,
                crate::api::GateState::Fail => 2,
                crate::api::GateState::Warn => 3,
                crate::api::GateState::Skip => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::HeadRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.orbit, serializer);
        <Option<String>>::sse_encode(self.origin, serializer);
        <bool>::sse_encode(self.owned, serializer);
    }
}

impl SseEncode for crate::api::HostFacts {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.version, serializer);
        <String>::sse_encode(self.identity_home, serializer);
        <String>::sse_encode(self.spaces_root, serializer);
        <u32>::sse_encode(self.orbit_count, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::LibraryRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.key, serializer);
        <String>::sse_encode(self.orbit, serializer);
        <String>::sse_encode(self.space, serializer);
        <String>::sse_encode(self.world_mount, serializer);
        <Option<String>>::sse_encode(self.display_name, serializer);
        <crate::api::PlacementView>::sse_encode(self.placement, serializer);
        <Option<String>>::sse_encode(self.opens_at, serializer);
        <Option<crate::api::Unopenable>>::sse_encode(self.unopenable, serializer);
        <Option<u64>>::sse_encode(self.last_opened, serializer);
        <Option<String>>::sse_encode(self.store, serializer);
        <Option<String>>::sse_encode(self.tagline, serializer);
        <Option<u32>>::sse_encode(self.accent, serializer);
        <Vec<crate::api::RouteRow>>::sse_encode(self.routes, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::DeviceRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::DeviceRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FailureRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FailureRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::GateRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::GateRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::HeadRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::HeadRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::LibraryRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::LibraryRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::MemberRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::MemberRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::NoticeRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::NoticeRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::OrbitRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::OrbitRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::RouteRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::RouteRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::StorageRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::StorageRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::MemberRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <Option<String>>::sse_encode(self.nick, serializer);
        <bool>::sse_encode(self.admin, serializer);
    }
}

impl SseEncode for crate::api::Missing {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::Missing::NotPlaced => 0,
                crate::api::Missing::Unreachable => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::NoticeRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.said, serializer);
        <Option<String>>::sse_encode(self.launched, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::DiagnosisRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::DiagnosisRow>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::HostFacts> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::HostFacts>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::Missing> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::Missing>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::SpaceRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::SpaceRow>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::Staleness> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::Staleness>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::Unopenable> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::Unopenable>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<crate::api::LibraryRow>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<crate::api::LibraryRow>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::OrbitRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.space, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.path, serializer);
        <Option<u64>>::sse_encode(self.last_opened, serializer);
    }
}

impl SseEncode for crate::api::PlacementView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::PlacementView::Placed => 0,
                crate::api::PlacementView::Vacant => 1,
                crate::api::PlacementView::Unknown => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::RouteRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.path, serializer);
    }
}

impl SseEncode for crate::api::SpaceRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.space, serializer);
        <Option<String>>::sse_encode(self.whoami, serializer);
        <bool>::sse_encode(self.admin, serializer);
        <Vec<crate::api::MemberRow>>::sse_encode(self.members, serializer);
        <Vec<String>>::sse_encode(self.devices, serializer);
        <Option<crate::api::DiagnosisRow>>::sse_encode(self.diagnosis, serializer);
    }
}

impl SseEncode for crate::api::Staleness {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::Staleness::NeverLoaded => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::Staleness::Signalled(field0) => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::StorageRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.orbit, serializer);
        <Option<String>>::sse_encode(self.name, serializer);
        <Option<u64>>::sse_encode(self.bytes_on_disk, serializer);
        <Option<u64>>::sse_encode(self.object_count, serializer);
        <Option<u64>>::sse_encode(self.last_verified_ms, serializer);
        <Option<crate::api::Missing>>::sse_encode(self.missing, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::Unopenable {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::Unopenable::Unhosted => 0,
                crate::api::Unopenable::Undeclared => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
