//! Astrolabe — the local client through which a person reaches the Worlds their
//! device serves.
//!
//! The reference shape is the Steam client: a library, a launcher, an identity
//! and a social client that never draws the game. `products/issues` ships its
//! own head and stays the authority on its own presentation; `Open` here is a
//! handoff, not a render.
//!
//! ## What is where
//!
//! - [`client`] is the reach: the supervisor library this crate embeds, and the
//!   host, Space and World planes it speaks. It draws nothing, which is what
//!   lets every rule in it be tested without a window.
//! - [`model`] is the App-owned state. One entity consumes the ordered
//!   `ClientSignal` stream and is the *only* model of client state — nothing
//!   mirrors it and nothing derives a parallel copy.
//! - [`api`] is the boundary: the whole of what the Dart interface can know,
//!   and the whole of what it can ask for.
//!
//! ## There is a boundary now, and it is the only one
//!
//! Revision 7 of the Plan moves the interface to Flutter, which returns the
//! generated binding revisions 5 and 6 removed. What was bought is a component
//! set this project already owns; what it costs is written down as five rules
//! and each one is a gate rather than a habit. The important one is unchanged
//! in substance: [`model::App`] is still the only model of client state. Dart
//! receives whole immutable projections of it and holds nothing but drafts.
//!
//! [`ui`] is the retiring egui interface. It is behind the `egui-ui` feature
//! and is not built by default.

/// Generated by the bridge codegen and checked in. Never edited by hand: it is
/// regenerated from [`api`], and CI fails when the two disagree.
#[rustfmt::skip]
mod frb_generated;

pub mod api;
pub mod browser;
pub mod client;
pub mod lifecycle;
pub mod link;
pub mod model;
pub mod notify;
pub mod runtime;
pub mod sidecar;
pub mod single_instance;
pub mod tray;
#[cfg(feature = "egui-ui")]
pub mod ui;

pub use client::{Client, ClientError, ClientResult, Config};
pub use model::App;
