#!/usr/bin/env node
// Stamp the Roku channel with a build tag and bump its manifest build number.
//
//   node scripts/stamp.mjs            # writes source/Build.brs, bumps manifest
//   node scripts/stamp.mjs --restore  # puts both back from git
//
// The tag is `astrolabe-roku/<major>.<minor>.<build>+<sha>[-dirty]`, where
// the sha is the repository HEAD and dirty means receivers/roku has
// uncommitted changes. It is what the receiver reports in every health
// report and prints on its console at launch.
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(root, "manifest");
const buildPath = join(root, "source", "Build.brs");

function git(args) {
  try {
    return execSync(`git ${args}`, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}

const DEFAULT_BUILD = [
  "' GENERATED by scripts/stamp.mjs at package time; this committed form is the",
  "' unstamped default. The tag names the channel build the coordinator's health",
  "' report and the console will show, so \"which receiver is this\" is answered",
  "' by a string, never by a line number.",
  "function AstrolabeBuild() as string",
  '    return "astrolabe-roku/dev"',
  "end function",
  "",
].join("\n");

if (process.argv.includes("--restore")) {
  git("checkout -- manifest");
  // Build.brs is restored from git when it is tracked, and to its default
  // otherwise, so a restore never fails on a tree where it is new.
  if (git("ls-files --error-unmatch source/Build.brs") !== "") {
    git("checkout -- source/Build.brs");
  } else {
    writeFileSync(buildPath, DEFAULT_BUILD);
  }
  console.log("restored manifest and source/Build.brs");
  process.exit(0);
}

const manifest = readFileSync(manifestPath, "utf8");
const field = (name) => {
  const match = manifest.match(new RegExp(`^${name}=(.*)$`, "m"));
  return match ? match[1].trim() : "";
};
const build = String(Number.parseInt(field("build_version") || "0", 10) + 1).padStart(5, "0");
const stamped = manifest.replace(/^build_version=.*$/m, `build_version=${build}`);
writeFileSync(manifestPath, stamped);

const sha = git("rev-parse --short=8 HEAD") || "nogit";
const dirty = git("status --porcelain --untracked-files=no -- .") !== "";
const tag = `astrolabe-roku/${field("major_version")}.${field("minor_version")}.${Number.parseInt(build, 10)}+${sha}${dirty ? "-dirty" : ""}`;
if (tag.length > 64) {
  console.error(`build tag exceeds the protocol's 64 bytes: ${tag}`);
  process.exit(1);
}
writeFileSync(
  buildPath,
  [
    "' GENERATED by scripts/stamp.mjs — do not edit; `node scripts/stamp.mjs --restore` puts the default back.",
    "function AstrolabeBuild() as string",
    `    return "${tag}"`,
    "end function",
    "",
  ].join("\n"),
);
console.log(tag);
