/**
 * Generates the colour tokens in `src/tokens.generated.css`.
 *
 * WHY THIS EXISTS. The palette used to be twenty independently chosen hex
 * pairs. Nothing structural made two semantic colours read at the same weight —
 * it held only for as long as someone had eyeballed it, and measurement said it
 * had already stopped holding: in dark mode the four accent families sat at
 * OKLCH lightness 0.571 (accent), 0.677 (danger), 0.695 (ok) and 0.720 (warn).
 * A 0.149 spread is not a palette, it is four colours that happen to coexist.
 *
 * So colour is DERIVED now, like every other axis. A seed contributes its hue;
 * lightness and chroma come from shared curves. Two families differ in hue and
 * in nothing else, which is what makes them equal weight by construction rather
 * than by inspection.
 *
 * WHY THE NEUTRALS DID NOT MOVE. Measuring the existing greys showed they were
 * already one hue-consistent ramp — 285.8-286.4 across every step, both themes.
 * The L curve in `palette.mjs` IS that measurement, so the greys this emits are
 * the greys we had. The generator earns its keep on the accent families, not on
 * them.
 *
 * WHY `oklch()` RATHER THAN HEX. The browser gamut-maps out-of-range values by
 * reducing chroma while holding hue, which is exactly what a hand-rolled clamp
 * would have to reimplement — and it does it per-display rather than for sRGB
 * only. Emitting hex would throw that away.
 *
 * WHERE THE CURVES LIVE. `tool/palette.mjs` — this file is one projection of
 * them onto Tailwind's `@theme` block, and `generate-astryx-theme.mjs` is
 * another onto Astryx's token vocabulary. Neither owns the palette.
 *
 * Run with `npm run tokens`. The output is committed; `designSystem.test.ts`
 * re-runs this and fails if the committed file has drifted, so the source of
 * truth cannot silently become the generated file.
 */

import { ACCENT_FG, familyPairs, neutralPairs, priorityPairs } from "./palette.mjs";

const lines = [];

/** `light-dark()` reads `color-scheme`, so one property flips the whole theme
 *  and neither palette has to be restated. */
const emit = (name, [light, dark]) =>
  lines.push(`  --color-${name}: light-dark(${light}, ${dark});`);

// Neutrals, by role.
for (const [role, pair] of Object.entries(neutralPairs())) {
  emit(role === "lineStrong" ? "line-strong" : role, pair);
}

// The four accent families: same curve, different hue. That is the whole point.
for (const [family, pair] of Object.entries(familyPairs())) emit(family, pair);

// Priority glyphs are the clearest case for the shared curve: four hues that
// have to read as one family at a glance, spanning the same range as the
// semantic colours above.
for (const [name, pair] of Object.entries(priorityPairs())) emit(name, pair);

const out = `/* GENERATED by tool/generate-tokens.mjs — do not edit.
 *
 * Colour is derived, not authored: a seed gives a hue, and lightness and chroma
 * come from shared curves, so two families differ in hue and nothing else. Edit
 * the seeds or the curves in the generator and run \`npm run tokens\`.
 *
 * \`--color-accent-fg\` is not here: it is the one colour that is a decision
 * rather than a position on a ramp — white on a solid, chosen for contrast. */
@theme {
${lines.join("\n")}
  --color-accent-fg: ${ACCENT_FG};
}
`;

const path = new URL("../src/tokens.generated.css", import.meta.url);
const { writeFileSync, readFileSync, existsSync } = await import("node:fs");

if (process.argv.includes("--check")) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== out) {
    console.error("tokens.generated.css is stale — run `npm run tokens`");
    process.exit(1);
  }
  console.log("tokens.generated.css is up to date");
} else {
  writeFileSync(path, out);
  console.log(`wrote ${lines.length + 1} colour tokens to src/tokens.generated.css`);
}
