// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `emit`, `empty`, `into_action`, `project`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Start the core. Idempotent: a second call is a no-op rather than a second
/// runtime, because two runtimes would be two supervisors of the same devices.
void start({String? stateRoot, String? sidecar}) =>
    Core.instance.api.crateApiStart(stateRoot: stateRoot, sidecar: sidecar);

/// Ask for something, and get back the view as it stands the instant it was
/// asked for.
///
/// Returning the view rather than nothing is what makes "a control is disabled
/// the moment it is clicked" true across a boundary. Waiting for the pump would
/// leave a live control for one round trip, which is long enough to press four
/// times and see three refusals.
ClientView dispatch({required ActionRequest action}) =>
    Core.instance.api.crateApiDispatch(action: action);

/// The view as it stands, for a surface that has just been built.
ClientView current() => Core.instance.api.crateApiCurrent();

/// Every view from now on.
Stream<ClientView> watch() => Core.instance.api.crateApiWatch();

@freezed
sealed class ActionRequest with _$ActionRequest {
  const ActionRequest._();

  /// Read this machine again.
  const factory ActionRequest.refresh() = ActionRequest_Refresh;

  /// Hand a World to the person's browser.
  const factory ActionRequest.open({
    required String orbit,
    required String entryPath,
  }) = ActionRequest_Open;
  const factory ActionRequest.startDevice({
    required String id,
  }) = ActionRequest_StartDevice;
  const factory ActionRequest.stopDevice({
    required String id,
  }) = ActionRequest_StopDevice;
  const factory ActionRequest.restartDevice({
    required String id,
  }) = ActionRequest_RestartDevice;
}

/// Everything a surface can draw, as of one moment.
///
/// Sent whole. There is no partial update and no patch protocol, because a
/// patch protocol is a second model in disguise: the receiver has to hold the
/// previous state and apply changes to it, and the moment it can do that it can
/// disagree with the sender.
class ClientView {
  /// Nothing has been read yet. Distinct from "read, and there is nothing".
  final bool loading;

  /// Why what is on screen may not be current. `None` is fresh.
  final Staleness? stale;

  /// `None` until the library has been read once — which is not the same as
  /// a device that serves nothing.
  final List<LibraryRow>? library_;
  final HostFacts? host;
  final List<HeadRow> heads;
  final List<DeviceRow> devices;
  final List<NoticeRow> notices;
  final List<FailureRow> failures;

  /// The keys of actions asked for and not yet answered. A control whose key
  /// is in here is disabled — on the frame the click happened, not on
  /// whichever later frame the answer arrives.
  final List<String> inFlight;

  const ClientView({
    required this.loading,
    this.stale,
    this.library_,
    this.host,
    required this.heads,
    required this.devices,
    required this.notices,
    required this.failures,
    required this.inFlight,
  });

  @override
  int get hashCode =>
      loading.hashCode ^
      stale.hashCode ^
      library_.hashCode ^
      host.hashCode ^
      heads.hashCode ^
      devices.hashCode ^
      notices.hashCode ^
      failures.hashCode ^
      inFlight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientView &&
          runtimeType == other.runtimeType &&
          loading == other.loading &&
          stale == other.stale &&
          library_ == other.library_ &&
          host == other.host &&
          heads == other.heads &&
          devices == other.devices &&
          notices == other.notices &&
          failures == other.failures &&
          inFlight == other.inFlight;
}

class DeviceRow {
  final String id;
  final String label;
  final String state;
  final bool owned;

  /// Whether observation of this device is degraded, and what went wrong.
  /// A sampling failure preserves the last good reading and says so; it is
  /// never drawn as "nothing there".
  final String? degraded;

  const DeviceRow({
    required this.id,
    required this.label,
    required this.state,
    required this.owned,
    this.degraded,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      state.hashCode ^
      owned.hashCode ^
      degraded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          owned == other.owned &&
          degraded == other.degraded;
}

class FailureRow {
  final String what;
  final String error;

  /// Whether asking again could plausibly work. A refusal is not a retry.
  final bool retryable;

  const FailureRow({
    required this.what,
    required this.error,
    required this.retryable,
  });

  @override
  int get hashCode => what.hashCode ^ error.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailureRow &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          error == other.error &&
          retryable == other.retryable;
}

class HeadRow {
  final String id;

  /// Browser or MCP.
  final String kind;

  /// The Orbit it is bound to. `None` is a browser head serving every Orbit
  /// its identity has.
  final String? orbit;

  /// The address, *without* the run credential its URL carries. A front page
  /// has no use for a credential — `Open` mints a single-use ticket of its
  /// own, which is what that ceremony is for.
  final String? origin;
  final bool owned;

  const HeadRow({
    required this.id,
    required this.kind,
    this.orbit,
    this.origin,
    required this.owned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      orbit.hashCode ^
      origin.hashCode ^
      owned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          orbit == other.orbit &&
          origin == other.origin &&
          owned == other.owned;
}

class HostFacts {
  final String version;
  final String identityHome;
  final String spacesRoot;
  final int orbitCount;

  const HostFacts({
    required this.version,
    required this.identityHome,
    required this.spacesRoot,
    required this.orbitCount,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      identityHome.hashCode ^
      spacesRoot.hashCode ^
      orbitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostFacts &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          identityHome == other.identityHome &&
          spacesRoot == other.spacesRoot &&
          orbitCount == other.orbitCount;
}

/// One row of the Library.
class LibraryRow {
  /// Stable across re-reads: the Orbit and the World in it. A selection
  /// keyed by index would silently follow whatever moved into that position.
  final String key;
  final String orbit;
  final String space;

  /// Empty when the row is the Space itself rather than a World in it.
  final String worldMount;

  /// `None` means nothing authoritative names it. Drawn as unnamed rather
  /// than as an id dressed up as a name.
  final String? displayName;
  final PlacementView placement;

  /// Where `Open` lands. `None` with [`Self::unopenable`] set is a row that
  /// cannot be opened at all.
  final String? opensAt;
  final Unopenable? unopenable;

  /// Wall-clock seconds. `None` is *never opened*, which a zero would
  /// silently turn into 1 January 1970.
  final BigInt? lastOpened;

  /// Where the Orbit's store lives, when the registry could be read.
  final String? store;

  const LibraryRow({
    required this.key,
    required this.orbit,
    required this.space,
    required this.worldMount,
    this.displayName,
    required this.placement,
    this.opensAt,
    this.unopenable,
    this.lastOpened,
    this.store,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      orbit.hashCode ^
      space.hashCode ^
      worldMount.hashCode ^
      displayName.hashCode ^
      placement.hashCode ^
      opensAt.hashCode ^
      unopenable.hashCode ^
      lastOpened.hashCode ^
      store.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRow &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          orbit == other.orbit &&
          space == other.space &&
          worldMount == other.worldMount &&
          displayName == other.displayName &&
          placement == other.placement &&
          opensAt == other.opensAt &&
          unopenable == other.unopenable &&
          lastOpened == other.lastOpened &&
          store == other.store;
}

class NoticeRow {
  final String said;

  /// Where a browser was sent, when that is what happened.
  final String? launched;

  const NoticeRow({
    required this.said,
    this.launched,
  });

  @override
  int get hashCode => said.hashCode ^ launched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoticeRow &&
          runtimeType == other.runtimeType &&
          said == other.said &&
          launched == other.launched;
}

/// Whether an Orbit is currently up. Three states, because "not running" and
/// "could not be asked" are different facts and only one is worth acting on.
///
/// Named apart from [`crate::client::library::Placement`] on purpose: the
/// codegen flattens type names across the crate and picks between collisions at
/// random, so a DTO that shared a name with a core type would be a coin toss
/// nobody could see land.
enum PlacementView {
  placed,
  vacant,
  unknown,
  ;
}

@freezed
sealed class Staleness with _$Staleness {
  const Staleness._();

  /// The first read has not landed.
  const factory Staleness.neverLoaded() = Staleness_NeverLoaded;

  /// The stream said so, and said why.
  const factory Staleness.signalled(
    String field0,
  ) = Staleness_Signalled;
}

/// Why a row cannot be opened. Two facts, not one.
enum Unopenable {
  /// This build hosts no head for that World.
  unhosted,

  /// The World is hosted here and has not declared where to open it.
  undeclared,
  ;
}
