// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `actor_address`, `attach_paths`, `attach_to`, `attach`, `authored_name_for`, `card_presence`, `emit`, `emit`, `empty`, `into_action`, `len`, `new`, `parse_agent_client`, `parse_mcp_scope`, `project`, `space_ref`, `view_of`, `world_people`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Core`, `Watchers`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `push`

/// Start the core, or attach to the one that is already running.
///
/// The first isolate boots the runtime. Later ones attach: same App, same
/// supervisor, a new view stream. A second *boot* — a start against a
/// different identity — is refused rather than spawning a second supervisor
/// of the same devices.
void start({String? stateRoot, String? sidecar}) =>
    Core.instance.api.crateApiStart(stateRoot: stateRoot, sidecar: sidecar);

/// Ask for something, and get back the view as it stands the instant it was
/// asked for.
///
/// Returning the view rather than nothing is what makes "a control is disabled
/// the moment it is clicked" true across a boundary. Waiting for the pump would
/// leave a live control for one round trip, which is long enough to press four
/// times and see three refusals.
ClientView dispatch({required ActionRequest action}) =>
    Core.instance.api.crateApiDispatch(action: action);

/// The artwork one installed World ships, by mount.
///
/// The one thing that crosses this boundary without being part of
/// [`ClientView`], and for a reason the view's own contract gives: the view is
/// pushed whole to every attached surface on every pump, and artwork is a
/// build constant that cannot change while the process runs. Riding in the view
/// it would be re-marshalled on every presence sample to repeat itself. Asked
/// for once and cached by the surface, it costs one copy for the life of the
/// window.
///
/// An unknown mount answers with no artwork, not an error.
WorldArtwork worldArtwork({required String mount}) =>
    Core.instance.api.crateApiWorldArtwork(mount: mount);

/// The view as it stands, for a surface that has just been built.
ClientView current() => Core.instance.api.crateApiCurrent();

/// Every view from now on, on this isolate.
///
/// Each attached isolate opens its own stream. Every live sink receives the
/// same [`ClientView`] on every pump; a sink that goes away is dropped and
/// does not stall the rest.
Stream<ClientView> watch() => Core.instance.api.crateApiWatch();

abstract class ViewPush {
  Future<bool> push({required ClientView view});
}

@freezed
sealed class ActionRequest with _$ActionRequest {
  const ActionRequest._();

  /// Read this machine again.
  const factory ActionRequest.refresh() = ActionRequest_Refresh;

  /// Hand a World to the person's browser.
  ///
  /// Names the mount as well as the path: a head serves one World, so opening
  /// says which rather than reaching for whichever head is up.
  const factory ActionRequest.open({
    required String world,
    required String entryPath,
  }) = ActionRequest_Open;

  /// Fetch this World's newest bundle now rather than at the next period.
  ///
  /// The daemon stages on a period measured in hours; a World is published
  /// in seconds. This is the control that closes that gap, and it is the
  /// whole reason a Library row ever draws an update affordance.
  const factory ActionRequest.updateWorld({
    required String world,
  }) = ActionRequest_UpdateWorld;
  const factory ActionRequest.startDevice({
    required String id,
  }) = ActionRequest_StartDevice;
  const factory ActionRequest.stopDevice({
    required String id,
  }) = ActionRequest_StopDevice;
  const factory ActionRequest.restartDevice({
    required String id,
  }) = ActionRequest_RestartDevice;

  /// Force-stop. Only ever offered for a daemon this client owns: ownership
  /// is the safety boundary, and there is no pid-based path across it.
  const factory ActionRequest.forceStopDevice({
    required String id,
  }) = ActionRequest_ForceStopDevice;
  const factory ActionRequest.stopAllOwned() = ActionRequest_StopAllOwned;

  /// Forget a device. `delete_data` additionally destroys what it holds, and
  /// is the one flag here that cannot be undone.
  const factory ActionRequest.removeDevice({
    required String id,
    required bool deleteData,
  }) = ActionRequest_RemoveDevice;

  /// Read one Space. Choosing a Space to administer is an act, not a
  /// listing — it is the read that makes the Members surface answerable.
  const factory ActionRequest.readSpace({
    required String orbit,
  }) = ActionRequest_ReadSpace;

  /// Start a browser head for this identity.
  const factory ActionRequest.startHead() = ActionRequest_StartHead;
  const factory ActionRequest.stopHead({
    required String id,
  }) = ActionRequest_StopHead;

  /// Forget an Orbit. The store is left alone; this is registry-only.
  const factory ActionRequest.forgetOrbit({
    required String space,
  }) = ActionRequest_ForgetOrbit;
  const factory ActionRequest.bookPut({
    String? card,
    required String name,
    String? note,
  }) = ActionRequest_BookPut;
  const factory ActionRequest.bookDelete({
    required String card,
  }) = ActionRequest_BookDelete;

  /// Set a card's picture from a file on this machine; `None` clears it.
  const factory ActionRequest.bookSetPicture({
    required String card,
    String? path,
  }) = ActionRequest_BookSetPicture;
  const factory ActionRequest.bookMerge({
    required String from,
    required String into,
  }) = ActionRequest_BookMerge;
  const factory ActionRequest.bookClaimSelf({
    required String card,
  }) = ActionRequest_BookClaimSelf;
  const factory ActionRequest.bookLink({
    required String card,
    required String handle,
  }) = ActionRequest_BookLink;
  const factory ActionRequest.bookUnlink({
    required String card,
    required String handle,
  }) = ActionRequest_BookUnlink;
  const factory ActionRequest.bookExport({
    required String path,
    List<String>? cards,
  }) = ActionRequest_BookExport;
  const factory ActionRequest.bookImport({
    required String path,
  }) = ActionRequest_BookImport;
  const factory ActionRequest.bookAccept({
    required String suggestion,
  }) = ActionRequest_BookAccept;
  const factory ActionRequest.bookDismiss({
    required String suggestion,
  }) = ActionRequest_BookDismiss;

  /// Author, or preview, an MCP binding for one World.
  ///
  /// Astrolabe writes the binding; the editor parents `lait mcp`. The World
  /// pin (`world`) is a mount this build hosts, not a path.
  const factory ActionRequest.installMcp({
    /// `claude` | `cursor` | `windsurf` | `generic`.
    required String client,

    /// `user` | `project`; `None` takes the client's default.
    String? scope,
    required String name,
    String? agent,
    required bool noAgent,
    required String project,

    /// World mount. `None` is the sole-World default.
    String? world,
    required bool preview,
  }) = ActionRequest_InstallMcp;

  /// Accept the receiver only after the person has compared the phrase and
  /// certificate fingerprint shown on both screens.
  const factory ActionRequest.displayPairingApprove({
    required String pairing,
    required String label,
  }) = ActionRequest_DisplayPairingApprove;
  const factory ActionRequest.displayPairingReject({
    required String pairing,
  }) = ActionRequest_DisplayPairingReject;

  /// Assign one exact World display surface to an enrolled receiver. The
  /// input remains JSON here because each package owns its own input schema;
  /// the daemon canonicalizes and validates it before committing the pin.
  const factory ActionRequest.displayAssignmentPut({
    required String device,
    required String orbit,
    required String world,
    required String surface,
    required String inputJson,
    required DisplayTheme theme,
    required int staleAfterMs,
    required DisplayStaleAction onStale,
    String? syncGroup,
    required DisplaySyncMode syncMode,
    required int staticDelayMs,
    BigInt? expiresAtUnixMs,
  }) = ActionRequest_DisplayAssignmentPut;
  const factory ActionRequest.displayAssignmentRevoke({
    required String assignment,
  }) = ActionRequest_DisplayAssignmentRevoke;
  const factory ActionRequest.displayDeviceRevoke({
    required String device,
  }) = ActionRequest_DisplayDeviceRevoke;

  /// Add a passphrase as a second way into the coordinator's identifier key.
  ///
  /// The first slot is sealed to this daemon's device, which survives an
  /// operating-system profile but not the loss of the identity. A passphrase
  /// depends on neither, which is what makes it a second way in rather than a
  /// second copy of the first.
  const factory ActionRequest.displayIdentifierAdmitPassphrase({
    required String passphrase,
  }) = ActionRequest_DisplayIdentifierAdmitPassphrase;

  /// Make this machine a screen.
  ///
  /// Pressing the control is the whole of the consent — there is no dialog
  /// in front of it, because being asked *what to show* before you are a
  /// screen is the wrong order. Nothing is enrolled and nothing is
  /// committed: this client is already a member of the Space it will draw,
  /// so there is no stranger to issue a credential to. Leaving is
  /// [`ActionRequest::LeavePresentation`].
  const factory ActionRequest.enterPresentation() =
      ActionRequest_EnterPresentation;

  /// Point this screen at one exact surface. Dispatched from inside the
  /// mode, never as a precondition for entering it.
  const factory ActionRequest.presentHere({
    required String orbit,
    required String world,
    required String surface,
    required String input,
    required String title,
  }) = ActionRequest_PresentHere;

  /// Ask the current selection again. What a refresh boundary and a manual
  /// nudge both do.
  const factory ActionRequest.presentRefresh() = ActionRequest_PresentRefresh;

  /// Stop being a screen.
  const factory ActionRequest.leavePresentation() =
      ActionRequest_LeavePresentation;
}

/// The identity's address book, as last read.
class BookFacts {
  final List<CardRow> cards;
  final bool migrationComplete;
  final int migrationPending;
  final int migrationImported;

  /// Staged card-exchange proposals awaiting review. Not in the book.
  final List<SuggestionRow> suggestions;

  const BookFacts({
    required this.cards,
    required this.migrationComplete,
    required this.migrationPending,
    required this.migrationImported,
    required this.suggestions,
  });

  @override
  int get hashCode =>
      cards.hashCode ^
      migrationComplete.hashCode ^
      migrationPending.hashCode ^
      migrationImported.hashCode ^
      suggestions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookFacts &&
          runtimeType == other.runtimeType &&
          cards == other.cards &&
          migrationComplete == other.migrationComplete &&
          migrationPending == other.migrationPending &&
          migrationImported == other.migrationImported &&
          suggestions == other.suggestions;
}

/// One authored Card. Handles are wire spellings, never reachability.
class CardRow {
  final String card;
  final String name;
  final String note;
  final List<String> handles;

  /// The phone-book reading of `handles`: addresses (`actor:` spellings),
  /// devices (bare device ids), and co-located agents (`agent:` spellings).
  final List<String> addresses;
  final List<String> devices;
  final List<String> agents;

  /// The stored picture (`<mime>;base64,<data>`), or `None` — the surface
  /// draws its default face for a card without one.
  final String? picture;
  final List<String> groups;
  final bool selfClaim;

  /// Measured presence joined over this card's handles, or `None` when no
  /// Space that names it could be asked. Unmeasured is absent, never
  /// `Offline` — the wire keeps the two apart so the surface can too.
  final PresenceView? presence;

  const CardRow({
    required this.card,
    required this.name,
    required this.note,
    required this.handles,
    required this.addresses,
    required this.devices,
    required this.agents,
    this.picture,
    required this.groups,
    required this.selfClaim,
    this.presence,
  });

  @override
  int get hashCode =>
      card.hashCode ^
      name.hashCode ^
      note.hashCode ^
      handles.hashCode ^
      addresses.hashCode ^
      devices.hashCode ^
      agents.hashCode ^
      picture.hashCode ^
      groups.hashCode ^
      selfClaim.hashCode ^
      presence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardRow &&
          runtimeType == other.runtimeType &&
          card == other.card &&
          name == other.name &&
          note == other.note &&
          handles == other.handles &&
          addresses == other.addresses &&
          devices == other.devices &&
          agents == other.agents &&
          picture == other.picture &&
          groups == other.groups &&
          selfClaim == other.selfClaim &&
          presence == other.presence;
}

/// Everything a surface can draw, as of one moment.
///
/// Sent whole. There is no partial update and no patch protocol, because a
/// patch protocol is a second model in disguise: the receiver has to hold the
/// previous state and apply changes to it, and the moment it can do that it can
/// disagree with the sender.
class ClientView {
  /// Nothing has been read yet. Distinct from "read, and there is nothing".
  final bool loading;

  /// Why what is on screen may not be current. `None` is fresh.
  final Staleness? stale;

  /// `None` until the library has been read once — which is not the same as
  /// a device that serves nothing.
  final List<LibraryRow>? library_;
  final HostFacts? host;

  /// The daemon-owned, self-hosted display coordinator. `None` until its
  /// first authoritative read lands.
  final DisplayFacts? display;

  /// This machine as a screen. `Some` *is* Big Picture — whether or not it
  /// has drawn anything yet — so a surface reads presence here rather than
  /// keeping a mode flag of its own that could disagree.
  final PresentationFacts? presentation;
  final List<HeadRow> heads;
  final List<DeviceRow> devices;
  final List<StorageRow> storage;

  /// This identity's Orbit registry, newest-opened first.
  final List<OrbitRow> orbits;

  /// The Space being administered, when one has been chosen. Choosing is an
  /// act — it costs a read — so this is absent until somebody chooses.
  final SpaceRow? space;

  /// `None` until the book has been read once. Empty cards is a book
  /// that answered and holds nothing, not an unread book.
  final BookFacts? book;
  final List<NoticeRow> notices;
  final List<FailureRow> failures;

  /// The keys of actions asked for and not yet answered. A control whose key
  /// is in here is disabled — on the frame the click happened, not on
  /// whichever later frame the answer arrives.
  final List<String> inFlight;

  /// Last MCP binding this client authored or previewed. Absent until then.
  final McpBindingRow? mcp;

  const ClientView({
    required this.loading,
    this.stale,
    this.library_,
    this.host,
    this.display,
    this.presentation,
    required this.heads,
    required this.devices,
    required this.storage,
    required this.orbits,
    this.space,
    this.book,
    required this.notices,
    required this.failures,
    required this.inFlight,
    this.mcp,
  });

  @override
  int get hashCode =>
      loading.hashCode ^
      stale.hashCode ^
      library_.hashCode ^
      host.hashCode ^
      display.hashCode ^
      presentation.hashCode ^
      heads.hashCode ^
      devices.hashCode ^
      storage.hashCode ^
      orbits.hashCode ^
      space.hashCode ^
      book.hashCode ^
      notices.hashCode ^
      failures.hashCode ^
      inFlight.hashCode ^
      mcp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientView &&
          runtimeType == other.runtimeType &&
          loading == other.loading &&
          stale == other.stale &&
          library_ == other.library_ &&
          host == other.host &&
          display == other.display &&
          presentation == other.presentation &&
          heads == other.heads &&
          devices == other.devices &&
          storage == other.storage &&
          orbits == other.orbits &&
          space == other.space &&
          book == other.book &&
          notices == other.notices &&
          failures == other.failures &&
          inFlight == other.inFlight &&
          mcp == other.mcp;
}

class DeviceRow {
  final String id;
  final String label;
  final String state;
  final bool owned;

  /// Whether observation of this device is degraded, and what went wrong.
  /// A sampling failure preserves the last good reading and says so; it is
  /// never drawn as "nothing there".
  final String? degraded;
  final String home;

  /// `None` for a daemon this client did not spawn. Ownership is a boundary:
  /// there is no pid-based path to stopping something we do not own, and the
  /// absence of a pid here is that boundary crossing the bridge.
  final int? pid;

  /// Whether this client may force-stop it. Answered by the core's
  /// capabilities rather than inferred from ownership on this side, because
  /// the two can differ and only one of them is authoritative.
  final bool canForceStop;
  final String? lastError;

  const DeviceRow({
    required this.id,
    required this.label,
    required this.state,
    required this.owned,
    this.degraded,
    required this.home,
    this.pid,
    required this.canForceStop,
    this.lastError,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      state.hashCode ^
      owned.hashCode ^
      degraded.hashCode ^
      home.hashCode ^
      pid.hashCode ^
      canForceStop.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          owned == other.owned &&
          degraded == other.degraded &&
          home == other.home &&
          pid == other.pid &&
          canForceStop == other.canForceStop &&
          lastError == other.lastError;
}

/// A diagnosis, when one was taken.
///
/// Absent when the Space could not be asked — which is *not* the same as every
/// gate passing, and is the whole reason this is an `Option` rather than an
/// empty list of gates.
class DiagnosisRow {
  final List<GateRow> gates;

  /// The first non-passing gate: the one actionable blocker.
  final String? blockedOn;
  final String summary;

  const DiagnosisRow({
    required this.gates,
    this.blockedOn,
    required this.summary,
  });

  @override
  int get hashCode => gates.hashCode ^ blockedOn.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisRow &&
          runtimeType == other.runtimeType &&
          gates == other.gates &&
          blockedOn == other.blockedOn &&
          summary == other.summary;
}

class DisplayAssignmentRow {
  final String assignment;
  final String device;
  final String orbit;
  final String space;
  final String program;
  final String world;
  final String surface;
  final String controller;
  final DisplayTheme theme;
  final String? syncGroup;
  final DisplaySyncMode? syncMode;
  final int staticDelayMs;
  final BigInt? expiresAtUnixMs;
  final BigInt? revokedAtUnixMs;

  const DisplayAssignmentRow({
    required this.assignment,
    required this.device,
    required this.orbit,
    required this.space,
    required this.program,
    required this.world,
    required this.surface,
    required this.controller,
    required this.theme,
    this.syncGroup,
    this.syncMode,
    required this.staticDelayMs,
    this.expiresAtUnixMs,
    this.revokedAtUnixMs,
  });

  @override
  int get hashCode =>
      assignment.hashCode ^
      device.hashCode ^
      orbit.hashCode ^
      space.hashCode ^
      program.hashCode ^
      world.hashCode ^
      surface.hashCode ^
      controller.hashCode ^
      theme.hashCode ^
      syncGroup.hashCode ^
      syncMode.hashCode ^
      staticDelayMs.hashCode ^
      expiresAtUnixMs.hashCode ^
      revokedAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayAssignmentRow &&
          runtimeType == other.runtimeType &&
          assignment == other.assignment &&
          device == other.device &&
          orbit == other.orbit &&
          space == other.space &&
          program == other.program &&
          world == other.world &&
          surface == other.surface &&
          controller == other.controller &&
          theme == other.theme &&
          syncGroup == other.syncGroup &&
          syncMode == other.syncMode &&
          staticDelayMs == other.staticDelayMs &&
          expiresAtUnixMs == other.expiresAtUnixMs &&
          revokedAtUnixMs == other.revokedAtUnixMs;
}

/// Astrolabe's complete controller-facing projection of the local display
/// coordinator. Receiver proof keys and canonical assignment input remain on
/// the daemon side of the boundary.
class DisplayFacts {
  final String instance;
  final String label;
  final String origin;
  final String certificateSha256;
  final String certificatePem;
  final List<DisplaySurfaceRow> surfaces;
  final List<DisplayReceiverRow> devices;
  final List<DisplayAssignmentRow> assignments;
  final List<DisplayPairingRow> pendingPairings;

  /// `None` from a daemon that predates the custody split — not reported, as
  /// distinct from reported-as-none.
  final DisplayIdentifierCustodyRow? identifierCustody;

  const DisplayFacts({
    required this.instance,
    required this.label,
    required this.origin,
    required this.certificateSha256,
    required this.certificatePem,
    required this.surfaces,
    required this.devices,
    required this.assignments,
    required this.pendingPairings,
    this.identifierCustody,
  });

  @override
  int get hashCode =>
      instance.hashCode ^
      label.hashCode ^
      origin.hashCode ^
      certificateSha256.hashCode ^
      certificatePem.hashCode ^
      surfaces.hashCode ^
      devices.hashCode ^
      assignments.hashCode ^
      pendingPairings.hashCode ^
      identifierCustody.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayFacts &&
          runtimeType == other.runtimeType &&
          instance == other.instance &&
          label == other.label &&
          origin == other.origin &&
          certificateSha256 == other.certificateSha256 &&
          certificatePem == other.certificatePem &&
          surfaces == other.surfaces &&
          devices == other.devices &&
          assignments == other.assignments &&
          pendingPairings == other.pendingPairings &&
          identifierCustody == other.identifierCustody;
}

class DisplayHealthRow {
  final String revision;
  final String currentItem;
  final int elapsedMs;
  final String connection;
  final String playback;
  final String lastError;
  final int stagedItems;
  final int stagedBytes;
  final int driftResidualMs;
  final int correctionEvents;
  final bool pipelineUnobservable;

  const DisplayHealthRow({
    required this.revision,
    required this.currentItem,
    required this.elapsedMs,
    required this.connection,
    required this.playback,
    required this.lastError,
    required this.stagedItems,
    required this.stagedBytes,
    required this.driftResidualMs,
    required this.correctionEvents,
    required this.pipelineUnobservable,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      currentItem.hashCode ^
      elapsedMs.hashCode ^
      connection.hashCode ^
      playback.hashCode ^
      lastError.hashCode ^
      stagedItems.hashCode ^
      stagedBytes.hashCode ^
      driftResidualMs.hashCode ^
      correctionEvents.hashCode ^
      pipelineUnobservable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayHealthRow &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          currentItem == other.currentItem &&
          elapsedMs == other.elapsedMs &&
          connection == other.connection &&
          playback == other.playback &&
          lastError == other.lastError &&
          stagedItems == other.stagedItems &&
          stagedBytes == other.stagedBytes &&
          driftResidualMs == other.driftResidualMs &&
          correctionEvents == other.correctionEvents &&
          pipelineUnobservable == other.pipelineUnobservable;
}

/// How many ways back into this coordinator's identifier key exist, and whether
/// any survives the machine.
///
/// Carried on the ordinary status projection rather than a settings page: the
/// moment an operator wants this is after the machine is gone, and a fact only
/// reachable from the lost machine is not a fact they have.
class DisplayIdentifierCustodyRow {
  /// Kinds of unlock path, never material.
  final List<String> slots;
  final bool portable;

  const DisplayIdentifierCustodyRow({
    required this.slots,
    required this.portable,
  });

  @override
  int get hashCode => slots.hashCode ^ portable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayIdentifierCustodyRow &&
          runtimeType == other.runtimeType &&
          slots == other.slots &&
          portable == other.portable;
}

class DisplayPairingRow {
  final String pairing;
  final List<String> confirmationPhrase;
  final String certificateSha256;
  final String platform;
  final String build;
  final BigInt createdAtUnixMs;
  final BigInt expiresAtUnixMs;

  const DisplayPairingRow({
    required this.pairing,
    required this.confirmationPhrase,
    required this.certificateSha256,
    required this.platform,
    required this.build,
    required this.createdAtUnixMs,
    required this.expiresAtUnixMs,
  });

  @override
  int get hashCode =>
      pairing.hashCode ^
      confirmationPhrase.hashCode ^
      certificateSha256.hashCode ^
      platform.hashCode ^
      build.hashCode ^
      createdAtUnixMs.hashCode ^
      expiresAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayPairingRow &&
          runtimeType == other.runtimeType &&
          pairing == other.pairing &&
          confirmationPhrase == other.confirmationPhrase &&
          certificateSha256 == other.certificateSha256 &&
          platform == other.platform &&
          build == other.build &&
          createdAtUnixMs == other.createdAtUnixMs &&
          expiresAtUnixMs == other.expiresAtUnixMs;
}

class DisplayReceiverRow {
  final String device;
  final String label;
  final String platform;
  final String build;
  final BigInt issuedAtUnixMs;
  final BigInt? revokedAtUnixMs;
  final DisplayHealthRow? health;

  const DisplayReceiverRow({
    required this.device,
    required this.label,
    required this.platform,
    required this.build,
    required this.issuedAtUnixMs,
    this.revokedAtUnixMs,
    this.health,
  });

  @override
  int get hashCode =>
      device.hashCode ^
      label.hashCode ^
      platform.hashCode ^
      build.hashCode ^
      issuedAtUnixMs.hashCode ^
      revokedAtUnixMs.hashCode ^
      health.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayReceiverRow &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          label == other.label &&
          platform == other.platform &&
          build == other.build &&
          issuedAtUnixMs == other.issuedAtUnixMs &&
          revokedAtUnixMs == other.revokedAtUnixMs &&
          health == other.health;
}

enum DisplayStaleAction {
  keepWithNativeBanner,
  blank,
  ;
}

class DisplaySurfaceRow {
  final String world;
  final String surface;
  final String title;
  final int contractVersion;
  final List<String> outputs;

  const DisplaySurfaceRow({
    required this.world,
    required this.surface,
    required this.title,
    required this.contractVersion,
    required this.outputs,
  });

  @override
  int get hashCode =>
      world.hashCode ^
      surface.hashCode ^
      title.hashCode ^
      contractVersion.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplaySurfaceRow &&
          runtimeType == other.runtimeType &&
          world == other.world &&
          surface == other.surface &&
          title == other.title &&
          contractVersion == other.contractVersion &&
          outputs == other.outputs;
}

enum DisplaySyncMode {
  stayInSync,
  positional,
  ;
}

enum DisplayTheme {
  light,
  dark,
  highContrast,
  ;
}

class FailureRow {
  final String what;
  final String error;

  /// Whether asking again could plausibly work. A refusal is not a retry.
  final bool retryable;

  const FailureRow({
    required this.what,
    required this.error,
    required this.retryable,
  });

  @override
  int get hashCode => what.hashCode ^ error.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailureRow &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          error == other.error &&
          retryable == other.retryable;
}

/// What a gate answered, when a diagnosis was taken.
class GateRow {
  /// Stable machine id — `space`, `daemon`, `membership`, `peer`, `synced`.
  final String id;
  final String label;
  final GateState state;
  final String detail;

  const GateRow({
    required this.id,
    required this.label,
    required this.state,
    required this.detail,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ state.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GateRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          detail == other.detail;
}

/// Five states, not two.
///
/// `Warn` is deliberately not blocking: a key-custody problem is urgent to fix
/// and irrelevant to whether somebody is onboarded, and a warning that hijacked
/// the blocker would tell a joiner they are stuck when they are not.
enum GateState {
  pass,
  wait,
  fail,
  warn,
  skip,
  ;
}

class HeadRow {
  final String id;

  /// Browser or MCP.
  final String kind;

  /// The Orbit it is bound to. `None` is a browser head serving every Orbit
  /// its identity has.
  final String? orbit;

  /// The one World this head serves.
  ///
  /// `None` is a head from before the pin, which answers for every mounted
  /// World. It matches no row deliberately: a surface cannot say a definite
  /// thing about it, and saying an indefinite thing is the defect this field
  /// closes.
  final String? world;

  /// The address, *without* the run credential its URL carries. A front page
  /// has no use for a credential — `Open` mints a single-use ticket of its
  /// own, which is what that ceremony is for.
  final String? origin;
  final bool owned;

  const HeadRow({
    required this.id,
    required this.kind,
    this.orbit,
    this.world,
    this.origin,
    required this.owned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      orbit.hashCode ^
      world.hashCode ^
      origin.hashCode ^
      owned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          orbit == other.orbit &&
          world == other.world &&
          origin == other.origin &&
          owned == other.owned;
}

class HostFacts {
  final String version;
  final String identityHome;
  final String spacesRoot;
  final int orbitCount;

  const HostFacts({
    required this.version,
    required this.identityHome,
    required this.spacesRoot,
    required this.orbitCount,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      identityHome.hashCode ^
      spacesRoot.hashCode ^
      orbitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostFacts &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          identityHome == other.identityHome &&
          spacesRoot == other.spacesRoot &&
          orbitCount == other.orbitCount;
}

/// One row of the Library: an installed World.
///
/// Everything here is declared by the bundled package and compiled in — no
/// probe ran to produce it, and no daemon can make it stale. Which Spaces
/// serve the World is the destination's fact: the head's own front page
/// carries the Space selector, and this row deliberately does not pre-ask it.
class LibraryRow {
  /// Stable across re-reads: the mount. A selection keyed by index would
  /// silently follow whatever moved into that position.
  final String key;
  final String worldMount;

  /// What the World calls itself. Always present — an installed package
  /// declares its name, so there is no unnamed row to draw.
  final String displayName;

  /// Where `Open` lands. `None` is a World that declared no entry path,
  /// which cannot be opened: `/` is not a guess to make on its behalf.
  final String? opensAt;

  /// Reviewed implementation version for the hosted World.
  final int? version;

  /// One line saying what this World is for.
  final String? tagline;

  /// Packed `0xRRGGBB`. A seed the interface derives a plate from locally;
  /// there is no asset here and nothing to fetch.
  final int? accent;

  /// People from the identity's book addressed in any Space this World is
  /// reachable in. `None` until the book has been read — which is not the
  /// same as a World nobody in the book is addressed near.
  final List<WorldPersonRow>? people;

  /// What this machine last learned about the World's own channel. `None`
  /// when nothing has ever been checked — which is not "up to date", and
  /// draws exactly what this row drew before any of it existed.
  final WorldUpdateRow? update;

  const LibraryRow({
    required this.key,
    required this.worldMount,
    required this.displayName,
    this.opensAt,
    this.version,
    this.tagline,
    this.accent,
    this.people,
    this.update,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      worldMount.hashCode ^
      displayName.hashCode ^
      opensAt.hashCode ^
      version.hashCode ^
      tagline.hashCode ^
      accent.hashCode ^
      people.hashCode ^
      update.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRow &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          worldMount == other.worldMount &&
          displayName == other.displayName &&
          opensAt == other.opensAt &&
          version == other.version &&
          tagline == other.tagline &&
          accent == other.accent &&
          people == other.people &&
          update == other.update;
}

/// What authoring an MCP binding produced. Bindings, not processes.
class McpBindingRow {
  final String path;
  final String detail;
  final String? note;
  final bool replaced;
  final String? agent;
  final bool written;

  /// Mount the binding was authored for. A surface showing another World
  /// must ignore this row.
  final String? world;

  const McpBindingRow({
    required this.path,
    required this.detail,
    this.note,
    required this.replaced,
    this.agent,
    required this.written,
    this.world,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      detail.hashCode ^
      note.hashCode ^
      replaced.hashCode ^
      agent.hashCode ^
      written.hashCode ^
      world.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpBindingRow &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          detail == other.detail &&
          note == other.note &&
          replaced == other.replaced &&
          agent == other.agent &&
          written == other.written &&
          world == other.world;
}

class MemberRow {
  final String id;
  final String? nick;

  /// Authored Card name that names this member, when one exists.
  /// Distinct from [`Self::nick`], which is Space-local and derived.
  final String? authoredName;
  final bool admin;

  const MemberRow({
    required this.id,
    this.nick,
    this.authoredName,
    required this.admin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ nick.hashCode ^ authoredName.hashCode ^ admin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nick == other.nick &&
          authoredName == other.authoredName &&
          admin == other.admin;
}

enum Missing {
  /// It is not up. Not an error, and not something a listing corrects —
  /// measuring must not place what nobody asked to place.
  notPlaced,

  /// It could not be asked.
  unreachable,
  ;
}

class NoticeRow {
  final String said;

  /// Where a browser was sent, when that is what happened.
  final String? launched;

  const NoticeRow({
    required this.said,
    this.launched,
  });

  @override
  int get hashCode => said.hashCode ^ launched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoticeRow &&
          runtimeType == other.runtimeType &&
          said == other.said &&
          launched == other.launched;
}

/// One Orbit in this identity's registry.
class OrbitRow {
  final String space;
  final String name;
  final String path;

  /// `None` is never opened, for the same reason it is on a library row.
  final BigInt? lastOpened;

  const OrbitRow({
    required this.space,
    required this.name,
    required this.path,
    this.lastOpened,
  });

  @override
  int get hashCode =>
      space.hashCode ^ name.hashCode ^ path.hashCode ^ lastOpened.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrbitRow &&
          runtimeType == other.runtimeType &&
          space == other.space &&
          name == other.name &&
          path == other.path &&
          lastOpened == other.lastOpened;
}

/// Measured reachability for the identity a Card names, from this device's
/// vantage — the Neighbor registry's beacon-fed answer, never a default.
enum PresenceView {
  online,
  away,

  /// A Space that names this identity answered, and nothing speaks for it
  /// right now. A measurement — distinct from the card-level `None`, which
  /// is "no Space that names it could be asked".
  offline,
  ;
}

/// What a screen was pointed at.
class PresentationChoice {
  final String orbit;
  final String world;
  final String surface;

  /// What to call this on screen while it is loading or refusing.
  final String title;

  const PresentationChoice({
    required this.orbit,
    required this.world,
    required this.surface,
    required this.title,
  });

  @override
  int get hashCode =>
      orbit.hashCode ^ world.hashCode ^ surface.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationChoice &&
          runtimeType == other.runtimeType &&
          orbit == other.orbit &&
          world == other.world &&
          surface == other.surface &&
          title == other.title;
}

/// This machine as a screen. Present exactly when Big Picture is on.
///
/// Being a screen and showing something are separate facts, so `chosen` is
/// optional: a screen entered and not yet pointed at anything is a real state
/// with its own surface, not a half-built one.
class PresentationFacts {
  final PresentationChoice? chosen;

  /// The last verified render, kept across a failed re-ask so a screen goes
  /// stale rather than dark.
  final PresentedProgram? program;

  /// Why the last attempt did not answer. Travels *beside* `program`, never
  /// instead of it — "stale, and here is why" and "nothing to show" are
  /// different things to tell somebody standing in front of a screen.
  final String? failure;

  const PresentationFacts({
    this.chosen,
    this.program,
    this.failure,
  });

  @override
  int get hashCode => chosen.hashCode ^ program.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentationFacts &&
          runtimeType == other.runtimeType &&
          chosen == other.chosen &&
          program == other.program &&
          failure == other.failure;
}

class PresentedItem {
  final String id;
  final int? durationMs;
  final String assessment;
  final String? spokenSummary;
  final PresentedScene scene;

  const PresentedItem({
    required this.id,
    this.durationMs,
    required this.assessment,
    this.spokenSummary,
    required this.scene,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      durationMs.hashCode ^
      assessment.hashCode ^
      spokenSummary.hashCode ^
      scene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentedItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          durationMs == other.durationMs &&
          assessment == other.assessment &&
          spokenSummary == other.spokenSummary &&
          scene == other.scene;
}

class PresentedProgram {
  /// `current`, `partial`, or `unavailable`.
  final String assessment;
  final List<String> partialReasons;

  /// `hold_last`, `loop`, `poll_at_end`, or `blank_at_end`.
  final String cycle;
  final int? refreshAfterMs;
  final List<PresentedItem> items;

  const PresentedProgram({
    required this.assessment,
    required this.partialReasons,
    required this.cycle,
    this.refreshAfterMs,
    required this.items,
  });

  @override
  int get hashCode =>
      assessment.hashCode ^
      partialReasons.hashCode ^
      cycle.hashCode ^
      refreshAfterMs.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PresentedProgram &&
          runtimeType == other.runtimeType &&
          assessment == other.assessment &&
          partialReasons == other.partialReasons &&
          cycle == other.cycle &&
          refreshAfterMs == other.refreshAfterMs &&
          items == other.items;
}

@freezed
sealed class PresentedScene with _$PresentedScene {
  const PresentedScene._();

  const factory PresentedScene.frame({
    /// `png`, `jpeg`, or `webp`.
    required String mediaType,
    required int width,
    required int height,
    required Uint8List bytes,
  }) = PresentedScene_Frame;
  const factory PresentedScene.blank({
    /// `source_unavailable`, `unsupported`, or `program_ended`.
    required String reason,
  }) = PresentedScene_Blank;
  const factory PresentedScene.unsupported({
    required String output,
  }) = PresentedScene_Unsupported;
}

/// The Space somebody is administering, as it last answered.
class SpaceRow {
  final String space;

  /// This actor's standing *here*. Per Orbit rather than per identity: one
  /// identity may hold very different standing in two Spaces, and a single
  /// answer would have to pick one and be wrong about the other.
  final String? whoami;
  final bool admin;
  final List<MemberRow> members;
  final List<String> devices;
  final DiagnosisRow? diagnosis;

  const SpaceRow({
    required this.space,
    this.whoami,
    required this.admin,
    required this.members,
    required this.devices,
    this.diagnosis,
  });

  @override
  int get hashCode =>
      space.hashCode ^
      whoami.hashCode ^
      admin.hashCode ^
      members.hashCode ^
      devices.hashCode ^
      diagnosis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpaceRow &&
          runtimeType == other.runtimeType &&
          space == other.space &&
          whoami == other.whoami &&
          admin == other.admin &&
          members == other.members &&
          devices == other.devices &&
          diagnosis == other.diagnosis;
}

@freezed
sealed class Staleness with _$Staleness {
  const Staleness._();

  /// The first read has not landed.
  const factory Staleness.neverLoaded() = Staleness_NeverLoaded;

  /// The stream said so, and said why.
  const factory Staleness.signalled(
    String field0,
  ) = Staleness_Signalled;
}

/// What one Orbit is holding.
class StorageRow {
  final String orbit;

  /// What the registry calls it. Advisory — a display name is owned by a
  /// World today — and carried as what it is rather than as truth.
  final String? name;

  /// Every figure is optional, and that is the contract. A footprint nobody
  /// could measure is *absent*, never zero: an Orbit reported as holding 0
  /// bytes is a claim, and one nobody asked is not.
  final BigInt? bytesOnDisk;
  final BigInt? objectCount;
  final BigInt? lastVerifiedMs;

  /// Why there are no figures, when there are none. Two reasons, because
  /// "not up" and "could not be asked" are different facts.
  final Missing? missing;

  const StorageRow({
    required this.orbit,
    this.name,
    this.bytesOnDisk,
    this.objectCount,
    this.lastVerifiedMs,
    this.missing,
  });

  @override
  int get hashCode =>
      orbit.hashCode ^
      name.hashCode ^
      bytesOnDisk.hashCode ^
      objectCount.hashCode ^
      lastVerifiedMs.hashCode ^
      missing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageRow &&
          runtimeType == other.runtimeType &&
          orbit == other.orbit &&
          name == other.name &&
          bytesOnDisk == other.bytesOnDisk &&
          objectCount == other.objectCount &&
          lastVerifiedMs == other.lastVerifiedMs &&
          missing == other.missing;
}

/// One staged suggestion from a card-exchange file. Review is the only way
/// into the book, so this carries exactly what the person must judge.
class SuggestionRow {
  final String suggestion;
  final String name;
  final String note;
  final List<String> handles;

  const SuggestionRow({
    required this.suggestion,
    required this.name,
    required this.note,
    required this.handles,
  });

  @override
  int get hashCode =>
      suggestion.hashCode ^ name.hashCode ^ note.hashCode ^ handles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuggestionRow &&
          runtimeType == other.runtimeType &&
          suggestion == other.suggestion &&
          name == other.name &&
          note == other.note &&
          handles == other.handles;
}

/// The artwork one World ships, as PNG bytes compiled into this build.
///
/// Not part of [`LibraryRow`], and the omission is the design: see
/// [`world_artwork`]. Both halves are optional and their absence is a real
/// answer — a World that ships neither is drawn from its accent, which is what
/// every World was drawn from before any of them shipped art.
///
/// No `Default` derive: the codegen turns one into a `default_()` on the Dart
/// class — an asynchronous round trip to the core to learn that two fields are
/// null, which `const WorldArtwork()` already says on the Dart side for free.
class WorldArtwork {
  final Uint8List? mark;
  final Uint8List? hero;

  const WorldArtwork({
    this.mark,
    this.hero,
  });

  @override
  int get hashCode => mark.hashCode ^ hero.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldArtwork &&
          runtimeType == other.runtimeType &&
          mark == other.mark &&
          hero == other.hero;
}

/// One person the book addresses near a World — the at-a-glance join between
/// the identity's own book and a Library row, across every Space the card
/// holds an address in. Not a roster: that is an authoritative read the
/// World's own head answers for, and this panel never places anything to
/// find out. My Card is excluded — the glance answers "who of mine is here",
/// and you are not a contact of yourself.
class WorldPersonRow {
  final String name;

  /// The stored picture (`<mime>;base64,<data>`), or `None` for the
  /// default face — the same canonical face the book draws.
  final String? picture;

  /// Best measured presence across the Spaces this card holds an address
  /// in, or `None` when none of them could be asked. A person is as
  /// present as their most reachable address.
  final PresenceView? presence;

  /// Filed under the canonical agent group.
  final bool agent;

  /// Has this World open right now: a World-scoped Live row spoke for
  /// them when the Space was asked. The panel's nearest liveness — a
  /// launched World, not merely a reachable device.
  final bool here;

  const WorldPersonRow({
    required this.name,
    this.picture,
    this.presence,
    required this.agent,
    required this.here,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      picture.hashCode ^
      presence.hashCode ^
      agent.hashCode ^
      here.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldPersonRow &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          picture == other.picture &&
          presence == other.presence &&
          agent == other.agent &&
          here == other.here;
}

/// A World's channel, as this machine last found it.
///
/// Separate from the row's compiled-in fields because the two are different
/// kinds of fact: the list is the install list and cannot go stale, this is
/// measured and can. Keeping them apart is what stops the Library becoming a
/// surface that probes to draw itself.
class WorldUpdateRow {
  /// The bundle version serving now. `None` is the embedded floor.
  final String? serving;

  /// The version the channel named when it was last asked.
  final String? available;

  /// The channel holds a bundle this machine is not serving and this build
  /// can run. The only state that turns `Open` into `Update`.
  final bool behind;

  /// A newer bundle exists that this build cannot run, each unmet
  /// requirement named. Shown, never offered — pressing an update that
  /// would be refused on arrival teaches a person to distrust the control.
  final List<String>? unmet;

  const WorldUpdateRow({
    this.serving,
    this.available,
    required this.behind,
    this.unmet,
  });

  @override
  int get hashCode =>
      serving.hashCode ^ available.hashCode ^ behind.hashCode ^ unmet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldUpdateRow &&
          runtimeType == other.runtimeType &&
          serving == other.serving &&
          available == other.available &&
          behind == other.behind &&
          unmet == other.unmet;
}
