// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `attach_paths`, `attach_to`, `attach`, `authored_name_for`, `emit`, `emit`, `empty`, `into_action`, `len`, `new`, `project`, `space_ref`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Core`, `Watchers`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `push`

/// Start the core, or attach to the one that is already running.
///
/// The first isolate boots the runtime. Later ones attach: same App, same
/// supervisor, a new view stream. A second *boot* — a start against a
/// different identity — is refused rather than spawning a second supervisor
/// of the same devices.
void start({String? stateRoot, String? sidecar}) =>
    Core.instance.api.crateApiStart(stateRoot: stateRoot, sidecar: sidecar);

/// Ask for something, and get back the view as it stands the instant it was
/// asked for.
///
/// Returning the view rather than nothing is what makes "a control is disabled
/// the moment it is clicked" true across a boundary. Waiting for the pump would
/// leave a live control for one round trip, which is long enough to press four
/// times and see three refusals.
ClientView dispatch({required ActionRequest action}) =>
    Core.instance.api.crateApiDispatch(action: action);

/// The view as it stands, for a surface that has just been built.
ClientView current() => Core.instance.api.crateApiCurrent();

/// Every view from now on, on this isolate.
///
/// Each attached isolate opens its own stream. Every live sink receives the
/// same [`ClientView`] on every pump; a sink that goes away is dropped and
/// does not stall the rest.
Stream<ClientView> watch() => Core.instance.api.crateApiWatch();

abstract class ViewPush {
  Future<bool> push({required ClientView view});
}

@freezed
sealed class ActionRequest with _$ActionRequest {
  const ActionRequest._();

  /// Read this machine again.
  const factory ActionRequest.refresh() = ActionRequest_Refresh;

  /// Hand a World to the person's browser.
  const factory ActionRequest.open({
    required String orbit,
    required String entryPath,
  }) = ActionRequest_Open;
  const factory ActionRequest.startDevice({
    required String id,
  }) = ActionRequest_StartDevice;
  const factory ActionRequest.stopDevice({
    required String id,
  }) = ActionRequest_StopDevice;
  const factory ActionRequest.restartDevice({
    required String id,
  }) = ActionRequest_RestartDevice;

  /// Force-stop. Only ever offered for a daemon this client owns: ownership
  /// is the safety boundary, and there is no pid-based path across it.
  const factory ActionRequest.forceStopDevice({
    required String id,
  }) = ActionRequest_ForceStopDevice;
  const factory ActionRequest.stopAllOwned() = ActionRequest_StopAllOwned;

  /// Forget a device. `delete_data` additionally destroys what it holds, and
  /// is the one flag here that cannot be undone.
  const factory ActionRequest.removeDevice({
    required String id,
    required bool deleteData,
  }) = ActionRequest_RemoveDevice;

  /// Read one Space. Choosing a Space to administer is an act, not a
  /// listing — it is the read that makes the Members surface answerable.
  const factory ActionRequest.readSpace({
    required String orbit,
  }) = ActionRequest_ReadSpace;

  /// Start a browser head for this identity.
  const factory ActionRequest.startHead() = ActionRequest_StartHead;
  const factory ActionRequest.stopHead({
    required String id,
  }) = ActionRequest_StopHead;

  /// Forget an Orbit. The store is left alone; this is registry-only.
  const factory ActionRequest.forgetOrbit({
    required String space,
  }) = ActionRequest_ForgetOrbit;
  const factory ActionRequest.bookPut({
    String? card,
    required String name,
    String? note,
  }) = ActionRequest_BookPut;
  const factory ActionRequest.bookDelete({
    required String card,
  }) = ActionRequest_BookDelete;
  const factory ActionRequest.bookMerge({
    required String from,
    required String into,
  }) = ActionRequest_BookMerge;
  const factory ActionRequest.bookClaimSelf({
    required String card,
  }) = ActionRequest_BookClaimSelf;
  const factory ActionRequest.bookLink({
    required String card,
    required String handle,
  }) = ActionRequest_BookLink;
  const factory ActionRequest.bookUnlink({
    required String card,
    required String handle,
  }) = ActionRequest_BookUnlink;
  const factory ActionRequest.bookExport({
    required String path,
    List<String>? cards,
  }) = ActionRequest_BookExport;
  const factory ActionRequest.bookImport({
    required String path,
  }) = ActionRequest_BookImport;
}

/// The identity's address book, as last read.
class BookFacts {
  final List<CardRow> cards;
  final bool migrationComplete;
  final int migrationPending;
  final int migrationImported;

  const BookFacts({
    required this.cards,
    required this.migrationComplete,
    required this.migrationPending,
    required this.migrationImported,
  });

  @override
  int get hashCode =>
      cards.hashCode ^
      migrationComplete.hashCode ^
      migrationPending.hashCode ^
      migrationImported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookFacts &&
          runtimeType == other.runtimeType &&
          cards == other.cards &&
          migrationComplete == other.migrationComplete &&
          migrationPending == other.migrationPending &&
          migrationImported == other.migrationImported;
}

/// One authored Card. Handles are wire spellings, never reachability.
class CardRow {
  final String card;
  final String name;
  final String note;
  final List<String> handles;
  final List<String> groups;
  final bool selfClaim;

  const CardRow({
    required this.card,
    required this.name,
    required this.note,
    required this.handles,
    required this.groups,
    required this.selfClaim,
  });

  @override
  int get hashCode =>
      card.hashCode ^
      name.hashCode ^
      note.hashCode ^
      handles.hashCode ^
      groups.hashCode ^
      selfClaim.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardRow &&
          runtimeType == other.runtimeType &&
          card == other.card &&
          name == other.name &&
          note == other.note &&
          handles == other.handles &&
          groups == other.groups &&
          selfClaim == other.selfClaim;
}

/// Everything a surface can draw, as of one moment.
///
/// Sent whole. There is no partial update and no patch protocol, because a
/// patch protocol is a second model in disguise: the receiver has to hold the
/// previous state and apply changes to it, and the moment it can do that it can
/// disagree with the sender.
class ClientView {
  /// Nothing has been read yet. Distinct from "read, and there is nothing".
  final bool loading;

  /// Why what is on screen may not be current. `None` is fresh.
  final Staleness? stale;

  /// `None` until the library has been read once — which is not the same as
  /// a device that serves nothing.
  final List<LibraryRow>? library_;
  final HostFacts? host;
  final List<HeadRow> heads;
  final List<DeviceRow> devices;
  final List<StorageRow> storage;

  /// This identity's Orbit registry, newest-opened first.
  final List<OrbitRow> orbits;

  /// The Space being administered, when one has been chosen. Choosing is an
  /// act — it costs a read — so this is absent until somebody chooses.
  final SpaceRow? space;

  /// `None` until the book has been read once. Empty cards is a book
  /// that answered and holds nothing, not an unread book.
  final BookFacts? book;
  final List<NoticeRow> notices;
  final List<FailureRow> failures;

  /// The keys of actions asked for and not yet answered. A control whose key
  /// is in here is disabled — on the frame the click happened, not on
  /// whichever later frame the answer arrives.
  final List<String> inFlight;

  const ClientView({
    required this.loading,
    this.stale,
    this.library_,
    this.host,
    required this.heads,
    required this.devices,
    required this.storage,
    required this.orbits,
    this.space,
    this.book,
    required this.notices,
    required this.failures,
    required this.inFlight,
  });

  @override
  int get hashCode =>
      loading.hashCode ^
      stale.hashCode ^
      library_.hashCode ^
      host.hashCode ^
      heads.hashCode ^
      devices.hashCode ^
      storage.hashCode ^
      orbits.hashCode ^
      space.hashCode ^
      book.hashCode ^
      notices.hashCode ^
      failures.hashCode ^
      inFlight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientView &&
          runtimeType == other.runtimeType &&
          loading == other.loading &&
          stale == other.stale &&
          library_ == other.library_ &&
          host == other.host &&
          heads == other.heads &&
          devices == other.devices &&
          storage == other.storage &&
          orbits == other.orbits &&
          space == other.space &&
          book == other.book &&
          notices == other.notices &&
          failures == other.failures &&
          inFlight == other.inFlight;
}

class DeviceRow {
  final String id;
  final String label;
  final String state;
  final bool owned;

  /// Whether observation of this device is degraded, and what went wrong.
  /// A sampling failure preserves the last good reading and says so; it is
  /// never drawn as "nothing there".
  final String? degraded;
  final String home;

  /// `None` for a daemon this client did not spawn. Ownership is a boundary:
  /// there is no pid-based path to stopping something we do not own, and the
  /// absence of a pid here is that boundary crossing the bridge.
  final int? pid;

  /// Whether this client may force-stop it. Answered by the core's
  /// capabilities rather than inferred from ownership on this side, because
  /// the two can differ and only one of them is authoritative.
  final bool canForceStop;
  final String? lastError;

  const DeviceRow({
    required this.id,
    required this.label,
    required this.state,
    required this.owned,
    this.degraded,
    required this.home,
    this.pid,
    required this.canForceStop,
    this.lastError,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      state.hashCode ^
      owned.hashCode ^
      degraded.hashCode ^
      home.hashCode ^
      pid.hashCode ^
      canForceStop.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          owned == other.owned &&
          degraded == other.degraded &&
          home == other.home &&
          pid == other.pid &&
          canForceStop == other.canForceStop &&
          lastError == other.lastError;
}

/// A diagnosis, when one was taken.
///
/// Absent when the Space could not be asked — which is *not* the same as every
/// gate passing, and is the whole reason this is an `Option` rather than an
/// empty list of gates.
class DiagnosisRow {
  final List<GateRow> gates;

  /// The first non-passing gate: the one actionable blocker.
  final String? blockedOn;
  final String summary;

  const DiagnosisRow({
    required this.gates,
    this.blockedOn,
    required this.summary,
  });

  @override
  int get hashCode => gates.hashCode ^ blockedOn.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisRow &&
          runtimeType == other.runtimeType &&
          gates == other.gates &&
          blockedOn == other.blockedOn &&
          summary == other.summary;
}

class FailureRow {
  final String what;
  final String error;

  /// Whether asking again could plausibly work. A refusal is not a retry.
  final bool retryable;

  const FailureRow({
    required this.what,
    required this.error,
    required this.retryable,
  });

  @override
  int get hashCode => what.hashCode ^ error.hashCode ^ retryable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FailureRow &&
          runtimeType == other.runtimeType &&
          what == other.what &&
          error == other.error &&
          retryable == other.retryable;
}

/// What a gate answered, when a diagnosis was taken.
class GateRow {
  /// Stable machine id — `space`, `daemon`, `membership`, `peer`, `synced`.
  final String id;
  final String label;
  final GateState state;
  final String detail;

  const GateRow({
    required this.id,
    required this.label,
    required this.state,
    required this.detail,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ state.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GateRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          state == other.state &&
          detail == other.detail;
}

/// Five states, not two.
///
/// `Warn` is deliberately not blocking: a key-custody problem is urgent to fix
/// and irrelevant to whether somebody is onboarded, and a warning that hijacked
/// the blocker would tell a joiner they are stuck when they are not.
enum GateState {
  pass,
  wait,
  fail,
  warn,
  skip,
  ;
}

class HeadRow {
  final String id;

  /// Browser or MCP.
  final String kind;

  /// The Orbit it is bound to. `None` is a browser head serving every Orbit
  /// its identity has.
  final String? orbit;

  /// The address, *without* the run credential its URL carries. A front page
  /// has no use for a credential — `Open` mints a single-use ticket of its
  /// own, which is what that ceremony is for.
  final String? origin;
  final bool owned;

  const HeadRow({
    required this.id,
    required this.kind,
    this.orbit,
    this.origin,
    required this.owned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      orbit.hashCode ^
      origin.hashCode ^
      owned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          orbit == other.orbit &&
          origin == other.origin &&
          owned == other.owned;
}

class HostFacts {
  final String version;
  final String identityHome;
  final String spacesRoot;
  final int orbitCount;

  const HostFacts({
    required this.version,
    required this.identityHome,
    required this.spacesRoot,
    required this.orbitCount,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      identityHome.hashCode ^
      spacesRoot.hashCode ^
      orbitCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostFacts &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          identityHome == other.identityHome &&
          spacesRoot == other.spacesRoot &&
          orbitCount == other.orbitCount;
}

/// One row of the Library.
class LibraryRow {
  /// Stable across re-reads: the Orbit and the World in it. A selection
  /// keyed by index would silently follow whatever moved into that position.
  final String key;
  final String orbit;
  final String space;

  /// Empty when the row is the Space itself rather than a World in it.
  final String worldMount;

  /// `None` means nothing authoritative names it. Drawn as unnamed rather
  /// than as an id dressed up as a name.
  final String? displayName;
  final PlacementView placement;

  /// Where `Open` lands. `None` with [`Self::unopenable`] set is a row that
  /// cannot be opened at all.
  final String? opensAt;
  final Unopenable? unopenable;

  /// Wall-clock seconds. `None` is *never opened*, which a zero would
  /// silently turn into 1 January 1970.
  final BigInt? lastOpened;

  /// Where the Orbit's store lives, when the registry could be read.
  final String? store;

  /// Reviewed implementation version for the hosted World.
  final int? version;

  /// The running Orbit's sync gate, kept as transport facts for Dart wording.
  final String? syncState;
  final String? syncDetail;

  /// What the World says about how it should be drawn. Empty for a Space row
  /// and for a World this build does not host — in both cases because nothing
  /// has said anything, which is a fact rather than a blank.
  final String? tagline;

  /// Packed `0xRRGGBB`. A seed the interface derives a plate from locally;
  /// there is no asset here and nothing to fetch.
  final int? accent;

  /// Named places inside the World, already resolved for this Orbit.
  final List<RouteRow> routes;

  const LibraryRow({
    required this.key,
    required this.orbit,
    required this.space,
    required this.worldMount,
    this.displayName,
    required this.placement,
    this.opensAt,
    this.unopenable,
    this.lastOpened,
    this.store,
    this.version,
    this.syncState,
    this.syncDetail,
    this.tagline,
    this.accent,
    required this.routes,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      orbit.hashCode ^
      space.hashCode ^
      worldMount.hashCode ^
      displayName.hashCode ^
      placement.hashCode ^
      opensAt.hashCode ^
      unopenable.hashCode ^
      lastOpened.hashCode ^
      store.hashCode ^
      version.hashCode ^
      syncState.hashCode ^
      syncDetail.hashCode ^
      tagline.hashCode ^
      accent.hashCode ^
      routes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryRow &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          orbit == other.orbit &&
          space == other.space &&
          worldMount == other.worldMount &&
          displayName == other.displayName &&
          placement == other.placement &&
          opensAt == other.opensAt &&
          unopenable == other.unopenable &&
          lastOpened == other.lastOpened &&
          store == other.store &&
          version == other.version &&
          syncState == other.syncState &&
          syncDetail == other.syncDetail &&
          tagline == other.tagline &&
          accent == other.accent &&
          routes == other.routes;
}

class MemberRow {
  final String id;
  final String? nick;

  /// Authored Card name that names this member, when one exists.
  /// Distinct from [`Self::nick`], which is Space-local and derived.
  final String? authoredName;
  final bool admin;

  const MemberRow({
    required this.id,
    this.nick,
    this.authoredName,
    required this.admin,
  });

  @override
  int get hashCode =>
      id.hashCode ^ nick.hashCode ^ authoredName.hashCode ^ admin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nick == other.nick &&
          authoredName == other.authoredName &&
          admin == other.admin;
}

enum Missing {
  /// It is not up. Not an error, and not something a listing corrects —
  /// measuring must not place what nobody asked to place.
  notPlaced,

  /// It could not be asked.
  unreachable,
  ;
}

class NoticeRow {
  final String said;

  /// Where a browser was sent, when that is what happened.
  final String? launched;

  const NoticeRow({
    required this.said,
    this.launched,
  });

  @override
  int get hashCode => said.hashCode ^ launched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoticeRow &&
          runtimeType == other.runtimeType &&
          said == other.said &&
          launched == other.launched;
}

/// One Orbit in this identity's registry.
class OrbitRow {
  final String space;
  final String name;
  final String path;

  /// `None` is never opened, for the same reason it is on a library row.
  final BigInt? lastOpened;

  const OrbitRow({
    required this.space,
    required this.name,
    required this.path,
    this.lastOpened,
  });

  @override
  int get hashCode =>
      space.hashCode ^ name.hashCode ^ path.hashCode ^ lastOpened.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrbitRow &&
          runtimeType == other.runtimeType &&
          space == other.space &&
          name == other.name &&
          path == other.path &&
          lastOpened == other.lastOpened;
}

/// Whether an Orbit is currently up. Three states, because "not running" and
/// "could not be asked" are different facts and only one is worth acting on.
///
/// Named apart from [`crate::client::library::Placement`] on purpose: the
/// codegen flattens type names across the crate and picks between collisions at
/// random, so a DTO that shared a name with a core type would be a coin toss
/// nobody could see land.
enum PlacementView {
  placed,
  vacant,
  unknown,
  ;
}

/// One named place inside a World.
class RouteRow {
  final String label;

  /// Absolute, and resolved: `Open` takes it as it stands.
  final String path;

  const RouteRow({
    required this.label,
    required this.path,
  });

  @override
  int get hashCode => label.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteRow &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          path == other.path;
}

/// The Space somebody is administering, as it last answered.
class SpaceRow {
  final String space;

  /// This actor's standing *here*. Per Orbit rather than per identity: one
  /// identity may hold very different standing in two Spaces, and a single
  /// answer would have to pick one and be wrong about the other.
  final String? whoami;
  final bool admin;
  final List<MemberRow> members;
  final List<String> devices;
  final DiagnosisRow? diagnosis;

  const SpaceRow({
    required this.space,
    this.whoami,
    required this.admin,
    required this.members,
    required this.devices,
    this.diagnosis,
  });

  @override
  int get hashCode =>
      space.hashCode ^
      whoami.hashCode ^
      admin.hashCode ^
      members.hashCode ^
      devices.hashCode ^
      diagnosis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpaceRow &&
          runtimeType == other.runtimeType &&
          space == other.space &&
          whoami == other.whoami &&
          admin == other.admin &&
          members == other.members &&
          devices == other.devices &&
          diagnosis == other.diagnosis;
}

@freezed
sealed class Staleness with _$Staleness {
  const Staleness._();

  /// The first read has not landed.
  const factory Staleness.neverLoaded() = Staleness_NeverLoaded;

  /// The stream said so, and said why.
  const factory Staleness.signalled(
    String field0,
  ) = Staleness_Signalled;
}

/// What one Orbit is holding.
class StorageRow {
  final String orbit;

  /// What the registry calls it. Advisory — a display name is owned by a
  /// World today — and carried as what it is rather than as truth.
  final String? name;

  /// Every figure is optional, and that is the contract. A footprint nobody
  /// could measure is *absent*, never zero: an Orbit reported as holding 0
  /// bytes is a claim, and one nobody asked is not.
  final BigInt? bytesOnDisk;
  final BigInt? objectCount;
  final BigInt? lastVerifiedMs;

  /// Why there are no figures, when there are none. Two reasons, because
  /// "not up" and "could not be asked" are different facts.
  final Missing? missing;

  const StorageRow({
    required this.orbit,
    this.name,
    this.bytesOnDisk,
    this.objectCount,
    this.lastVerifiedMs,
    this.missing,
  });

  @override
  int get hashCode =>
      orbit.hashCode ^
      name.hashCode ^
      bytesOnDisk.hashCode ^
      objectCount.hashCode ^
      lastVerifiedMs.hashCode ^
      missing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageRow &&
          runtimeType == other.runtimeType &&
          orbit == other.orbit &&
          name == other.name &&
          bytesOnDisk == other.bytesOnDisk &&
          objectCount == other.objectCount &&
          lastVerifiedMs == other.lastVerifiedMs &&
          missing == other.missing;
}

/// Why a row cannot be opened. Two facts, not one.
enum Unopenable {
  /// This build hosts no head for that World.
  unhosted,

  /// The World is hosted here and has not declared where to open it.
  undeclared,
  ;
}
