// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class Core extends BaseEntrypoint<CoreApi, CoreApiImpl, CoreWire> {
  @internal
  static final instance = Core._();

  Core._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    CoreApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required CoreApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<CoreApiImpl, CoreWire> get apiImplConstructor =>
      CoreApiImpl.new;

  @override
  WireConstructor<CoreWire> get wireConstructor => CoreWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 489796461;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'astrolabe',
    ioDirectory: '../../tools/astrolabe/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class CoreApi extends BaseApi {
  ClientView crateApiCurrent();

  ClientView crateApiDispatch({required ActionRequest action});

  void crateApiStart({String? stateRoot, String? sidecar});

  Stream<ClientView> crateApiWatch();

  WorldArtwork crateApiWorldArtwork({required String mount});
}

class CoreApiImpl extends CoreApiImplPlatform implements CoreApi {
  CoreApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ClientView crateApiCurrent() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_client_view,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCurrentConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCurrentConstMeta => const TaskConstMeta(
        debugName: "current",
        argNames: [],
      );

  @override
  ClientView crateApiDispatch({required ActionRequest action}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_action_request(action, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_client_view,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDispatchConstMeta,
      argValues: [action],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDispatchConstMeta => const TaskConstMeta(
        debugName: "dispatch",
        argNames: ["action"],
      );

  @override
  void crateApiStart({String? stateRoot, String? sidecar}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(stateRoot, serializer);
        sse_encode_opt_String(sidecar, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiStartConstMeta,
      argValues: [stateRoot, sidecar],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStartConstMeta => const TaskConstMeta(
        debugName: "start",
        argNames: ["stateRoot", "sidecar"],
      );

  @override
  Stream<ClientView> crateApiWatch() {
    final sink = RustStreamSink<ClientView>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_client_view_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWatchConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatchConstMeta => const TaskConstMeta(
        debugName: "watch",
        argNames: ["sink"],
      );

  @override
  WorldArtwork crateApiWorldArtwork({required String mount}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mount, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_world_artwork,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWorldArtworkConstMeta,
      argValues: [mount],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWorldArtworkConstMeta => const TaskConstMeta(
        debugName: "world_artwork",
        argNames: ["mount"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ClientView> dco_decode_StreamSink_client_view_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ViewPush dco_decode_TraitDef_ViewPush(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ActionRequest dco_decode_action_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ActionRequest_Refresh();
      case 1:
        return ActionRequest_Open(
          entryPath: dco_decode_String(raw[1]),
        );
      case 2:
        return ActionRequest_StartDevice(
          id: dco_decode_String(raw[1]),
        );
      case 3:
        return ActionRequest_StopDevice(
          id: dco_decode_String(raw[1]),
        );
      case 4:
        return ActionRequest_RestartDevice(
          id: dco_decode_String(raw[1]),
        );
      case 5:
        return ActionRequest_ForceStopDevice(
          id: dco_decode_String(raw[1]),
        );
      case 6:
        return ActionRequest_StopAllOwned();
      case 7:
        return ActionRequest_RemoveDevice(
          id: dco_decode_String(raw[1]),
          deleteData: dco_decode_bool(raw[2]),
        );
      case 8:
        return ActionRequest_ReadSpace(
          orbit: dco_decode_String(raw[1]),
        );
      case 9:
        return ActionRequest_StartHead();
      case 10:
        return ActionRequest_StopHead(
          id: dco_decode_String(raw[1]),
        );
      case 11:
        return ActionRequest_ForgetOrbit(
          space: dco_decode_String(raw[1]),
        );
      case 12:
        return ActionRequest_BookPut(
          card: dco_decode_opt_String(raw[1]),
          name: dco_decode_String(raw[2]),
          note: dco_decode_opt_String(raw[3]),
        );
      case 13:
        return ActionRequest_BookDelete(
          card: dco_decode_String(raw[1]),
        );
      case 14:
        return ActionRequest_BookSetPicture(
          card: dco_decode_String(raw[1]),
          path: dco_decode_opt_String(raw[2]),
        );
      case 15:
        return ActionRequest_BookMerge(
          from: dco_decode_String(raw[1]),
          into: dco_decode_String(raw[2]),
        );
      case 16:
        return ActionRequest_BookClaimSelf(
          card: dco_decode_String(raw[1]),
        );
      case 17:
        return ActionRequest_BookLink(
          card: dco_decode_String(raw[1]),
          handle: dco_decode_String(raw[2]),
        );
      case 18:
        return ActionRequest_BookUnlink(
          card: dco_decode_String(raw[1]),
          handle: dco_decode_String(raw[2]),
        );
      case 19:
        return ActionRequest_BookExport(
          path: dco_decode_String(raw[1]),
          cards: dco_decode_opt_list_String(raw[2]),
        );
      case 20:
        return ActionRequest_BookImport(
          path: dco_decode_String(raw[1]),
        );
      case 21:
        return ActionRequest_BookAccept(
          suggestion: dco_decode_String(raw[1]),
        );
      case 22:
        return ActionRequest_BookDismiss(
          suggestion: dco_decode_String(raw[1]),
        );
      case 23:
        return ActionRequest_InstallMcp(
          client: dco_decode_String(raw[1]),
          scope: dco_decode_opt_String(raw[2]),
          name: dco_decode_String(raw[3]),
          agent: dco_decode_opt_String(raw[4]),
          noAgent: dco_decode_bool(raw[5]),
          project: dco_decode_String(raw[6]),
          world: dco_decode_opt_String(raw[7]),
          preview: dco_decode_bool(raw[8]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BookFacts dco_decode_book_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BookFacts(
      cards: dco_decode_list_card_row(arr[0]),
      migrationComplete: dco_decode_bool(arr[1]),
      migrationPending: dco_decode_u_32(arr[2]),
      migrationImported: dco_decode_u_32(arr[3]),
      suggestions: dco_decode_list_suggestion_row(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ActionRequest dco_decode_box_autoadd_action_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_action_request(raw);
  }

  @protected
  BookFacts dco_decode_box_autoadd_book_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_book_facts(raw);
  }

  @protected
  ClientView dco_decode_box_autoadd_client_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_client_view(raw);
  }

  @protected
  DiagnosisRow dco_decode_box_autoadd_diagnosis_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_diagnosis_row(raw);
  }

  @protected
  HostFacts dco_decode_box_autoadd_host_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_host_facts(raw);
  }

  @protected
  McpBindingRow dco_decode_box_autoadd_mcp_binding_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mcp_binding_row(raw);
  }

  @protected
  Missing dco_decode_box_autoadd_missing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_missing(raw);
  }

  @protected
  PresenceView dco_decode_box_autoadd_presence_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_presence_view(raw);
  }

  @protected
  SpaceRow dco_decode_box_autoadd_space_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_space_row(raw);
  }

  @protected
  Staleness dco_decode_box_autoadd_staleness(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_staleness(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  CardRow dco_decode_card_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return CardRow(
      card: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      note: dco_decode_String(arr[2]),
      handles: dco_decode_list_String(arr[3]),
      addresses: dco_decode_list_String(arr[4]),
      devices: dco_decode_list_String(arr[5]),
      agents: dco_decode_list_String(arr[6]),
      picture: dco_decode_opt_String(arr[7]),
      groups: dco_decode_list_String(arr[8]),
      selfClaim: dco_decode_bool(arr[9]),
      presence: dco_decode_opt_box_autoadd_presence_view(arr[10]),
    );
  }

  @protected
  ClientView dco_decode_client_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ClientView(
      loading: dco_decode_bool(arr[0]),
      stale: dco_decode_opt_box_autoadd_staleness(arr[1]),
      library_: dco_decode_opt_list_library_row(arr[2]),
      host: dco_decode_opt_box_autoadd_host_facts(arr[3]),
      heads: dco_decode_list_head_row(arr[4]),
      devices: dco_decode_list_device_row(arr[5]),
      storage: dco_decode_list_storage_row(arr[6]),
      orbits: dco_decode_list_orbit_row(arr[7]),
      space: dco_decode_opt_box_autoadd_space_row(arr[8]),
      book: dco_decode_opt_box_autoadd_book_facts(arr[9]),
      notices: dco_decode_list_notice_row(arr[10]),
      failures: dco_decode_list_failure_row(arr[11]),
      inFlight: dco_decode_list_String(arr[12]),
      mcp: dco_decode_opt_box_autoadd_mcp_binding_row(arr[13]),
    );
  }

  @protected
  DeviceRow dco_decode_device_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DeviceRow(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      state: dco_decode_String(arr[2]),
      owned: dco_decode_bool(arr[3]),
      degraded: dco_decode_opt_String(arr[4]),
      home: dco_decode_String(arr[5]),
      pid: dco_decode_opt_box_autoadd_u_32(arr[6]),
      canForceStop: dco_decode_bool(arr[7]),
      lastError: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  DiagnosisRow dco_decode_diagnosis_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DiagnosisRow(
      gates: dco_decode_list_gate_row(arr[0]),
      blockedOn: dco_decode_opt_String(arr[1]),
      summary: dco_decode_String(arr[2]),
    );
  }

  @protected
  FailureRow dco_decode_failure_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FailureRow(
      what: dco_decode_String(arr[0]),
      error: dco_decode_String(arr[1]),
      retryable: dco_decode_bool(arr[2]),
    );
  }

  @protected
  GateRow dco_decode_gate_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GateRow(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      state: dco_decode_gate_state(arr[2]),
      detail: dco_decode_String(arr[3]),
    );
  }

  @protected
  GateState dco_decode_gate_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GateState.values[raw as int];
  }

  @protected
  HeadRow dco_decode_head_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HeadRow(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      orbit: dco_decode_opt_String(arr[2]),
      origin: dco_decode_opt_String(arr[3]),
      owned: dco_decode_bool(arr[4]),
    );
  }

  @protected
  HostFacts dco_decode_host_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HostFacts(
      version: dco_decode_String(arr[0]),
      identityHome: dco_decode_String(arr[1]),
      spacesRoot: dco_decode_String(arr[2]),
      orbitCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LibraryRow dco_decode_library_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LibraryRow(
      key: dco_decode_String(arr[0]),
      worldMount: dco_decode_String(arr[1]),
      displayName: dco_decode_String(arr[2]),
      opensAt: dco_decode_opt_String(arr[3]),
      version: dco_decode_opt_box_autoadd_u_32(arr[4]),
      tagline: dco_decode_opt_String(arr[5]),
      accent: dco_decode_opt_box_autoadd_u_32(arr[6]),
      people: dco_decode_opt_list_world_person_row(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CardRow> dco_decode_list_card_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_card_row).toList();
  }

  @protected
  List<DeviceRow> dco_decode_list_device_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_row).toList();
  }

  @protected
  List<FailureRow> dco_decode_list_failure_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_failure_row).toList();
  }

  @protected
  List<GateRow> dco_decode_list_gate_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gate_row).toList();
  }

  @protected
  List<HeadRow> dco_decode_list_head_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_head_row).toList();
  }

  @protected
  List<LibraryRow> dco_decode_list_library_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_library_row).toList();
  }

  @protected
  List<MemberRow> dco_decode_list_member_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_row).toList();
  }

  @protected
  List<NoticeRow> dco_decode_list_notice_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_notice_row).toList();
  }

  @protected
  List<OrbitRow> dco_decode_list_orbit_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_orbit_row).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StorageRow> dco_decode_list_storage_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_storage_row).toList();
  }

  @protected
  List<SuggestionRow> dco_decode_list_suggestion_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_suggestion_row).toList();
  }

  @protected
  List<WorldPersonRow> dco_decode_list_world_person_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_world_person_row).toList();
  }

  @protected
  McpBindingRow dco_decode_mcp_binding_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return McpBindingRow(
      path: dco_decode_String(arr[0]),
      detail: dco_decode_String(arr[1]),
      note: dco_decode_opt_String(arr[2]),
      replaced: dco_decode_bool(arr[3]),
      agent: dco_decode_opt_String(arr[4]),
      written: dco_decode_bool(arr[5]),
      world: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  MemberRow dco_decode_member_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MemberRow(
      id: dco_decode_String(arr[0]),
      nick: dco_decode_opt_String(arr[1]),
      authoredName: dco_decode_opt_String(arr[2]),
      admin: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Missing dco_decode_missing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Missing.values[raw as int];
  }

  @protected
  NoticeRow dco_decode_notice_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NoticeRow(
      said: dco_decode_String(arr[0]),
      launched: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BookFacts? dco_decode_opt_box_autoadd_book_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_book_facts(raw);
  }

  @protected
  DiagnosisRow? dco_decode_opt_box_autoadd_diagnosis_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_diagnosis_row(raw);
  }

  @protected
  HostFacts? dco_decode_opt_box_autoadd_host_facts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_host_facts(raw);
  }

  @protected
  McpBindingRow? dco_decode_opt_box_autoadd_mcp_binding_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mcp_binding_row(raw);
  }

  @protected
  Missing? dco_decode_opt_box_autoadd_missing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_missing(raw);
  }

  @protected
  PresenceView? dco_decode_opt_box_autoadd_presence_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_presence_view(raw);
  }

  @protected
  SpaceRow? dco_decode_opt_box_autoadd_space_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_space_row(raw);
  }

  @protected
  Staleness? dco_decode_opt_box_autoadd_staleness(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_staleness(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  List<LibraryRow>? dco_decode_opt_list_library_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_library_row(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  List<WorldPersonRow>? dco_decode_opt_list_world_person_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_world_person_row(raw);
  }

  @protected
  OrbitRow dco_decode_orbit_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OrbitRow(
      space: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      lastOpened: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  PresenceView dco_decode_presence_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PresenceView.values[raw as int];
  }

  @protected
  SpaceRow dco_decode_space_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SpaceRow(
      space: dco_decode_String(arr[0]),
      whoami: dco_decode_opt_String(arr[1]),
      admin: dco_decode_bool(arr[2]),
      members: dco_decode_list_member_row(arr[3]),
      devices: dco_decode_list_String(arr[4]),
      diagnosis: dco_decode_opt_box_autoadd_diagnosis_row(arr[5]),
    );
  }

  @protected
  Staleness dco_decode_staleness(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Staleness_NeverLoaded();
      case 1:
        return Staleness_Signalled(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  StorageRow dco_decode_storage_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return StorageRow(
      orbit: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      bytesOnDisk: dco_decode_opt_box_autoadd_u_64(arr[2]),
      objectCount: dco_decode_opt_box_autoadd_u_64(arr[3]),
      lastVerifiedMs: dco_decode_opt_box_autoadd_u_64(arr[4]),
      missing: dco_decode_opt_box_autoadd_missing(arr[5]),
    );
  }

  @protected
  SuggestionRow dco_decode_suggestion_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SuggestionRow(
      suggestion: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      note: dco_decode_String(arr[2]),
      handles: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorldArtwork dco_decode_world_artwork(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WorldArtwork(
      mark: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      hero: dco_decode_opt_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  WorldPersonRow dco_decode_world_person_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WorldPersonRow(
      name: dco_decode_String(arr[0]),
      picture: dco_decode_opt_String(arr[1]),
      presence: dco_decode_opt_box_autoadd_presence_view(arr[2]),
      agent: dco_decode_bool(arr[3]),
      here: dco_decode_bool(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ClientView> sse_decode_StreamSink_client_view_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActionRequest sse_decode_action_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ActionRequest_Refresh();
      case 1:
        var var_entryPath = sse_decode_String(deserializer);
        return ActionRequest_Open(entryPath: var_entryPath);
      case 2:
        var var_id = sse_decode_String(deserializer);
        return ActionRequest_StartDevice(id: var_id);
      case 3:
        var var_id = sse_decode_String(deserializer);
        return ActionRequest_StopDevice(id: var_id);
      case 4:
        var var_id = sse_decode_String(deserializer);
        return ActionRequest_RestartDevice(id: var_id);
      case 5:
        var var_id = sse_decode_String(deserializer);
        return ActionRequest_ForceStopDevice(id: var_id);
      case 6:
        return ActionRequest_StopAllOwned();
      case 7:
        var var_id = sse_decode_String(deserializer);
        var var_deleteData = sse_decode_bool(deserializer);
        return ActionRequest_RemoveDevice(
            id: var_id, deleteData: var_deleteData);
      case 8:
        var var_orbit = sse_decode_String(deserializer);
        return ActionRequest_ReadSpace(orbit: var_orbit);
      case 9:
        return ActionRequest_StartHead();
      case 10:
        var var_id = sse_decode_String(deserializer);
        return ActionRequest_StopHead(id: var_id);
      case 11:
        var var_space = sse_decode_String(deserializer);
        return ActionRequest_ForgetOrbit(space: var_space);
      case 12:
        var var_card = sse_decode_opt_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_note = sse_decode_opt_String(deserializer);
        return ActionRequest_BookPut(
            card: var_card, name: var_name, note: var_note);
      case 13:
        var var_card = sse_decode_String(deserializer);
        return ActionRequest_BookDelete(card: var_card);
      case 14:
        var var_card = sse_decode_String(deserializer);
        var var_path = sse_decode_opt_String(deserializer);
        return ActionRequest_BookSetPicture(card: var_card, path: var_path);
      case 15:
        var var_from = sse_decode_String(deserializer);
        var var_into = sse_decode_String(deserializer);
        return ActionRequest_BookMerge(from: var_from, into: var_into);
      case 16:
        var var_card = sse_decode_String(deserializer);
        return ActionRequest_BookClaimSelf(card: var_card);
      case 17:
        var var_card = sse_decode_String(deserializer);
        var var_handle = sse_decode_String(deserializer);
        return ActionRequest_BookLink(card: var_card, handle: var_handle);
      case 18:
        var var_card = sse_decode_String(deserializer);
        var var_handle = sse_decode_String(deserializer);
        return ActionRequest_BookUnlink(card: var_card, handle: var_handle);
      case 19:
        var var_path = sse_decode_String(deserializer);
        var var_cards = sse_decode_opt_list_String(deserializer);
        return ActionRequest_BookExport(path: var_path, cards: var_cards);
      case 20:
        var var_path = sse_decode_String(deserializer);
        return ActionRequest_BookImport(path: var_path);
      case 21:
        var var_suggestion = sse_decode_String(deserializer);
        return ActionRequest_BookAccept(suggestion: var_suggestion);
      case 22:
        var var_suggestion = sse_decode_String(deserializer);
        return ActionRequest_BookDismiss(suggestion: var_suggestion);
      case 23:
        var var_client = sse_decode_String(deserializer);
        var var_scope = sse_decode_opt_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        var var_agent = sse_decode_opt_String(deserializer);
        var var_noAgent = sse_decode_bool(deserializer);
        var var_project = sse_decode_String(deserializer);
        var var_world = sse_decode_opt_String(deserializer);
        var var_preview = sse_decode_bool(deserializer);
        return ActionRequest_InstallMcp(
            client: var_client,
            scope: var_scope,
            name: var_name,
            agent: var_agent,
            noAgent: var_noAgent,
            project: var_project,
            world: var_world,
            preview: var_preview);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BookFacts sse_decode_book_facts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cards = sse_decode_list_card_row(deserializer);
    var var_migrationComplete = sse_decode_bool(deserializer);
    var var_migrationPending = sse_decode_u_32(deserializer);
    var var_migrationImported = sse_decode_u_32(deserializer);
    var var_suggestions = sse_decode_list_suggestion_row(deserializer);
    return BookFacts(
        cards: var_cards,
        migrationComplete: var_migrationComplete,
        migrationPending: var_migrationPending,
        migrationImported: var_migrationImported,
        suggestions: var_suggestions);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ActionRequest sse_decode_box_autoadd_action_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_action_request(deserializer));
  }

  @protected
  BookFacts sse_decode_box_autoadd_book_facts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_book_facts(deserializer));
  }

  @protected
  ClientView sse_decode_box_autoadd_client_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_client_view(deserializer));
  }

  @protected
  DiagnosisRow sse_decode_box_autoadd_diagnosis_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_diagnosis_row(deserializer));
  }

  @protected
  HostFacts sse_decode_box_autoadd_host_facts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_host_facts(deserializer));
  }

  @protected
  McpBindingRow sse_decode_box_autoadd_mcp_binding_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mcp_binding_row(deserializer));
  }

  @protected
  Missing sse_decode_box_autoadd_missing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_missing(deserializer));
  }

  @protected
  PresenceView sse_decode_box_autoadd_presence_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_presence_view(deserializer));
  }

  @protected
  SpaceRow sse_decode_box_autoadd_space_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_space_row(deserializer));
  }

  @protected
  Staleness sse_decode_box_autoadd_staleness(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_staleness(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  CardRow sse_decode_card_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_card = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_handles = sse_decode_list_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    var var_devices = sse_decode_list_String(deserializer);
    var var_agents = sse_decode_list_String(deserializer);
    var var_picture = sse_decode_opt_String(deserializer);
    var var_groups = sse_decode_list_String(deserializer);
    var var_selfClaim = sse_decode_bool(deserializer);
    var var_presence = sse_decode_opt_box_autoadd_presence_view(deserializer);
    return CardRow(
        card: var_card,
        name: var_name,
        note: var_note,
        handles: var_handles,
        addresses: var_addresses,
        devices: var_devices,
        agents: var_agents,
        picture: var_picture,
        groups: var_groups,
        selfClaim: var_selfClaim,
        presence: var_presence);
  }

  @protected
  ClientView sse_decode_client_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loading = sse_decode_bool(deserializer);
    var var_stale = sse_decode_opt_box_autoadd_staleness(deserializer);
    var var_library_ = sse_decode_opt_list_library_row(deserializer);
    var var_host = sse_decode_opt_box_autoadd_host_facts(deserializer);
    var var_heads = sse_decode_list_head_row(deserializer);
    var var_devices = sse_decode_list_device_row(deserializer);
    var var_storage = sse_decode_list_storage_row(deserializer);
    var var_orbits = sse_decode_list_orbit_row(deserializer);
    var var_space = sse_decode_opt_box_autoadd_space_row(deserializer);
    var var_book = sse_decode_opt_box_autoadd_book_facts(deserializer);
    var var_notices = sse_decode_list_notice_row(deserializer);
    var var_failures = sse_decode_list_failure_row(deserializer);
    var var_inFlight = sse_decode_list_String(deserializer);
    var var_mcp = sse_decode_opt_box_autoadd_mcp_binding_row(deserializer);
    return ClientView(
        loading: var_loading,
        stale: var_stale,
        library_: var_library_,
        host: var_host,
        heads: var_heads,
        devices: var_devices,
        storage: var_storage,
        orbits: var_orbits,
        space: var_space,
        book: var_book,
        notices: var_notices,
        failures: var_failures,
        inFlight: var_inFlight,
        mcp: var_mcp);
  }

  @protected
  DeviceRow sse_decode_device_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_owned = sse_decode_bool(deserializer);
    var var_degraded = sse_decode_opt_String(deserializer);
    var var_home = sse_decode_String(deserializer);
    var var_pid = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_canForceStop = sse_decode_bool(deserializer);
    var var_lastError = sse_decode_opt_String(deserializer);
    return DeviceRow(
        id: var_id,
        label: var_label,
        state: var_state,
        owned: var_owned,
        degraded: var_degraded,
        home: var_home,
        pid: var_pid,
        canForceStop: var_canForceStop,
        lastError: var_lastError);
  }

  @protected
  DiagnosisRow sse_decode_diagnosis_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gates = sse_decode_list_gate_row(deserializer);
    var var_blockedOn = sse_decode_opt_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    return DiagnosisRow(
        gates: var_gates, blockedOn: var_blockedOn, summary: var_summary);
  }

  @protected
  FailureRow sse_decode_failure_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_what = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    var var_retryable = sse_decode_bool(deserializer);
    return FailureRow(
        what: var_what, error: var_error, retryable: var_retryable);
  }

  @protected
  GateRow sse_decode_gate_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_state = sse_decode_gate_state(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return GateRow(
        id: var_id, label: var_label, state: var_state, detail: var_detail);
  }

  @protected
  GateState sse_decode_gate_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GateState.values[inner];
  }

  @protected
  HeadRow sse_decode_head_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_orbit = sse_decode_opt_String(deserializer);
    var var_origin = sse_decode_opt_String(deserializer);
    var var_owned = sse_decode_bool(deserializer);
    return HeadRow(
        id: var_id,
        kind: var_kind,
        orbit: var_orbit,
        origin: var_origin,
        owned: var_owned);
  }

  @protected
  HostFacts sse_decode_host_facts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_identityHome = sse_decode_String(deserializer);
    var var_spacesRoot = sse_decode_String(deserializer);
    var var_orbitCount = sse_decode_u_32(deserializer);
    return HostFacts(
        version: var_version,
        identityHome: var_identityHome,
        spacesRoot: var_spacesRoot,
        orbitCount: var_orbitCount);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LibraryRow sse_decode_library_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_worldMount = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_opensAt = sse_decode_opt_String(deserializer);
    var var_version = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_tagline = sse_decode_opt_String(deserializer);
    var var_accent = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_people = sse_decode_opt_list_world_person_row(deserializer);
    return LibraryRow(
        key: var_key,
        worldMount: var_worldMount,
        displayName: var_displayName,
        opensAt: var_opensAt,
        version: var_version,
        tagline: var_tagline,
        accent: var_accent,
        people: var_people);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CardRow> sse_decode_list_card_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CardRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_card_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceRow> sse_decode_list_device_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<FailureRow> sse_decode_list_failure_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FailureRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_failure_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<GateRow> sse_decode_list_gate_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GateRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gate_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeadRow> sse_decode_list_head_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeadRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_head_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<LibraryRow> sse_decode_list_library_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LibraryRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_library_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberRow> sse_decode_list_member_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoticeRow> sse_decode_list_notice_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoticeRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_notice_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<OrbitRow> sse_decode_list_orbit_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OrbitRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_orbit_row(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StorageRow> sse_decode_list_storage_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StorageRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_storage_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<SuggestionRow> sse_decode_list_suggestion_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SuggestionRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_suggestion_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<WorldPersonRow> sse_decode_list_world_person_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorldPersonRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_world_person_row(deserializer));
    }
    return ans_;
  }

  @protected
  McpBindingRow sse_decode_mcp_binding_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_note = sse_decode_opt_String(deserializer);
    var var_replaced = sse_decode_bool(deserializer);
    var var_agent = sse_decode_opt_String(deserializer);
    var var_written = sse_decode_bool(deserializer);
    var var_world = sse_decode_opt_String(deserializer);
    return McpBindingRow(
        path: var_path,
        detail: var_detail,
        note: var_note,
        replaced: var_replaced,
        agent: var_agent,
        written: var_written,
        world: var_world);
  }

  @protected
  MemberRow sse_decode_member_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_nick = sse_decode_opt_String(deserializer);
    var var_authoredName = sse_decode_opt_String(deserializer);
    var var_admin = sse_decode_bool(deserializer);
    return MemberRow(
        id: var_id,
        nick: var_nick,
        authoredName: var_authoredName,
        admin: var_admin);
  }

  @protected
  Missing sse_decode_missing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Missing.values[inner];
  }

  @protected
  NoticeRow sse_decode_notice_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_said = sse_decode_String(deserializer);
    var var_launched = sse_decode_opt_String(deserializer);
    return NoticeRow(said: var_said, launched: var_launched);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BookFacts? sse_decode_opt_box_autoadd_book_facts(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_book_facts(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DiagnosisRow? sse_decode_opt_box_autoadd_diagnosis_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_diagnosis_row(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HostFacts? sse_decode_opt_box_autoadd_host_facts(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_host_facts(deserializer));
    } else {
      return null;
    }
  }

  @protected
  McpBindingRow? sse_decode_opt_box_autoadd_mcp_binding_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mcp_binding_row(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Missing? sse_decode_opt_box_autoadd_missing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_missing(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PresenceView? sse_decode_opt_box_autoadd_presence_view(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_presence_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SpaceRow? sse_decode_opt_box_autoadd_space_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_space_row(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Staleness? sse_decode_opt_box_autoadd_staleness(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_staleness(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<LibraryRow>? sse_decode_opt_list_library_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_library_row(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<WorldPersonRow>? sse_decode_opt_list_world_person_row(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_world_person_row(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OrbitRow sse_decode_orbit_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_space = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_lastOpened = sse_decode_opt_box_autoadd_u_64(deserializer);
    return OrbitRow(
        space: var_space,
        name: var_name,
        path: var_path,
        lastOpened: var_lastOpened);
  }

  @protected
  PresenceView sse_decode_presence_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PresenceView.values[inner];
  }

  @protected
  SpaceRow sse_decode_space_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_space = sse_decode_String(deserializer);
    var var_whoami = sse_decode_opt_String(deserializer);
    var var_admin = sse_decode_bool(deserializer);
    var var_members = sse_decode_list_member_row(deserializer);
    var var_devices = sse_decode_list_String(deserializer);
    var var_diagnosis = sse_decode_opt_box_autoadd_diagnosis_row(deserializer);
    return SpaceRow(
        space: var_space,
        whoami: var_whoami,
        admin: var_admin,
        members: var_members,
        devices: var_devices,
        diagnosis: var_diagnosis);
  }

  @protected
  Staleness sse_decode_staleness(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return Staleness_NeverLoaded();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return Staleness_Signalled(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  StorageRow sse_decode_storage_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orbit = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_bytesOnDisk = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_objectCount = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_lastVerifiedMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_missing = sse_decode_opt_box_autoadd_missing(deserializer);
    return StorageRow(
        orbit: var_orbit,
        name: var_name,
        bytesOnDisk: var_bytesOnDisk,
        objectCount: var_objectCount,
        lastVerifiedMs: var_lastVerifiedMs,
        missing: var_missing);
  }

  @protected
  SuggestionRow sse_decode_suggestion_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_suggestion = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_handles = sse_decode_list_String(deserializer);
    return SuggestionRow(
        suggestion: var_suggestion,
        name: var_name,
        note: var_note,
        handles: var_handles);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorldArtwork sse_decode_world_artwork(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mark = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_hero = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return WorldArtwork(mark: var_mark, hero: var_hero);
  }

  @protected
  WorldPersonRow sse_decode_world_person_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_picture = sse_decode_opt_String(deserializer);
    var var_presence = sse_decode_opt_box_autoadd_presence_view(deserializer);
    var var_agent = sse_decode_bool(deserializer);
    var var_here = sse_decode_bool(deserializer);
    return WorldPersonRow(
        name: var_name,
        picture: var_picture,
        presence: var_presence,
        agent: var_agent,
        here: var_here);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_client_view_Sse(
      RustStreamSink<ClientView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_client_view,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_action_request(ActionRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ActionRequest_Refresh():
        sse_encode_i_32(0, serializer);
      case ActionRequest_Open(entryPath: final entryPath):
        sse_encode_i_32(1, serializer);
        sse_encode_String(entryPath, serializer);
      case ActionRequest_StartDevice(id: final id):
        sse_encode_i_32(2, serializer);
        sse_encode_String(id, serializer);
      case ActionRequest_StopDevice(id: final id):
        sse_encode_i_32(3, serializer);
        sse_encode_String(id, serializer);
      case ActionRequest_RestartDevice(id: final id):
        sse_encode_i_32(4, serializer);
        sse_encode_String(id, serializer);
      case ActionRequest_ForceStopDevice(id: final id):
        sse_encode_i_32(5, serializer);
        sse_encode_String(id, serializer);
      case ActionRequest_StopAllOwned():
        sse_encode_i_32(6, serializer);
      case ActionRequest_RemoveDevice(
          id: final id,
          deleteData: final deleteData
        ):
        sse_encode_i_32(7, serializer);
        sse_encode_String(id, serializer);
        sse_encode_bool(deleteData, serializer);
      case ActionRequest_ReadSpace(orbit: final orbit):
        sse_encode_i_32(8, serializer);
        sse_encode_String(orbit, serializer);
      case ActionRequest_StartHead():
        sse_encode_i_32(9, serializer);
      case ActionRequest_StopHead(id: final id):
        sse_encode_i_32(10, serializer);
        sse_encode_String(id, serializer);
      case ActionRequest_ForgetOrbit(space: final space):
        sse_encode_i_32(11, serializer);
        sse_encode_String(space, serializer);
      case ActionRequest_BookPut(
          card: final card,
          name: final name,
          note: final note
        ):
        sse_encode_i_32(12, serializer);
        sse_encode_opt_String(card, serializer);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(note, serializer);
      case ActionRequest_BookDelete(card: final card):
        sse_encode_i_32(13, serializer);
        sse_encode_String(card, serializer);
      case ActionRequest_BookSetPicture(card: final card, path: final path):
        sse_encode_i_32(14, serializer);
        sse_encode_String(card, serializer);
        sse_encode_opt_String(path, serializer);
      case ActionRequest_BookMerge(from: final from, into: final into):
        sse_encode_i_32(15, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(into, serializer);
      case ActionRequest_BookClaimSelf(card: final card):
        sse_encode_i_32(16, serializer);
        sse_encode_String(card, serializer);
      case ActionRequest_BookLink(card: final card, handle: final handle):
        sse_encode_i_32(17, serializer);
        sse_encode_String(card, serializer);
        sse_encode_String(handle, serializer);
      case ActionRequest_BookUnlink(card: final card, handle: final handle):
        sse_encode_i_32(18, serializer);
        sse_encode_String(card, serializer);
        sse_encode_String(handle, serializer);
      case ActionRequest_BookExport(path: final path, cards: final cards):
        sse_encode_i_32(19, serializer);
        sse_encode_String(path, serializer);
        sse_encode_opt_list_String(cards, serializer);
      case ActionRequest_BookImport(path: final path):
        sse_encode_i_32(20, serializer);
        sse_encode_String(path, serializer);
      case ActionRequest_BookAccept(suggestion: final suggestion):
        sse_encode_i_32(21, serializer);
        sse_encode_String(suggestion, serializer);
      case ActionRequest_BookDismiss(suggestion: final suggestion):
        sse_encode_i_32(22, serializer);
        sse_encode_String(suggestion, serializer);
      case ActionRequest_InstallMcp(
          client: final client,
          scope: final scope,
          name: final name,
          agent: final agent,
          noAgent: final noAgent,
          project: final project,
          world: final world,
          preview: final preview
        ):
        sse_encode_i_32(23, serializer);
        sse_encode_String(client, serializer);
        sse_encode_opt_String(scope, serializer);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(agent, serializer);
        sse_encode_bool(noAgent, serializer);
        sse_encode_String(project, serializer);
        sse_encode_opt_String(world, serializer);
        sse_encode_bool(preview, serializer);
    }
  }

  @protected
  void sse_encode_book_facts(BookFacts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_card_row(self.cards, serializer);
    sse_encode_bool(self.migrationComplete, serializer);
    sse_encode_u_32(self.migrationPending, serializer);
    sse_encode_u_32(self.migrationImported, serializer);
    sse_encode_list_suggestion_row(self.suggestions, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_action_request(
      ActionRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_action_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_book_facts(
      BookFacts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book_facts(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_client_view(
      ClientView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_client_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_diagnosis_row(
      DiagnosisRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_diagnosis_row(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_host_facts(
      HostFacts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_host_facts(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mcp_binding_row(
      McpBindingRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mcp_binding_row(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_missing(Missing self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_missing(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_presence_view(
      PresenceView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_presence_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_space_row(
      SpaceRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_space_row(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_staleness(
      Staleness self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_staleness(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_card_row(CardRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.card, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_list_String(self.handles, serializer);
    sse_encode_list_String(self.addresses, serializer);
    sse_encode_list_String(self.devices, serializer);
    sse_encode_list_String(self.agents, serializer);
    sse_encode_opt_String(self.picture, serializer);
    sse_encode_list_String(self.groups, serializer);
    sse_encode_bool(self.selfClaim, serializer);
    sse_encode_opt_box_autoadd_presence_view(self.presence, serializer);
  }

  @protected
  void sse_encode_client_view(ClientView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loading, serializer);
    sse_encode_opt_box_autoadd_staleness(self.stale, serializer);
    sse_encode_opt_list_library_row(self.library_, serializer);
    sse_encode_opt_box_autoadd_host_facts(self.host, serializer);
    sse_encode_list_head_row(self.heads, serializer);
    sse_encode_list_device_row(self.devices, serializer);
    sse_encode_list_storage_row(self.storage, serializer);
    sse_encode_list_orbit_row(self.orbits, serializer);
    sse_encode_opt_box_autoadd_space_row(self.space, serializer);
    sse_encode_opt_box_autoadd_book_facts(self.book, serializer);
    sse_encode_list_notice_row(self.notices, serializer);
    sse_encode_list_failure_row(self.failures, serializer);
    sse_encode_list_String(self.inFlight, serializer);
    sse_encode_opt_box_autoadd_mcp_binding_row(self.mcp, serializer);
  }

  @protected
  void sse_encode_device_row(DeviceRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_bool(self.owned, serializer);
    sse_encode_opt_String(self.degraded, serializer);
    sse_encode_String(self.home, serializer);
    sse_encode_opt_box_autoadd_u_32(self.pid, serializer);
    sse_encode_bool(self.canForceStop, serializer);
    sse_encode_opt_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_diagnosis_row(DiagnosisRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_gate_row(self.gates, serializer);
    sse_encode_opt_String(self.blockedOn, serializer);
    sse_encode_String(self.summary, serializer);
  }

  @protected
  void sse_encode_failure_row(FailureRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.what, serializer);
    sse_encode_String(self.error, serializer);
    sse_encode_bool(self.retryable, serializer);
  }

  @protected
  void sse_encode_gate_row(GateRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_gate_state(self.state, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_gate_state(GateState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_head_row(HeadRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.orbit, serializer);
    sse_encode_opt_String(self.origin, serializer);
    sse_encode_bool(self.owned, serializer);
  }

  @protected
  void sse_encode_host_facts(HostFacts self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.identityHome, serializer);
    sse_encode_String(self.spacesRoot, serializer);
    sse_encode_u_32(self.orbitCount, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_library_row(LibraryRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.worldMount, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.opensAt, serializer);
    sse_encode_opt_box_autoadd_u_32(self.version, serializer);
    sse_encode_opt_String(self.tagline, serializer);
    sse_encode_opt_box_autoadd_u_32(self.accent, serializer);
    sse_encode_opt_list_world_person_row(self.people, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_card_row(List<CardRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_card_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_row(
      List<DeviceRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_failure_row(
      List<FailureRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_failure_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gate_row(List<GateRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gate_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_head_row(List<HeadRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_head_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_library_row(
      List<LibraryRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_library_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_row(
      List<MemberRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_notice_row(
      List<NoticeRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_notice_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_orbit_row(
      List<OrbitRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_orbit_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_storage_row(
      List<StorageRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_storage_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_suggestion_row(
      List<SuggestionRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_suggestion_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_world_person_row(
      List<WorldPersonRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_world_person_row(item, serializer);
    }
  }

  @protected
  void sse_encode_mcp_binding_row(
      McpBindingRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_opt_String(self.note, serializer);
    sse_encode_bool(self.replaced, serializer);
    sse_encode_opt_String(self.agent, serializer);
    sse_encode_bool(self.written, serializer);
    sse_encode_opt_String(self.world, serializer);
  }

  @protected
  void sse_encode_member_row(MemberRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.nick, serializer);
    sse_encode_opt_String(self.authoredName, serializer);
    sse_encode_bool(self.admin, serializer);
  }

  @protected
  void sse_encode_missing(Missing self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_notice_row(NoticeRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.said, serializer);
    sse_encode_opt_String(self.launched, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_book_facts(
      BookFacts? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_book_facts(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_diagnosis_row(
      DiagnosisRow? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_diagnosis_row(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_host_facts(
      HostFacts? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_host_facts(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_mcp_binding_row(
      McpBindingRow? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mcp_binding_row(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_missing(
      Missing? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_missing(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_presence_view(
      PresenceView? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_presence_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_space_row(
      SpaceRow? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_space_row(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_staleness(
      Staleness? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_staleness(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_library_row(
      List<LibraryRow>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_library_row(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_world_person_row(
      List<WorldPersonRow>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_world_person_row(self, serializer);
    }
  }

  @protected
  void sse_encode_orbit_row(OrbitRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.space, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lastOpened, serializer);
  }

  @protected
  void sse_encode_presence_view(PresenceView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_space_row(SpaceRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.space, serializer);
    sse_encode_opt_String(self.whoami, serializer);
    sse_encode_bool(self.admin, serializer);
    sse_encode_list_member_row(self.members, serializer);
    sse_encode_list_String(self.devices, serializer);
    sse_encode_opt_box_autoadd_diagnosis_row(self.diagnosis, serializer);
  }

  @protected
  void sse_encode_staleness(Staleness self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Staleness_NeverLoaded():
        sse_encode_i_32(0, serializer);
      case Staleness_Signalled(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_storage_row(StorageRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.orbit, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_64(self.bytesOnDisk, serializer);
    sse_encode_opt_box_autoadd_u_64(self.objectCount, serializer);
    sse_encode_opt_box_autoadd_u_64(self.lastVerifiedMs, serializer);
    sse_encode_opt_box_autoadd_missing(self.missing, serializer);
  }

  @protected
  void sse_encode_suggestion_row(SuggestionRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.suggestion, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_list_String(self.handles, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_world_artwork(WorldArtwork self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.mark, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.hero, serializer);
  }

  @protected
  void sse_encode_world_person_row(
      WorldPersonRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.picture, serializer);
    sse_encode_opt_box_autoadd_presence_view(self.presence, serializer);
    sse_encode_bool(self.agent, serializer);
    sse_encode_bool(self.here, serializer);
  }
}
