// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class CoreApiImplPlatform extends BaseApiImpl<CoreWire> {
  CoreApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ClientView> dco_decode_StreamSink_client_view_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ViewPush dco_decode_TraitDef_ViewPush(dynamic raw);

  @protected
  ActionRequest dco_decode_action_request(dynamic raw);

  @protected
  BookFacts dco_decode_book_facts(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActionRequest dco_decode_box_autoadd_action_request(dynamic raw);

  @protected
  BookFacts dco_decode_box_autoadd_book_facts(dynamic raw);

  @protected
  ClientView dco_decode_box_autoadd_client_view(dynamic raw);

  @protected
  DiagnosisRow dco_decode_box_autoadd_diagnosis_row(dynamic raw);

  @protected
  DisplayFacts dco_decode_box_autoadd_display_facts(dynamic raw);

  @protected
  DisplayHealthRow dco_decode_box_autoadd_display_health_row(dynamic raw);

  @protected
  DisplaySyncMode dco_decode_box_autoadd_display_sync_mode(dynamic raw);

  @protected
  HostFacts dco_decode_box_autoadd_host_facts(dynamic raw);

  @protected
  McpBindingRow dco_decode_box_autoadd_mcp_binding_row(dynamic raw);

  @protected
  Missing dco_decode_box_autoadd_missing(dynamic raw);

  @protected
  PresenceView dco_decode_box_autoadd_presence_view(dynamic raw);

  @protected
  SpaceRow dco_decode_box_autoadd_space_row(dynamic raw);

  @protected
  Staleness dco_decode_box_autoadd_staleness(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CardRow dco_decode_card_row(dynamic raw);

  @protected
  ClientView dco_decode_client_view(dynamic raw);

  @protected
  DeviceRow dco_decode_device_row(dynamic raw);

  @protected
  DiagnosisRow dco_decode_diagnosis_row(dynamic raw);

  @protected
  DisplayAssignmentRow dco_decode_display_assignment_row(dynamic raw);

  @protected
  DisplayFacts dco_decode_display_facts(dynamic raw);

  @protected
  DisplayHealthRow dco_decode_display_health_row(dynamic raw);

  @protected
  DisplayPairingRow dco_decode_display_pairing_row(dynamic raw);

  @protected
  DisplayReceiverRow dco_decode_display_receiver_row(dynamic raw);

  @protected
  DisplayStaleAction dco_decode_display_stale_action(dynamic raw);

  @protected
  DisplaySurfaceRow dco_decode_display_surface_row(dynamic raw);

  @protected
  DisplaySyncMode dco_decode_display_sync_mode(dynamic raw);

  @protected
  DisplayTheme dco_decode_display_theme(dynamic raw);

  @protected
  FailureRow dco_decode_failure_row(dynamic raw);

  @protected
  GateRow dco_decode_gate_row(dynamic raw);

  @protected
  GateState dco_decode_gate_state(dynamic raw);

  @protected
  HeadRow dco_decode_head_row(dynamic raw);

  @protected
  HostFacts dco_decode_host_facts(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LibraryRow dco_decode_library_row(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CardRow> dco_decode_list_card_row(dynamic raw);

  @protected
  List<DeviceRow> dco_decode_list_device_row(dynamic raw);

  @protected
  List<DisplayAssignmentRow> dco_decode_list_display_assignment_row(
      dynamic raw);

  @protected
  List<DisplayPairingRow> dco_decode_list_display_pairing_row(dynamic raw);

  @protected
  List<DisplayReceiverRow> dco_decode_list_display_receiver_row(dynamic raw);

  @protected
  List<DisplaySurfaceRow> dco_decode_list_display_surface_row(dynamic raw);

  @protected
  List<FailureRow> dco_decode_list_failure_row(dynamic raw);

  @protected
  List<GateRow> dco_decode_list_gate_row(dynamic raw);

  @protected
  List<HeadRow> dco_decode_list_head_row(dynamic raw);

  @protected
  List<LibraryRow> dco_decode_list_library_row(dynamic raw);

  @protected
  List<MemberRow> dco_decode_list_member_row(dynamic raw);

  @protected
  List<NoticeRow> dco_decode_list_notice_row(dynamic raw);

  @protected
  List<OrbitRow> dco_decode_list_orbit_row(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StorageRow> dco_decode_list_storage_row(dynamic raw);

  @protected
  List<SuggestionRow> dco_decode_list_suggestion_row(dynamic raw);

  @protected
  List<WorldPersonRow> dco_decode_list_world_person_row(dynamic raw);

  @protected
  McpBindingRow dco_decode_mcp_binding_row(dynamic raw);

  @protected
  MemberRow dco_decode_member_row(dynamic raw);

  @protected
  Missing dco_decode_missing(dynamic raw);

  @protected
  NoticeRow dco_decode_notice_row(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BookFacts? dco_decode_opt_box_autoadd_book_facts(dynamic raw);

  @protected
  DiagnosisRow? dco_decode_opt_box_autoadd_diagnosis_row(dynamic raw);

  @protected
  DisplayFacts? dco_decode_opt_box_autoadd_display_facts(dynamic raw);

  @protected
  DisplayHealthRow? dco_decode_opt_box_autoadd_display_health_row(dynamic raw);

  @protected
  DisplaySyncMode? dco_decode_opt_box_autoadd_display_sync_mode(dynamic raw);

  @protected
  HostFacts? dco_decode_opt_box_autoadd_host_facts(dynamic raw);

  @protected
  McpBindingRow? dco_decode_opt_box_autoadd_mcp_binding_row(dynamic raw);

  @protected
  Missing? dco_decode_opt_box_autoadd_missing(dynamic raw);

  @protected
  PresenceView? dco_decode_opt_box_autoadd_presence_view(dynamic raw);

  @protected
  SpaceRow? dco_decode_opt_box_autoadd_space_row(dynamic raw);

  @protected
  Staleness? dco_decode_opt_box_autoadd_staleness(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<LibraryRow>? dco_decode_opt_list_library_row(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<WorldPersonRow>? dco_decode_opt_list_world_person_row(dynamic raw);

  @protected
  OrbitRow dco_decode_orbit_row(dynamic raw);

  @protected
  PresenceView dco_decode_presence_view(dynamic raw);

  @protected
  SpaceRow dco_decode_space_row(dynamic raw);

  @protected
  Staleness dco_decode_staleness(dynamic raw);

  @protected
  StorageRow dco_decode_storage_row(dynamic raw);

  @protected
  SuggestionRow dco_decode_suggestion_row(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorldArtwork dco_decode_world_artwork(dynamic raw);

  @protected
  WorldPersonRow dco_decode_world_person_row(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ClientView> sse_decode_StreamSink_client_view_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionRequest sse_decode_action_request(SseDeserializer deserializer);

  @protected
  BookFacts sse_decode_book_facts(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActionRequest sse_decode_box_autoadd_action_request(
      SseDeserializer deserializer);

  @protected
  BookFacts sse_decode_box_autoadd_book_facts(SseDeserializer deserializer);

  @protected
  ClientView sse_decode_box_autoadd_client_view(SseDeserializer deserializer);

  @protected
  DiagnosisRow sse_decode_box_autoadd_diagnosis_row(
      SseDeserializer deserializer);

  @protected
  DisplayFacts sse_decode_box_autoadd_display_facts(
      SseDeserializer deserializer);

  @protected
  DisplayHealthRow sse_decode_box_autoadd_display_health_row(
      SseDeserializer deserializer);

  @protected
  DisplaySyncMode sse_decode_box_autoadd_display_sync_mode(
      SseDeserializer deserializer);

  @protected
  HostFacts sse_decode_box_autoadd_host_facts(SseDeserializer deserializer);

  @protected
  McpBindingRow sse_decode_box_autoadd_mcp_binding_row(
      SseDeserializer deserializer);

  @protected
  Missing sse_decode_box_autoadd_missing(SseDeserializer deserializer);

  @protected
  PresenceView sse_decode_box_autoadd_presence_view(
      SseDeserializer deserializer);

  @protected
  SpaceRow sse_decode_box_autoadd_space_row(SseDeserializer deserializer);

  @protected
  Staleness sse_decode_box_autoadd_staleness(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CardRow sse_decode_card_row(SseDeserializer deserializer);

  @protected
  ClientView sse_decode_client_view(SseDeserializer deserializer);

  @protected
  DeviceRow sse_decode_device_row(SseDeserializer deserializer);

  @protected
  DiagnosisRow sse_decode_diagnosis_row(SseDeserializer deserializer);

  @protected
  DisplayAssignmentRow sse_decode_display_assignment_row(
      SseDeserializer deserializer);

  @protected
  DisplayFacts sse_decode_display_facts(SseDeserializer deserializer);

  @protected
  DisplayHealthRow sse_decode_display_health_row(SseDeserializer deserializer);

  @protected
  DisplayPairingRow sse_decode_display_pairing_row(
      SseDeserializer deserializer);

  @protected
  DisplayReceiverRow sse_decode_display_receiver_row(
      SseDeserializer deserializer);

  @protected
  DisplayStaleAction sse_decode_display_stale_action(
      SseDeserializer deserializer);

  @protected
  DisplaySurfaceRow sse_decode_display_surface_row(
      SseDeserializer deserializer);

  @protected
  DisplaySyncMode sse_decode_display_sync_mode(SseDeserializer deserializer);

  @protected
  DisplayTheme sse_decode_display_theme(SseDeserializer deserializer);

  @protected
  FailureRow sse_decode_failure_row(SseDeserializer deserializer);

  @protected
  GateRow sse_decode_gate_row(SseDeserializer deserializer);

  @protected
  GateState sse_decode_gate_state(SseDeserializer deserializer);

  @protected
  HeadRow sse_decode_head_row(SseDeserializer deserializer);

  @protected
  HostFacts sse_decode_host_facts(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LibraryRow sse_decode_library_row(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CardRow> sse_decode_list_card_row(SseDeserializer deserializer);

  @protected
  List<DeviceRow> sse_decode_list_device_row(SseDeserializer deserializer);

  @protected
  List<DisplayAssignmentRow> sse_decode_list_display_assignment_row(
      SseDeserializer deserializer);

  @protected
  List<DisplayPairingRow> sse_decode_list_display_pairing_row(
      SseDeserializer deserializer);

  @protected
  List<DisplayReceiverRow> sse_decode_list_display_receiver_row(
      SseDeserializer deserializer);

  @protected
  List<DisplaySurfaceRow> sse_decode_list_display_surface_row(
      SseDeserializer deserializer);

  @protected
  List<FailureRow> sse_decode_list_failure_row(SseDeserializer deserializer);

  @protected
  List<GateRow> sse_decode_list_gate_row(SseDeserializer deserializer);

  @protected
  List<HeadRow> sse_decode_list_head_row(SseDeserializer deserializer);

  @protected
  List<LibraryRow> sse_decode_list_library_row(SseDeserializer deserializer);

  @protected
  List<MemberRow> sse_decode_list_member_row(SseDeserializer deserializer);

  @protected
  List<NoticeRow> sse_decode_list_notice_row(SseDeserializer deserializer);

  @protected
  List<OrbitRow> sse_decode_list_orbit_row(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StorageRow> sse_decode_list_storage_row(SseDeserializer deserializer);

  @protected
  List<SuggestionRow> sse_decode_list_suggestion_row(
      SseDeserializer deserializer);

  @protected
  List<WorldPersonRow> sse_decode_list_world_person_row(
      SseDeserializer deserializer);

  @protected
  McpBindingRow sse_decode_mcp_binding_row(SseDeserializer deserializer);

  @protected
  MemberRow sse_decode_member_row(SseDeserializer deserializer);

  @protected
  Missing sse_decode_missing(SseDeserializer deserializer);

  @protected
  NoticeRow sse_decode_notice_row(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BookFacts? sse_decode_opt_box_autoadd_book_facts(
      SseDeserializer deserializer);

  @protected
  DiagnosisRow? sse_decode_opt_box_autoadd_diagnosis_row(
      SseDeserializer deserializer);

  @protected
  DisplayFacts? sse_decode_opt_box_autoadd_display_facts(
      SseDeserializer deserializer);

  @protected
  DisplayHealthRow? sse_decode_opt_box_autoadd_display_health_row(
      SseDeserializer deserializer);

  @protected
  DisplaySyncMode? sse_decode_opt_box_autoadd_display_sync_mode(
      SseDeserializer deserializer);

  @protected
  HostFacts? sse_decode_opt_box_autoadd_host_facts(
      SseDeserializer deserializer);

  @protected
  McpBindingRow? sse_decode_opt_box_autoadd_mcp_binding_row(
      SseDeserializer deserializer);

  @protected
  Missing? sse_decode_opt_box_autoadd_missing(SseDeserializer deserializer);

  @protected
  PresenceView? sse_decode_opt_box_autoadd_presence_view(
      SseDeserializer deserializer);

  @protected
  SpaceRow? sse_decode_opt_box_autoadd_space_row(SseDeserializer deserializer);

  @protected
  Staleness? sse_decode_opt_box_autoadd_staleness(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<LibraryRow>? sse_decode_opt_list_library_row(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<WorldPersonRow>? sse_decode_opt_list_world_person_row(
      SseDeserializer deserializer);

  @protected
  OrbitRow sse_decode_orbit_row(SseDeserializer deserializer);

  @protected
  PresenceView sse_decode_presence_view(SseDeserializer deserializer);

  @protected
  SpaceRow sse_decode_space_row(SseDeserializer deserializer);

  @protected
  Staleness sse_decode_staleness(SseDeserializer deserializer);

  @protected
  StorageRow sse_decode_storage_row(SseDeserializer deserializer);

  @protected
  SuggestionRow sse_decode_suggestion_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorldArtwork sse_decode_world_artwork(SseDeserializer deserializer);

  @protected
  WorldPersonRow sse_decode_world_person_row(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_client_view_Sse(
      RustStreamSink<ClientView> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_request(ActionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_book_facts(BookFacts self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_action_request(
      ActionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_book_facts(
      BookFacts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_view(
      ClientView self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_diagnosis_row(
      DiagnosisRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_display_facts(
      DisplayFacts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_display_health_row(
      DisplayHealthRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_display_sync_mode(
      DisplaySyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_host_facts(
      HostFacts self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mcp_binding_row(
      McpBindingRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_missing(Missing self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_presence_view(
      PresenceView self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_space_row(
      SpaceRow self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_staleness(
      Staleness self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_card_row(CardRow self, SseSerializer serializer);

  @protected
  void sse_encode_client_view(ClientView self, SseSerializer serializer);

  @protected
  void sse_encode_device_row(DeviceRow self, SseSerializer serializer);

  @protected
  void sse_encode_diagnosis_row(DiagnosisRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_assignment_row(
      DisplayAssignmentRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_facts(DisplayFacts self, SseSerializer serializer);

  @protected
  void sse_encode_display_health_row(
      DisplayHealthRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_pairing_row(
      DisplayPairingRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_receiver_row(
      DisplayReceiverRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_stale_action(
      DisplayStaleAction self, SseSerializer serializer);

  @protected
  void sse_encode_display_surface_row(
      DisplaySurfaceRow self, SseSerializer serializer);

  @protected
  void sse_encode_display_sync_mode(
      DisplaySyncMode self, SseSerializer serializer);

  @protected
  void sse_encode_display_theme(DisplayTheme self, SseSerializer serializer);

  @protected
  void sse_encode_failure_row(FailureRow self, SseSerializer serializer);

  @protected
  void sse_encode_gate_row(GateRow self, SseSerializer serializer);

  @protected
  void sse_encode_gate_state(GateState self, SseSerializer serializer);

  @protected
  void sse_encode_head_row(HeadRow self, SseSerializer serializer);

  @protected
  void sse_encode_host_facts(HostFacts self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_library_row(LibraryRow self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_card_row(List<CardRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_device_row(
      List<DeviceRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_display_assignment_row(
      List<DisplayAssignmentRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_display_pairing_row(
      List<DisplayPairingRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_display_receiver_row(
      List<DisplayReceiverRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_display_surface_row(
      List<DisplaySurfaceRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_failure_row(
      List<FailureRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gate_row(List<GateRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_head_row(List<HeadRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_library_row(
      List<LibraryRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_member_row(
      List<MemberRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_notice_row(
      List<NoticeRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_orbit_row(List<OrbitRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_storage_row(
      List<StorageRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_suggestion_row(
      List<SuggestionRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_world_person_row(
      List<WorldPersonRow> self, SseSerializer serializer);

  @protected
  void sse_encode_mcp_binding_row(McpBindingRow self, SseSerializer serializer);

  @protected
  void sse_encode_member_row(MemberRow self, SseSerializer serializer);

  @protected
  void sse_encode_missing(Missing self, SseSerializer serializer);

  @protected
  void sse_encode_notice_row(NoticeRow self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_book_facts(
      BookFacts? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_diagnosis_row(
      DiagnosisRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_display_facts(
      DisplayFacts? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_display_health_row(
      DisplayHealthRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_display_sync_mode(
      DisplaySyncMode? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_host_facts(
      HostFacts? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mcp_binding_row(
      McpBindingRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_missing(
      Missing? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_presence_view(
      PresenceView? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_space_row(
      SpaceRow? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_staleness(
      Staleness? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_library_row(
      List<LibraryRow>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_world_person_row(
      List<WorldPersonRow>? self, SseSerializer serializer);

  @protected
  void sse_encode_orbit_row(OrbitRow self, SseSerializer serializer);

  @protected
  void sse_encode_presence_view(PresenceView self, SseSerializer serializer);

  @protected
  void sse_encode_space_row(SpaceRow self, SseSerializer serializer);

  @protected
  void sse_encode_staleness(Staleness self, SseSerializer serializer);

  @protected
  void sse_encode_storage_row(StorageRow self, SseSerializer serializer);

  @protected
  void sse_encode_suggestion_row(SuggestionRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_world_artwork(WorldArtwork self, SseSerializer serializer);

  @protected
  void sse_encode_world_person_row(
      WorldPersonRow self, SseSerializer serializer);
}

// Section: wire_class

class CoreWire implements BaseWire {
  factory CoreWire.fromExternalLibrary(ExternalLibrary lib) =>
      CoreWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CoreWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
}
